; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v \
; RUN:   -verify-machineinstrs | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v \
; RUN:   -verify-machineinstrs | FileCheck %s

declare <8 x i16> @llvm.riscv.vadd(<8 x i16>, <8 x i16>, <8 x i16>, iXLen)
declare <8 x i32> @llvm.riscv.vwadd(<8 x i32>, <8 x i16>, <8 x i16>, iXLen)

define <8 x i16> @fixed_vectors_intrinsic_vadd(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: fixed_vectors_intrinsic_vadd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    ret
entry:
    %res = call <8 x i16> @llvm.riscv.vadd(<8 x i16> poison, <8 x i16> %a, <8 x i16> %b, iXLen 8)
    ret <8 x i16> %res
}

define <8 x i32> @fixed_vectors_intrinsic_vwadd(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: fixed_vectors_intrinsic_vwadd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    vmv1r.v v11, v8
; CHECK-NEXT:    vwadd.vv v8, v11, v10
; CHECK-NEXT:    ret
entry:
    %res = call <8 x i32> @llvm.riscv.vwadd(<8 x i32> poison, <8 x i16> %a, <8 x i16> %b, iXLen 8)
    ret <8 x i32> %res
}
