; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+v -stop-after=finalize-isel < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+v -stop-after=finalize-isel --riscv-v-vector-bits-min=256 --riscv-v-vector-bits-max=256 < %s | FileCheck %s --check-prefixes=KNOWN-VLEN

define dso_local void @move_vector(ptr %a, ptr %b) {
  ; CHECK-LABEL: name: move_vector
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gprnox0 = ADDI $x0, 32
  ; CHECK-NEXT:   [[PseudoVLE32_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE32_V_M4 $noreg, [[COPY1]], [[ADDI]], 5 /* e32 */, 2 /* tu, ma */ :: (load (<vscale x 1 x s256>) from %ir.a, align 4)
  ; CHECK-NEXT:   PseudoVSE32_V_M4 killed [[PseudoVLE32_V_M4_]], [[COPY]], [[ADDI]], 5 /* e32 */ :: (store (<vscale x 1 x s256>) into %ir.b, align 4)
  ; CHECK-NEXT:   PseudoRET
  ;
  ; KNOWN-VLEN-LABEL: name: move_vector
  ; KNOWN-VLEN: bb.0.entry:
  ; KNOWN-VLEN-NEXT:   liveins: $x10, $x11
  ; KNOWN-VLEN-NEXT: {{  $}}
  ; KNOWN-VLEN-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; KNOWN-VLEN-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; KNOWN-VLEN-NEXT:   [[ADDI:%[0-9]+]]:gprnox0 = ADDI $x0, 32
  ; KNOWN-VLEN-NEXT:   [[PseudoVLE32_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE32_V_M4 $noreg, [[COPY1]], [[ADDI]], 5 /* e32 */, 2 /* tu, ma */ :: (load (s1024) from %ir.a, align 4)
  ; KNOWN-VLEN-NEXT:   PseudoVSE32_V_M4 killed [[PseudoVLE32_V_M4_]], [[COPY]], [[ADDI]], 5 /* e32 */ :: (store (s1024) into %ir.b, align 4)
  ; KNOWN-VLEN-NEXT:   PseudoRET
entry:
  %0 = tail call <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.i64(<vscale x 8 x i32> poison, ptr %a, i64 32)
  tail call void @llvm.riscv.vse.nxv8i32.i64(<vscale x 8 x i32> %0, ptr %b, i64 32)
  ret void
}
