; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+m,+v -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64 -mattr=+m,+v -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV64

define void @matmul_min(ptr %vptr, ptr %scalars, ptr %acc0_ptr, ptr %acc1_ptr) {
; CHECK-LABEL: matmul_min:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 64
; CHECK-NEXT:    li a5, 32
; CHECK-NEXT:    vsetvli zero, a5, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v16, (a0)
; CHECK-NEXT:    lb a0, 0(a1)
; CHECK-NEXT:    lb a1, 1(a1)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vle8.v v12, (a3)
; CHECK-NEXT:    vsetvli zero, a5, e8, m2, ta, ma
; CHECK-NEXT:    vwmacc.vx v8, a0, v16
; CHECK-NEXT:    vwmacc.vx v12, a1, v16
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    vse8.v v12, (a3)
; CHECK-NEXT:    ret
entry:
  %acc0 = load <32 x i16>, ptr %acc0_ptr, align 1
  %acc1 = load <32 x i16>, ptr %acc1_ptr, align 1

  %v8 = load <32 x i8>, ptr %vptr, align 1
  %v16 = sext <32 x i8> %v8 to <32 x i16>

  %s0_ptr = getelementptr i8, ptr %scalars, i32 0
  %s0_i8 = load i8, ptr %s0_ptr, align 1
  %s0_i16 = sext i8 %s0_i8 to i16
  %tmp0 = insertelement <32 x i16> poison, i16 %s0_i16, i32 0
  %splat0 = shufflevector <32 x i16> %tmp0, <32 x i16> poison, <32 x i32> zeroinitializer
  %mul0 = mul <32 x i16> %splat0, %v16
  %add0 = add <32 x i16> %mul0, %acc0

  %s1_ptr = getelementptr i8, ptr %scalars, i32 1
  %s1_i8 = load i8, ptr %s1_ptr, align 1
  %s1_i16 = sext i8 %s1_i8 to i16
  %tmp1 = insertelement <32 x i16> poison, i16 %s1_i16, i32 0
  %splat1 = shufflevector <32 x i16> %tmp1, <32 x i16> poison, <32 x i32> zeroinitializer
  %mul1 = mul <32 x i16> %splat1, %v16
  %add1 = add <32 x i16> %mul1, %acc1

  store <32 x i16> %add0, ptr %acc0_ptr, align 1
  store <32 x i16> %add1, ptr %acc1_ptr, align 1

  ret void
}

; This function comes from the core part of the quantized operator "q4k_q8k_gemm" and is mainly used to test whether instruction combining and instruction scheduling are working correctly.
; To simplify debugging, only the parts that are prone to issues have been retained. The q4 decompression and subsequent dequantization operations have been removed.
;
; @q4k_q8k_gemm_kernel was generated by the following python script:
;
; ```
; def gen_q4k_q8k_gemm_kernel(mr: int, k_iters: int, loop_count: int = 8):
;     lines = []
;
;     def emit(s=""):
;         lines.append(s)
;
;     emit(f"define void @q4k_q8k_gemm_kernel(ptr %a_ptr, ptr %w_ptr, ptr %scale_ptr, ptr %res_ptr) {{")
;     emit("entry:")
;
;     emit(f"  br label %loop")
;
;     # ---- loop body ----
;     emit("loop:")
;
;     # ---- phi ----
;     for j in range(mr):
;         emit(f"  %acc_{j} = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_{j}_new, %loop ]")
;
;     emit(f"  %a_iter_ptr = phi ptr [ %a_ptr, %entry ], [ %a_iter_next, %loop ]")
;     emit(f"  %w_iter_ptr = phi ptr [ %w_ptr, %entry ], [ %w_iter_next, %loop ]")
;     emit(f"  %scale_iter_ptr = phi ptr [ %scale_ptr, %entry ], [ %scale_iter_next, %loop ]")
;
;     emit(f"  %loop_idx = phi i32 [0, %entry], [%loop_next, %loop]")
;
;     # ---- inner K-loop ----
;     for k in range(k_iters):
;         emit(f"  %w_{k}_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 {k}")
;         emit(f"  %w_{k}_i8 = load <vscale x 8 x i8>, ptr %w_{k}_ptr")
;         emit(f"  %w_{k}_i16 = sext <vscale x 8 x i8> %w_{k}_i8 to <vscale x 8 x i16>")
;         emit("")
;
;         emit(f"  %a_{k}_ptr = getelementptr <{mr} x i8>, ptr %a_iter_ptr, i32 {k}")
;         for j in range(mr):
;             emit(f"  %a_{k}_{j}_ptr = getelementptr i8, ptr %a_{k}_ptr, i32 {j}")
;             emit(f"  %a_{k}_{j}_i8 = load i8, ptr %a_{k}_{j}_ptr")
;             emit(f"  %a_{k}_{j}_i16 = sext i8 %a_{k}_{j}_i8 to i16")
;             # splat
;             emit(f"  %a_{k}_{j}_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_{k}_{j}_i16, i32 0")
;             emit(f"  %a_{k}_{j}_vsplat = shufflevector <vscale x 8 x i16> %a_{k}_{j}_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer")
;             # mul + add
;             emit(f"  %mul_{k}_{j} = mul <vscale x 8 x i16> %a_{k}_{j}_vsplat, %w_{k}_i16")
;             if k == 0:
;                 emit(f"  %add_{k}_{j} = add <vscale x 8 x i16> %mul_{k}_{j}, zeroinitializer")
;             else:
;                 emit(f"  %add_{k}_{j} = add <vscale x 8 x i16> %mul_{k}_{j}, %add_{k-1}_{j}")
;         emit("")
;
;     # ---- load scale ----
;     emit("  %scale_i8 = load <vscale x 8 x i8>, ptr %scale_iter_ptr")
;     emit("  %scale_i32 = sext <vscale x 8 x i8> %scale_i8 to <vscale x 8 x i32>")
;     emit("")
;
;     # ---- convert to i32 and scale ----
;     last_k = k_iters - 1
;     for j in range(mr):
;         emit(f"  %add_{j}_i32 = sext <vscale x 8 x i16> %add_{last_k}_{j} to <vscale x 8 x i32>")
;         emit(f"  %scaled_{j} = mul <vscale x 8 x i32> %add_{j}_i32, %scale_i32")
;         emit(f"  %acc_{j}_new = add <vscale x 8 x i32> %acc_{j}, %scaled_{j}")
;     emit("")
;
;     # ---- increment pointers ----
;     emit(f"  %a_iter_next = getelementptr <{mr} x i8>, ptr %a_iter_ptr, i32 {k_iters}")
;     emit(f"  %w_iter_next = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 {k_iters}")
;     emit(f"  %scale_iter_next = getelementptr <vscale x 8 x i8>, ptr %scale_iter_ptr, i32 1")
;
;     # ---- loop increment ----
;     emit(f"  %loop_next = add i32 %loop_idx, 1")
;     emit(f"  %loop_cond = icmp slt i32 %loop_next, {loop_count}")
;     emit(f"  br i1 %loop_cond, label %loop, label %loop_end")
;     emit("")
;
;     # ---- writeback ----
;     emit("loop_end:")
;     for j in range(mr):
;         emit(f"  %res_{j}_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 {j}")
;         emit(f"  store <vscale x 8 x i32> %acc_{j}, ptr %res_{j}_ptr")
;     emit("")
;     emit("  ret void")
;     emit("}")
;
;     return "\n".join(lines)
;
;
; if __name__ == '__main__':
;     print(gen_q4k_q8k_gemm_kernel(mr=12, k_iters=32, loop_count=8))
;
; ```
define void @q4k_q8k_gemm_kernel(ptr %a_ptr, ptr %w_ptr, ptr %scale_ptr, ptr %res_ptr) {
; RV32-LABEL: q4k_q8k_gemm_kernel:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    addi sp, sp, -496
; RV32-NEXT:    .cfi_def_cfa_offset 496
; RV32-NEXT:    sw ra, 492(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 488(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s1, 484(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s2, 480(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s3, 476(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s4, 472(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s5, 468(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s6, 464(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s7, 460(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s8, 456(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s9, 452(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s10, 448(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s11, 444(sp) # 4-byte Folded Spill
; RV32-NEXT:    .cfi_offset ra, -4
; RV32-NEXT:    .cfi_offset s0, -8
; RV32-NEXT:    .cfi_offset s1, -12
; RV32-NEXT:    .cfi_offset s2, -16
; RV32-NEXT:    .cfi_offset s3, -20
; RV32-NEXT:    .cfi_offset s4, -24
; RV32-NEXT:    .cfi_offset s5, -28
; RV32-NEXT:    .cfi_offset s6, -32
; RV32-NEXT:    .cfi_offset s7, -36
; RV32-NEXT:    .cfi_offset s8, -40
; RV32-NEXT:    .cfi_offset s9, -44
; RV32-NEXT:    .cfi_offset s10, -48
; RV32-NEXT:    .cfi_offset s11, -52
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 118
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    sub sp, sp, a4
; RV32-NEXT:    .cfi_escape 0x0f, 0x0f, 0x72, 0x00, 0x11, 0xf0, 0x03, 0x22, 0x11, 0xf6, 0x00, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 496 + 118 * vlenb
; RV32-NEXT:    sw a3, 8(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv s1, a2
; RV32-NEXT:    mv s2, a1
; RV32-NEXT:    lui a1, 1
; RV32-NEXT:    vsetvli a2, zero, e32, m4, ta, ma
; RV32-NEXT:    vmv.v.i v8, 0
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li a2, 10
; RV32-NEXT:    li a3, 11
; RV32-NEXT:    li a4, 13
; RV32-NEXT:    li a5, 18
; RV32-NEXT:    li a6, 19
; RV32-NEXT:    li a7, 20
; RV32-NEXT:    li t0, 21
; RV32-NEXT:    li t1, 22
; RV32-NEXT:    li t2, 23
; RV32-NEXT:    li t3, 25
; RV32-NEXT:    li t4, 26
; RV32-NEXT:    li t5, 27
; RV32-NEXT:    li t6, 29
; RV32-NEXT:    add a1, a0, a1
; RV32-NEXT:    sw a1, 104(sp) # 4-byte Folded Spill
; RV32-NEXT:    slli s5, s0, 1
; RV32-NEXT:    slli s4, s0, 2
; RV32-NEXT:    slli s3, s0, 3
; RV32-NEXT:    mul a1, s0, a2
; RV32-NEXT:    sw a1, 96(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a1, s0, a3
; RV32-NEXT:    sw a1, 92(sp) # 4-byte Folded Spill
; RV32-NEXT:    slli a2, s0, 4
; RV32-NEXT:    mul a1, s0, a4
; RV32-NEXT:    sw a1, 88(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a1, s0, a5
; RV32-NEXT:    sw a1, 84(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a1, s0, a6
; RV32-NEXT:    sw a1, 80(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a1, s0, a7
; RV32-NEXT:    sw a1, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a1, s0, t0
; RV32-NEXT:    sw a1, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a1, s0, t1
; RV32-NEXT:    sw a1, 68(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a1, s0, t2
; RV32-NEXT:    sw a1, 64(sp) # 4-byte Folded Spill
; RV32-NEXT:    slli a1, s0, 5
; RV32-NEXT:    mul a3, s0, t3
; RV32-NEXT:    sw a3, 60(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a3, s0, t4
; RV32-NEXT:    sw a3, 56(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a3, s0, t5
; RV32-NEXT:    sw a3, 52(sp) # 4-byte Folded Spill
; RV32-NEXT:    mul a3, s0, t6
; RV32-NEXT:    sw a3, 48(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    li a4, 76
; RV32-NEXT:    mul a3, a3, a4
; RV32-NEXT:    add a3, sp, a3
; RV32-NEXT:    addi a3, a3, 432
; RV32-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    li a4, 72
; RV32-NEXT:    mul a3, a3, a4
; RV32-NEXT:    add a3, sp, a3
; RV32-NEXT:    addi a3, a3, 432
; RV32-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    li a4, 68
; RV32-NEXT:    mul a3, a3, a4
; RV32-NEXT:    add a3, sp, a3
; RV32-NEXT:    addi a3, a3, 432
; RV32-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    slli a3, a3, 6
; RV32-NEXT:    add a3, sp, a3
; RV32-NEXT:    addi a3, a3, 432
; RV32-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    li a4, 60
; RV32-NEXT:    mul a3, a3, a4
; RV32-NEXT:    add a3, sp, a3
; RV32-NEXT:    addi a3, a3, 432
; RV32-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    li a4, 56
; RV32-NEXT:    mul a3, a3, a4
; RV32-NEXT:    add a3, sp, a3
; RV32-NEXT:    addi a3, a3, 432
; RV32-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    li a4, 52
; RV32-NEXT:    mul a3, a3, a4
; RV32-NEXT:    add a3, sp, a3
; RV32-NEXT:    addi a3, a3, 432
; RV32-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV32-NEXT:    add a3, s5, s0
; RV32-NEXT:    sw a3, 44(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a3, s4, s0
; RV32-NEXT:    sw a3, 40(sp) # 4-byte Folded Spill
; RV32-NEXT:    sub a3, s3, s5
; RV32-NEXT:    sw a3, 36(sp) # 4-byte Folded Spill
; RV32-NEXT:    sub a3, s3, s0
; RV32-NEXT:    sw a3, 32(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a3, s3, s0
; RV32-NEXT:    sw a3, 28(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s4, 116(sp) # 4-byte Folded Spill
; RV32-NEXT:    sub a3, a2, s4
; RV32-NEXT:    sw a3, 108(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s5, 100(sp) # 4-byte Folded Spill
; RV32-NEXT:    sub a3, a2, s5
; RV32-NEXT:    sw a3, 24(sp) # 4-byte Folded Spill
; RV32-NEXT:    sub a3, a2, s0
; RV32-NEXT:    sw a3, 20(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 424(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a2, 124(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a2, a2, s0
; RV32-NEXT:    sw a2, 16(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a1, 416(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s3, 120(sp) # 4-byte Folded Spill
; RV32-NEXT:    sub a1, a1, s3
; RV32-NEXT:    sw a1, 112(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 48
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 44
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 40
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 80
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 36
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:  .LBB1_1: # %loop
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    sw s2, 420(sp) # 4-byte Folded Spill
; RV32-NEXT:    vl1r.v v6, (s2)
; RV32-NEXT:    lb a6, 0(a0)
; RV32-NEXT:    lb a1, 1(a0)
; RV32-NEXT:    sw a1, 380(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a1, 2(a0)
; RV32-NEXT:    sw a1, 400(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a1, 3(a0)
; RV32-NEXT:    sw a1, 412(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a1, 424(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a1, s2, a1
; RV32-NEXT:    lb a2, 16(a0)
; RV32-NEXT:    lb a3, 17(a0)
; RV32-NEXT:    sw a3, 368(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 18(a0)
; RV32-NEXT:    sw a3, 392(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 19(a0)
; RV32-NEXT:    sw a3, 408(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s4, 100(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t0, s2, s4
; RV32-NEXT:    lb s0, 32(a0)
; RV32-NEXT:    lb a3, 33(a0)
; RV32-NEXT:    sw a3, 360(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 34(a0)
; RV32-NEXT:    sw a3, 384(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 35(a0)
; RV32-NEXT:    sw a3, 404(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw t3, 44(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t3, s2, t3
; RV32-NEXT:    lb a7, 48(a0)
; RV32-NEXT:    lb a3, 49(a0)
; RV32-NEXT:    sw a3, 352(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 50(a0)
; RV32-NEXT:    sw a3, 372(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 51(a0)
; RV32-NEXT:    sw a3, 396(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw t6, 116(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t2, s2, t6
; RV32-NEXT:    lb a3, 64(a0)
; RV32-NEXT:    lb a4, 65(a0)
; RV32-NEXT:    sw a4, 348(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 66(a0)
; RV32-NEXT:    sw a4, 364(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 67(a0)
; RV32-NEXT:    sw a4, 388(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw t1, 40(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t1, s2, t1
; RV32-NEXT:    vl1r.v v12, (a1)
; RV32-NEXT:    lb a1, 80(a0)
; RV32-NEXT:    lb a4, 81(a0)
; RV32-NEXT:    sw a4, 344(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 82(a0)
; RV32-NEXT:    sw a4, 356(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 83(a0)
; RV32-NEXT:    sw a4, 376(sp) # 4-byte Folded Spill
; RV32-NEXT:    vl1r.v v13, (t0)
; RV32-NEXT:    lw t0, 36(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t0, s2, t0
; RV32-NEXT:    vl1r.v v18, (t3)
; RV32-NEXT:    lw t3, 32(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t3, s2, t3
; RV32-NEXT:    vl1r.v v19, (t2)
; RV32-NEXT:    lw t2, 120(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t2, s2, t2
; RV32-NEXT:    vl1r.v v24, (t1)
; RV32-NEXT:    lw t1, 28(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t1, s2, t1
; RV32-NEXT:    vl1r.v v29, (t0)
; RV32-NEXT:    lw t4, 96(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t4, s2, t4
; RV32-NEXT:    vl1r.v v16, (t3)
; RV32-NEXT:    lw t3, 92(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t3, s2, t3
; RV32-NEXT:    vl1r.v v27, (t2)
; RV32-NEXT:    lw t2, 108(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t2, s2, t2
; RV32-NEXT:    vl1r.v v7, (t1)
; RV32-NEXT:    lw t0, 88(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t0, s2, t0
; RV32-NEXT:    vl1r.v v5, (t4)
; RV32-NEXT:    lw t1, 24(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t1, s2, t1
; RV32-NEXT:    vl1r.v v4, (t3)
; RV32-NEXT:    lw t3, 20(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t3, s2, t3
; RV32-NEXT:    vl1r.v v3, (t2)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 92
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v3, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw t5, 124(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t5, s2, t5
; RV32-NEXT:    vl1r.v v28, (t0)
; RV32-NEXT:    lw t4, 16(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t4, s2, t4
; RV32-NEXT:    vl1r.v v2, (t1)
; RV32-NEXT:    lw t2, 84(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t2, s2, t2
; RV32-NEXT:    vl1r.v v0, (t3)
; RV32-NEXT:    lw t0, 80(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t0, s2, t0
; RV32-NEXT:    vl1r.v v30, (t5)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 93
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v30, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw t1, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t1, s2, t1
; RV32-NEXT:    vl1r.v v20, (t4)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 114
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v20, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw t3, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t3, s2, t3
; RV32-NEXT:    vl1r.v v15, (t2)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 113
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v15, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw t4, 68(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t4, s2, t4
; RV32-NEXT:    vl1r.v v14, (t0)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 102
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v14, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw t5, 64(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t5, s2, t5
; RV32-NEXT:    vl1r.v v1, (t1)
; RV32-NEXT:    lw t2, 112(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t2, s2, t2
; RV32-NEXT:    vl1r.v v31, (t3)
; RV32-NEXT:    lw t1, 60(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t1, s2, t1
; RV32-NEXT:    vl1r.v v26, (t4)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 104
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v26, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw t0, 56(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t0, s2, t0
; RV32-NEXT:    vl1r.v v25, (t5)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li a5, 94
; RV32-NEXT:    mul a4, a4, a5
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v25, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a5, 52(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a5, s2, a5
; RV32-NEXT:    vl1r.v v21, (t2)
; RV32-NEXT:    csrr a4, vlenb
; RV32-NEXT:    li t2, 117
; RV32-NEXT:    mul a4, a4, t2
; RV32-NEXT:    add a4, sp, a4
; RV32-NEXT:    addi a4, a4, 432
; RV32-NEXT:    vs1r.v v21, (a4) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a4, 416(sp) # 4-byte Folded Reload
; RV32-NEXT:    sub t2, a4, t6
; RV32-NEXT:    vl1r.v v22, (t1)
; RV32-NEXT:    csrr t1, vlenb
; RV32-NEXT:    li t3, 116
; RV32-NEXT:    mul t1, t1, t3
; RV32-NEXT:    add t1, sp, t1
; RV32-NEXT:    addi t1, t1, 432
; RV32-NEXT:    vs1r.v v22, (t1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw t1, 48(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t1, s2, t1
; RV32-NEXT:    vl1r.v v23, (t0)
; RV32-NEXT:    csrr t0, vlenb
; RV32-NEXT:    li t3, 108
; RV32-NEXT:    mul t0, t0, t3
; RV32-NEXT:    add t0, sp, t0
; RV32-NEXT:    addi t0, t0, 432
; RV32-NEXT:    vs1r.v v23, (t0) # vscale x 8-byte Folded Spill
; RV32-NEXT:    vl1r.v v10, (a5)
; RV32-NEXT:    csrr a5, vlenb
; RV32-NEXT:    li t0, 111
; RV32-NEXT:    mul a5, a5, t0
; RV32-NEXT:    add a5, sp, a5
; RV32-NEXT:    addi a5, a5, 432
; RV32-NEXT:    vs1r.v v10, (a5) # vscale x 8-byte Folded Spill
; RV32-NEXT:    sw t2, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a5, s2, t2
; RV32-NEXT:    vl1r.v v17, (t1)
; RV32-NEXT:    csrr t0, vlenb
; RV32-NEXT:    li t1, 112
; RV32-NEXT:    mul t0, t0, t1
; RV32-NEXT:    add t0, sp, t0
; RV32-NEXT:    addi t0, t0, 432
; RV32-NEXT:    vs1r.v v17, (t0) # vscale x 8-byte Folded Spill
; RV32-NEXT:    vl1r.v v11, (a5)
; RV32-NEXT:    csrr a5, vlenb
; RV32-NEXT:    li t0, 110
; RV32-NEXT:    mul a5, a5, t0
; RV32-NEXT:    add a5, sp, a5
; RV32-NEXT:    addi a5, a5, 432
; RV32-NEXT:    vs1r.v v11, (a5) # vscale x 8-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    vwmul.vx v8, v6, a6
; RV32-NEXT:    lb a5, 96(a0)
; RV32-NEXT:    lb a6, 97(a0)
; RV32-NEXT:    sw a6, 160(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 98(a0)
; RV32-NEXT:    sw a6, 264(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 99(a0)
; RV32-NEXT:    sw a6, 340(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a2, v12
; RV32-NEXT:    vwmacc.vx v8, s0, v13
; RV32-NEXT:    vwmacc.vx v8, a7, v18
; RV32-NEXT:    vwmacc.vx v8, a3, v19
; RV32-NEXT:    lb a2, 112(a0)
; RV32-NEXT:    lb a3, 113(a0)
; RV32-NEXT:    sw a3, 148(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 114(a0)
; RV32-NEXT:    sw a3, 252(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 115(a0)
; RV32-NEXT:    sw a3, 336(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v24
; RV32-NEXT:    vwmacc.vx v8, a5, v29
; RV32-NEXT:    vwmacc.vx v8, a2, v16
; RV32-NEXT:    lb a1, 128(a0)
; RV32-NEXT:    lb a2, 129(a0)
; RV32-NEXT:    sw a2, 136(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 130(a0)
; RV32-NEXT:    sw a2, 240(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 131(a0)
; RV32-NEXT:    sw a2, 332(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    lb a1, 144(a0)
; RV32-NEXT:    lb a2, 145(a0)
; RV32-NEXT:    sw a2, 132(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 146(a0)
; RV32-NEXT:    sw a2, 236(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 147(a0)
; RV32-NEXT:    sw a2, 328(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v7
; RV32-NEXT:    lb a1, 160(a0)
; RV32-NEXT:    lb ra, 161(a0)
; RV32-NEXT:    lb a2, 162(a0)
; RV32-NEXT:    sw a2, 228(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 163(a0)
; RV32-NEXT:    sw a2, 324(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v5
; RV32-NEXT:    lb a1, 176(a0)
; RV32-NEXT:    lb s11, 177(a0)
; RV32-NEXT:    lb a2, 178(a0)
; RV32-NEXT:    sw a2, 224(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 179(a0)
; RV32-NEXT:    sw a2, 320(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v4
; RV32-NEXT:    lb a1, 192(a0)
; RV32-NEXT:    lb s10, 193(a0)
; RV32-NEXT:    lb a2, 194(a0)
; RV32-NEXT:    sw a2, 220(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 195(a0)
; RV32-NEXT:    sw a2, 316(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    lb a1, 208(a0)
; RV32-NEXT:    lb s9, 209(a0)
; RV32-NEXT:    lb a2, 210(a0)
; RV32-NEXT:    sw a2, 216(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 211(a0)
; RV32-NEXT:    sw a2, 312(sp) # 4-byte Folded Spill
; RV32-NEXT:    vmv1r.v v3, v28
; RV32-NEXT:    vwmacc.vx v8, a1, v28
; RV32-NEXT:    lb a1, 224(a0)
; RV32-NEXT:    lb s8, 225(a0)
; RV32-NEXT:    lb a2, 226(a0)
; RV32-NEXT:    sw a2, 212(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 227(a0)
; RV32-NEXT:    sw a2, 308(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v2
; RV32-NEXT:    lb a1, 240(a0)
; RV32-NEXT:    lb s7, 241(a0)
; RV32-NEXT:    lb a2, 242(a0)
; RV32-NEXT:    sw a2, 208(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 243(a0)
; RV32-NEXT:    sw a2, 304(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v0
; RV32-NEXT:    lb a1, 256(a0)
; RV32-NEXT:    lb s6, 257(a0)
; RV32-NEXT:    lb a2, 258(a0)
; RV32-NEXT:    sw a2, 204(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 259(a0)
; RV32-NEXT:    sw a2, 300(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v30
; RV32-NEXT:    lb a1, 272(a0)
; RV32-NEXT:    lb s5, 273(a0)
; RV32-NEXT:    lb a2, 274(a0)
; RV32-NEXT:    sw a2, 200(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 275(a0)
; RV32-NEXT:    sw a2, 296(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    lb a1, 288(a0)
; RV32-NEXT:    lb s3, 289(a0)
; RV32-NEXT:    lb a2, 290(a0)
; RV32-NEXT:    sw a2, 196(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 291(a0)
; RV32-NEXT:    sw a2, 292(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v15
; RV32-NEXT:    lb a1, 304(a0)
; RV32-NEXT:    lb s0, 305(a0)
; RV32-NEXT:    lb a2, 306(a0)
; RV32-NEXT:    sw a2, 192(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 307(a0)
; RV32-NEXT:    sw a2, 288(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v14
; RV32-NEXT:    lb a1, 320(a0)
; RV32-NEXT:    lb t6, 321(a0)
; RV32-NEXT:    lb a2, 322(a0)
; RV32-NEXT:    sw a2, 188(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 323(a0)
; RV32-NEXT:    sw a2, 284(sp) # 4-byte Folded Spill
; RV32-NEXT:    vmv1r.v v28, v1
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 96
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vs1r.v v1, (a2) # vscale x 8-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v1
; RV32-NEXT:    lb a1, 336(a0)
; RV32-NEXT:    lb t5, 337(a0)
; RV32-NEXT:    lb a2, 338(a0)
; RV32-NEXT:    sw a2, 180(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 339(a0)
; RV32-NEXT:    sw a2, 280(sp) # 4-byte Folded Spill
; RV32-NEXT:    vmv1r.v v1, v31
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 95
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vs1r.v v31, (a2) # vscale x 8-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v31
; RV32-NEXT:    lb a1, 352(a0)
; RV32-NEXT:    lb t4, 353(a0)
; RV32-NEXT:    lb a2, 354(a0)
; RV32-NEXT:    sw a2, 176(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 355(a0)
; RV32-NEXT:    sw a2, 276(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v26
; RV32-NEXT:    lb a1, 368(a0)
; RV32-NEXT:    lb t3, 369(a0)
; RV32-NEXT:    lb a2, 370(a0)
; RV32-NEXT:    sw a2, 172(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 371(a0)
; RV32-NEXT:    sw a2, 272(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v25
; RV32-NEXT:    lb a1, 384(a0)
; RV32-NEXT:    lb t2, 385(a0)
; RV32-NEXT:    lb a2, 386(a0)
; RV32-NEXT:    sw a2, 168(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 387(a0)
; RV32-NEXT:    sw a2, 268(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v21
; RV32-NEXT:    lb a1, 400(a0)
; RV32-NEXT:    lb t1, 401(a0)
; RV32-NEXT:    lb a2, 402(a0)
; RV32-NEXT:    sw a2, 164(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 403(a0)
; RV32-NEXT:    sw a2, 260(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v22
; RV32-NEXT:    lb a1, 416(a0)
; RV32-NEXT:    lb t0, 417(a0)
; RV32-NEXT:    lb a2, 418(a0)
; RV32-NEXT:    sw a2, 156(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 419(a0)
; RV32-NEXT:    sw a2, 256(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v23
; RV32-NEXT:    lb a1, 432(a0)
; RV32-NEXT:    lb a7, 433(a0)
; RV32-NEXT:    lb a2, 434(a0)
; RV32-NEXT:    sw a2, 152(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 435(a0)
; RV32-NEXT:    sw a2, 248(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v10
; RV32-NEXT:    lb a1, 448(a0)
; RV32-NEXT:    lb a6, 449(a0)
; RV32-NEXT:    lb a2, 450(a0)
; RV32-NEXT:    sw a2, 144(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 451(a0)
; RV32-NEXT:    sw a2, 244(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v11
; RV32-NEXT:    lb a2, 464(a0)
; RV32-NEXT:    lb a5, 465(a0)
; RV32-NEXT:    lb a1, 466(a0)
; RV32-NEXT:    sw a1, 140(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a1, 467(a0)
; RV32-NEXT:    sw a1, 232(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a2, v17
; RV32-NEXT:    sub a2, a4, s4
; RV32-NEXT:    add a2, s2, a2
; RV32-NEXT:    lb a1, 480(a0)
; RV32-NEXT:    vl1r.v v10, (a2)
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 98
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vs1r.v v10, (a2) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lb a3, 481(a0)
; RV32-NEXT:    lb s2, 482(a0)
; RV32-NEXT:    lb a2, 483(a0)
; RV32-NEXT:    sw a2, 184(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v10
; RV32-NEXT:    lw a1, 424(sp) # 4-byte Folded Reload
; RV32-NEXT:    sub a2, a4, a1
; RV32-NEXT:    lw a4, 420(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a4, a4, a2
; RV32-NEXT:    lb a1, 496(a0)
; RV32-NEXT:    lb a2, 497(a0)
; RV32-NEXT:    vl1r.v v26, (a4)
; RV32-NEXT:    sw s1, 128(sp) # 4-byte Folded Spill
; RV32-NEXT:    vl1r.v v10, (s1)
; RV32-NEXT:    lb a4, 498(a0)
; RV32-NEXT:    lb s4, 499(a0)
; RV32-NEXT:    vwmacc.vx v8, a1, v26
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 107
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v26, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vsext.vf2 v14, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 80
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a1, a1, 5
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vwmacc.vv v20, v8, v14
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 100
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs2r.v v14, (a1) # vscale x 16-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 80
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vmv1r.v v11, v6
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 88
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v6, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 380(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v8, v6, a1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 97
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v12, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 368(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 115
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v13, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 360(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v13
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 106
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v18, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 352(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v18
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 105
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v19, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 348(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v19
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 109
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v24, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 344(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v24
; RV32-NEXT:    vmv1r.v v25, v29
; RV32-NEXT:    lw a1, 160(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v29
; RV32-NEXT:    lw a1, 148(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    lw a1, 136(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    lw a1, 132(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v7
; RV32-NEXT:    vwmacc.vx v8, ra, v5
; RV32-NEXT:    vwmacc.vx v8, s11, v4
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 92
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v6, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s10, v6
; RV32-NEXT:    vwmacc.vx v8, s9, v3
; RV32-NEXT:    vwmacc.vx v8, s8, v2
; RV32-NEXT:    vwmacc.vx v8, s7, v0
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 93
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v30, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s6, v30
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 114
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v31, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s5, v31
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 113
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s3, v17
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s1, 102
; RV32-NEXT:    mul a1, a1, s1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v29, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v29
; RV32-NEXT:    vwmacc.vx v8, t6, v28
; RV32-NEXT:    vwmacc.vx v8, t5, v1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t5, 104
; RV32-NEXT:    mul a1, a1, t5
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v1, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t4, v1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t4, 94
; RV32-NEXT:    mul a1, a1, t4
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v28, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t3, v28
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t3, 117
; RV32-NEXT:    mul a1, a1, t3
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t2, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t2, 116
; RV32-NEXT:    mul a1, a1, t2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t1, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t1, 108
; RV32-NEXT:    mul a1, a1, t1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t0, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 111
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a7, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a7, 110
; RV32-NEXT:    mul a1, a1, a7
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a6, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a6, 112
; RV32-NEXT:    mul a1, a1, a6
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a5, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a5, 98
; RV32-NEXT:    mul a1, a1, a5
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a3, v10
; RV32-NEXT:    vwmacc.vx v8, a2, v26
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 76
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 28
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v20, v8, v14
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 76
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 400(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v8, v11, a1
; RV32-NEXT:    lw a1, 392(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    lw a1, 384(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v13
; RV32-NEXT:    lw a1, 372(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v18
; RV32-NEXT:    lw a1, 364(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v19
; RV32-NEXT:    lw a1, 356(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v24
; RV32-NEXT:    lw a1, 264(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v25
; RV32-NEXT:    vmv1r.v v26, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 99
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v16, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 252(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    lw a1, 240(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    lw a1, 236(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v7
; RV32-NEXT:    lw a1, 228(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v5
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 103
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v4, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 224(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v4
; RV32-NEXT:    lw a1, 220(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v6
; RV32-NEXT:    lw a1, 216(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    lw a1, 212(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v2
; RV32-NEXT:    lw a1, 208(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v0
; RV32-NEXT:    vmv1r.v v18, v30
; RV32-NEXT:    lw a1, 204(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v30
; RV32-NEXT:    vmv1r.v v12, v31
; RV32-NEXT:    lw a1, 200(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v31
; RV32-NEXT:    vmv1r.v v24, v17
; RV32-NEXT:    lw a1, 196(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v17
; RV32-NEXT:    lw a1, 192(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v29
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 96
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v30, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 188(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v30
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v31, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v31
; RV32-NEXT:    lw a1, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v1
; RV32-NEXT:    lw a1, 172(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v28
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 117
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v19, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 168(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v19
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 116
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v13, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 164(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v13
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 108
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v14, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 156(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v14
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 111
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 152(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v15
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 110
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v29, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 144(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v29
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 112
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 140(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    vwmacc.vx v8, s2, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 107
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a4, v17
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 72
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 24
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 100
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl2r.v v10, (a1) # vscale x 16-byte Folded Reload
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v20, v8, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 72
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 88
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 412(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v8, v20, a1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 97
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 408(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 115
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 404(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 106
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 396(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 105
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 388(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 109
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 376(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    lw a1, 340(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v25
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 91
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v25, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 336(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v26
; RV32-NEXT:    lw a1, 332(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 87
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v27, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 328(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v7
; RV32-NEXT:    vmv1r.v v26, v7
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 90
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v7, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 324(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v5
; RV32-NEXT:    lw a1, 320(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v4
; RV32-NEXT:    lw a1, 316(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v6
; RV32-NEXT:    vmv1r.v v4, v6
; RV32-NEXT:    lw a1, 312(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 89
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v3, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 308(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v2
; RV32-NEXT:    lw a1, 304(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v0
; RV32-NEXT:    lw a1, 300(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v18
; RV32-NEXT:    lw a1, 296(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    lw a1, 292(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v24
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 102
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v24, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 288(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v24
; RV32-NEXT:    lw a1, 284(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v30
; RV32-NEXT:    lw a1, 280(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v31
; RV32-NEXT:    lw a1, 276(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v1
; RV32-NEXT:    lw a1, 272(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v28
; RV32-NEXT:    lw a1, 268(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v19
; RV32-NEXT:    lw a1, 260(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v13
; RV32-NEXT:    lw a1, 256(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v14
; RV32-NEXT:    lw a1, 248(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v15
; RV32-NEXT:    lw a1, 244(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v29
; RV32-NEXT:    lw a1, 232(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 98
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 184(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    vwmacc.vx v8, s4, v17
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 68
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 20
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v20, v8, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 68
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    lb a1, 4(a0)
; RV32-NEXT:    lb a2, 5(a0)
; RV32-NEXT:    sw a2, 204(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 6(a0)
; RV32-NEXT:    sw a2, 328(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 7(a0)
; RV32-NEXT:    sw a2, 412(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 20(a0)
; RV32-NEXT:    lb a3, 21(a0)
; RV32-NEXT:    sw a3, 196(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 22(a0)
; RV32-NEXT:    sw a3, 324(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 23(a0)
; RV32-NEXT:    sw a3, 408(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 36(a0)
; RV32-NEXT:    lb a4, 37(a0)
; RV32-NEXT:    sw a4, 192(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 38(a0)
; RV32-NEXT:    sw a4, 320(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 39(a0)
; RV32-NEXT:    sw a4, 404(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 52(a0)
; RV32-NEXT:    lb a5, 53(a0)
; RV32-NEXT:    sw a5, 184(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a5, 54(a0)
; RV32-NEXT:    sw a5, 312(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a5, 55(a0)
; RV32-NEXT:    sw a5, 400(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a5, 68(a0)
; RV32-NEXT:    lb a6, 69(a0)
; RV32-NEXT:    sw a6, 180(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 70(a0)
; RV32-NEXT:    sw a6, 308(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 71(a0)
; RV32-NEXT:    sw a6, 396(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 84(a0)
; RV32-NEXT:    lb a7, 85(a0)
; RV32-NEXT:    sw a7, 176(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a7, 86(a0)
; RV32-NEXT:    sw a7, 304(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a7, 87(a0)
; RV32-NEXT:    sw a7, 392(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a7, 100(a0)
; RV32-NEXT:    lb t0, 101(a0)
; RV32-NEXT:    sw t0, 168(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb t0, 102(a0)
; RV32-NEXT:    sw t0, 296(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb t0, 103(a0)
; RV32-NEXT:    sw t0, 388(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr t0, vlenb
; RV32-NEXT:    li t1, 88
; RV32-NEXT:    mul t0, t0, t1
; RV32-NEXT:    add t0, sp, t0
; RV32-NEXT:    addi t0, t0, 432
; RV32-NEXT:    vl1r.v v19, (t0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    vwmul.vx v8, v19, a1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 97
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v13, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a2, v13
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 115
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a3, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 106
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v6, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a4, v6
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 105
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v7, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a5, v7
; RV32-NEXT:    lb a1, 116(a0)
; RV32-NEXT:    lb a2, 117(a0)
; RV32-NEXT:    sw a2, 152(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 118(a0)
; RV32-NEXT:    sw a2, 272(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 119(a0)
; RV32-NEXT:    sw a2, 384(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 109
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a6, v16
; RV32-NEXT:    vwmacc.vx v8, a7, v25
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 99
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    lb a1, 132(a0)
; RV32-NEXT:    lb a2, 133(a0)
; RV32-NEXT:    sw a2, 140(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 134(a0)
; RV32-NEXT:    sw a2, 260(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 135(a0)
; RV32-NEXT:    sw a2, 380(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    lb a1, 148(a0)
; RV32-NEXT:    lb a2, 149(a0)
; RV32-NEXT:    sw a2, 132(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 150(a0)
; RV32-NEXT:    sw a2, 248(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 151(a0)
; RV32-NEXT:    sw a2, 376(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v26
; RV32-NEXT:    lb a1, 164(a0)
; RV32-NEXT:    lb s10, 165(a0)
; RV32-NEXT:    lb a2, 166(a0)
; RV32-NEXT:    sw a2, 244(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 167(a0)
; RV32-NEXT:    sw a2, 372(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v5
; RV32-NEXT:    lb a1, 180(a0)
; RV32-NEXT:    lb s7, 181(a0)
; RV32-NEXT:    lb a2, 182(a0)
; RV32-NEXT:    sw a2, 240(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 183(a0)
; RV32-NEXT:    sw a2, 368(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 103
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    lb a1, 196(a0)
; RV32-NEXT:    lb t5, 197(a0)
; RV32-NEXT:    lb a2, 198(a0)
; RV32-NEXT:    sw a2, 236(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 199(a0)
; RV32-NEXT:    sw a2, 364(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v4
; RV32-NEXT:    lb a1, 212(a0)
; RV32-NEXT:    lb t4, 213(a0)
; RV32-NEXT:    lb a2, 214(a0)
; RV32-NEXT:    sw a2, 232(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 215(a0)
; RV32-NEXT:    sw a2, 360(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    lb a1, 228(a0)
; RV32-NEXT:    lb t3, 229(a0)
; RV32-NEXT:    lb a2, 230(a0)
; RV32-NEXT:    sw a2, 228(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 231(a0)
; RV32-NEXT:    sw a2, 356(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v2
; RV32-NEXT:    lb a1, 244(a0)
; RV32-NEXT:    lb t2, 245(a0)
; RV32-NEXT:    lb a2, 246(a0)
; RV32-NEXT:    sw a2, 224(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 247(a0)
; RV32-NEXT:    sw a2, 352(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v0
; RV32-NEXT:    lb a1, 260(a0)
; RV32-NEXT:    lb t1, 261(a0)
; RV32-NEXT:    lb a2, 262(a0)
; RV32-NEXT:    sw a2, 220(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 263(a0)
; RV32-NEXT:    sw a2, 348(sp) # 4-byte Folded Spill
; RV32-NEXT:    vmv1r.v v3, v18
; RV32-NEXT:    vwmacc.vx v8, a1, v18
; RV32-NEXT:    lb a1, 276(a0)
; RV32-NEXT:    lb t0, 277(a0)
; RV32-NEXT:    lb a2, 278(a0)
; RV32-NEXT:    sw a2, 216(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 279(a0)
; RV32-NEXT:    sw a2, 344(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 114
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v29, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v29
; RV32-NEXT:    lb a1, 292(a0)
; RV32-NEXT:    lb a7, 293(a0)
; RV32-NEXT:    lb a2, 294(a0)
; RV32-NEXT:    sw a2, 212(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 295(a0)
; RV32-NEXT:    sw a2, 340(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 113
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v27, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    lb a1, 308(a0)
; RV32-NEXT:    lb a6, 309(a0)
; RV32-NEXT:    lb a2, 310(a0)
; RV32-NEXT:    sw a2, 208(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 311(a0)
; RV32-NEXT:    sw a2, 336(sp) # 4-byte Folded Spill
; RV32-NEXT:    vmv1r.v v1, v24
; RV32-NEXT:    vwmacc.vx v8, a1, v24
; RV32-NEXT:    lb a1, 324(a0)
; RV32-NEXT:    lb a4, 325(a0)
; RV32-NEXT:    lb a2, 326(a0)
; RV32-NEXT:    sw a2, 200(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 327(a0)
; RV32-NEXT:    sw a2, 332(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v30
; RV32-NEXT:    lb a1, 340(a0)
; RV32-NEXT:    lb a3, 341(a0)
; RV32-NEXT:    lb a2, 342(a0)
; RV32-NEXT:    sw a2, 188(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 343(a0)
; RV32-NEXT:    sw a2, 316(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a1, v31
; RV32-NEXT:    lb a1, 356(a0)
; RV32-NEXT:    lb a2, 357(a0)
; RV32-NEXT:    lb a5, 358(a0)
; RV32-NEXT:    sw a5, 172(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a5, 359(a0)
; RV32-NEXT:    sw a5, 300(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a6, 4(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a5, vlenb
; RV32-NEXT:    li a6, 104
; RV32-NEXT:    mul a5, a5, a6
; RV32-NEXT:    add a5, sp, a5
; RV32-NEXT:    addi a5, a5, 432
; RV32-NEXT:    vl1r.v v25, (a5) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v25
; RV32-NEXT:    lb a5, 372(a0)
; RV32-NEXT:    lb a1, 373(a0)
; RV32-NEXT:    lb t6, 374(a0)
; RV32-NEXT:    sw t6, 164(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb t6, 375(a0)
; RV32-NEXT:    sw t6, 292(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, a5, v28
; RV32-NEXT:    lb t6, 388(a0)
; RV32-NEXT:    lb a5, 389(a0)
; RV32-NEXT:    lb s0, 390(a0)
; RV32-NEXT:    sw s0, 160(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb s0, 391(a0)
; RV32-NEXT:    sw s0, 288(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li s0, 117
; RV32-NEXT:    mul a6, a6, s0
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 432
; RV32-NEXT:    vl1r.v v24, (a6) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t6, v24
; RV32-NEXT:    lb t6, 404(a0)
; RV32-NEXT:    lb ra, 405(a0)
; RV32-NEXT:    lb s0, 406(a0)
; RV32-NEXT:    sw s0, 156(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb s0, 407(a0)
; RV32-NEXT:    sw s0, 284(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li s0, 116
; RV32-NEXT:    mul a6, a6, s0
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 432
; RV32-NEXT:    vl1r.v v26, (a6) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t6, v26
; RV32-NEXT:    lb t6, 420(a0)
; RV32-NEXT:    lb s9, 421(a0)
; RV32-NEXT:    lb s0, 422(a0)
; RV32-NEXT:    sw s0, 148(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb s0, 423(a0)
; RV32-NEXT:    sw s0, 280(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, t6, v14
; RV32-NEXT:    lb t6, 436(a0)
; RV32-NEXT:    lb s8, 437(a0)
; RV32-NEXT:    lb s0, 438(a0)
; RV32-NEXT:    sw s0, 144(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb s0, 439(a0)
; RV32-NEXT:    sw s0, 276(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v8, t6, v15
; RV32-NEXT:    lb t6, 452(a0)
; RV32-NEXT:    lb s5, 453(a0)
; RV32-NEXT:    lb s0, 454(a0)
; RV32-NEXT:    sw s0, 136(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb s0, 455(a0)
; RV32-NEXT:    sw s0, 268(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li s0, 110
; RV32-NEXT:    mul a6, a6, s0
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 432
; RV32-NEXT:    vl1r.v v16, (a6) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t6, v16
; RV32-NEXT:    lb t6, 468(a0)
; RV32-NEXT:    lb s4, 469(a0)
; RV32-NEXT:    lb s11, 470(a0)
; RV32-NEXT:    lb s0, 471(a0)
; RV32-NEXT:    sw s0, 264(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li s0, 112
; RV32-NEXT:    mul a6, a6, s0
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 432
; RV32-NEXT:    vl1r.v v18, (a6) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t6, v18
; RV32-NEXT:    lb t6, 484(a0)
; RV32-NEXT:    lb s3, 485(a0)
; RV32-NEXT:    lb s6, 486(a0)
; RV32-NEXT:    lb s0, 487(a0)
; RV32-NEXT:    sw s0, 256(sp) # 4-byte Folded Spill
; RV32-NEXT:    vmv1r.v v17, v12
; RV32-NEXT:    vwmacc.vx v8, t6, v12
; RV32-NEXT:    lb s0, 500(a0)
; RV32-NEXT:    lb s2, 501(a0)
; RV32-NEXT:    lb t6, 502(a0)
; RV32-NEXT:    lb s1, 503(a0)
; RV32-NEXT:    sw s1, 252(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr s1, vlenb
; RV32-NEXT:    li a6, 107
; RV32-NEXT:    mul s1, s1, a6
; RV32-NEXT:    lw a6, 4(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s1, sp, s1
; RV32-NEXT:    addi s1, s1, 432
; RV32-NEXT:    vl1r.v v12, (s1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v12
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    slli s0, s0, 6
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl4r.v v20, (s0) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    slli s0, s0, 4
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vs4r.v v20, (s0) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v20, v8, v10
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    slli s0, s0, 6
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vs4r.v v20, (s0) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw s0, 204(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v8, v19, s0
; RV32-NEXT:    vmv1r.v v21, v13
; RV32-NEXT:    lw s0, 196(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v13
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li s1, 115
; RV32-NEXT:    mul s0, s0, s1
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl1r.v v13, (s0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw s0, 192(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v13
; RV32-NEXT:    lw s0, 184(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v6
; RV32-NEXT:    lw s0, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v7
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li s1, 109
; RV32-NEXT:    mul s0, s0, s1
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl1r.v v20, (s0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw s0, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v20
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li s1, 91
; RV32-NEXT:    mul s0, s0, s1
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl1r.v v7, (s0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw s0, 168(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v7
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li s1, 99
; RV32-NEXT:    mul s0, s0, s1
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl1r.v v22, (s0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw s0, 152(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v22
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li s1, 87
; RV32-NEXT:    mul s0, s0, s1
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl1r.v v22, (s0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw s0, 140(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v22
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li s1, 90
; RV32-NEXT:    mul s0, s0, s1
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl1r.v v6, (s0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw s0, 132(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s0, v6
; RV32-NEXT:    vwmacc.vx v8, s10, v5
; RV32-NEXT:    csrr s0, vlenb
; RV32-NEXT:    li s1, 103
; RV32-NEXT:    mul s0, s0, s1
; RV32-NEXT:    add s0, sp, s0
; RV32-NEXT:    addi s0, s0, 432
; RV32-NEXT:    vl1r.v v23, (s0) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, s7, v23
; RV32-NEXT:    vwmacc.vx v8, t5, v4
; RV32-NEXT:    csrr t5, vlenb
; RV32-NEXT:    li s0, 89
; RV32-NEXT:    mul t5, t5, s0
; RV32-NEXT:    add t5, sp, t5
; RV32-NEXT:    addi t5, t5, 432
; RV32-NEXT:    vl1r.v v23, (t5) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, t4, v23
; RV32-NEXT:    vwmacc.vx v8, t3, v2
; RV32-NEXT:    vwmacc.vx v8, t2, v0
; RV32-NEXT:    vwmacc.vx v8, t1, v3
; RV32-NEXT:    vwmacc.vx v8, t0, v29
; RV32-NEXT:    vwmacc.vx v8, a7, v27
; RV32-NEXT:    vwmacc.vx v8, a6, v1
; RV32-NEXT:    vwmacc.vx v8, a4, v30
; RV32-NEXT:    vwmacc.vx v8, a3, v31
; RV32-NEXT:    vwmacc.vx v8, a2, v25
; RV32-NEXT:    vwmacc.vx v8, a1, v28
; RV32-NEXT:    vwmacc.vx v8, a5, v24
; RV32-NEXT:    vwmacc.vx v8, ra, v26
; RV32-NEXT:    vwmacc.vx v8, s9, v14
; RV32-NEXT:    vmv1r.v v31, v14
; RV32-NEXT:    vwmacc.vx v8, s8, v15
; RV32-NEXT:    vwmacc.vx v8, s5, v16
; RV32-NEXT:    vwmacc.vx v8, s4, v18
; RV32-NEXT:    vmv1r.v v30, v18
; RV32-NEXT:    vwmacc.vx v8, s3, v17
; RV32-NEXT:    vmv1r.v v28, v17
; RV32-NEXT:    vwmacc.vx v8, s2, v12
; RV32-NEXT:    vmv1r.v v29, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 60
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v24, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 12
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v24, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v24, v8, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 60
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v24, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vmv1r.v v11, v19
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 328(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v8, v19, a1
; RV32-NEXT:    lw a1, 324(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v21
; RV32-NEXT:    lw a1, 320(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v13
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 106
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v18, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 312(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v18
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 105
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v19, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 308(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v19
; RV32-NEXT:    vmv1r.v v10, v20
; RV32-NEXT:    lw a1, 304(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    vmv1r.v v20, v7
; RV32-NEXT:    lw a1, 296(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v7
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 99
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v21, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 272(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v21
; RV32-NEXT:    lw a1, 260(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v22
; RV32-NEXT:    vmv1r.v v7, v6
; RV32-NEXT:    lw a1, 248(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v6
; RV32-NEXT:    vmv1r.v v6, v5
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 84
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v5, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 244(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v5
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 103
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v5, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 240(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v5
; RV32-NEXT:    lw a1, 236(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v4
; RV32-NEXT:    lw a1, 232(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v23
; RV32-NEXT:    vmv1r.v v24, v2
; RV32-NEXT:    lw a1, 228(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v2
; RV32-NEXT:    vmv1r.v v25, v0
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 85
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v0, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 224(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v0
; RV32-NEXT:    vmv1r.v v26, v3
; RV32-NEXT:    lw a1, 220(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 114
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v27, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 216(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 113
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v3, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 212(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    vmv1r.v v14, v1
; RV32-NEXT:    lw a1, 208(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 96
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v2, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 200(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v2
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v1, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 188(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 104
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v0, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 172(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v0
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 94
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 164(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v15
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 117
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 160(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 116
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 156(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v17
; RV32-NEXT:    lw a1, 148(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v31
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 111
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 144(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 110
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 136(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v17
; RV32-NEXT:    vwmacc.vx v8, s11, v30
; RV32-NEXT:    vwmacc.vx v8, s6, v28
; RV32-NEXT:    vwmacc.vx v8, t6, v29
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 56
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v28, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v28, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 100
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl2r.v v12, (a1) # vscale x 16-byte Folded Reload
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v28, v8, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 56
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v28, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 412(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v8, v11, a1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 97
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v28, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 408(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v28
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 115
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v29, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 404(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v29
; RV32-NEXT:    lw a1, 400(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v18
; RV32-NEXT:    lw a1, 396(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v19
; RV32-NEXT:    lw a1, 392(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v10
; RV32-NEXT:    lw a1, 388(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v20
; RV32-NEXT:    vmv1r.v v30, v20
; RV32-NEXT:    lw a1, 384(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v21
; RV32-NEXT:    lw a1, 380(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v22
; RV32-NEXT:    lw a1, 376(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v7
; RV32-NEXT:    vmv1r.v v31, v7
; RV32-NEXT:    lw a1, 372(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v6
; RV32-NEXT:    lw a1, 368(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v5
; RV32-NEXT:    lw a1, 364(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v4
; RV32-NEXT:    vmv1r.v v20, v4
; RV32-NEXT:    lw a1, 360(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v23
; RV32-NEXT:    lw a1, 356(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v24
; RV32-NEXT:    vmv1r.v v23, v24
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 86
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs1r.v v24, (a1) # vscale x 8-byte Folded Spill
; RV32-NEXT:    lw a1, 352(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v25
; RV32-NEXT:    lw a1, 348(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v26
; RV32-NEXT:    vmv1r.v v25, v26
; RV32-NEXT:    lw a1, 344(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v27
; RV32-NEXT:    lw a1, 340(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    lw a1, 336(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v14
; RV32-NEXT:    lw a1, 332(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v2
; RV32-NEXT:    vmv1r.v v14, v2
; RV32-NEXT:    lw a1, 316(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v1
; RV32-NEXT:    lw a1, 300(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v0
; RV32-NEXT:    lw a1, 292(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v15
; RV32-NEXT:    vmv1r.v v2, v15
; RV32-NEXT:    lw a1, 288(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 116
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 284(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 108
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v3, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 280(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v3
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 111
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 276(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    lw a1, 268(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v17
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 112
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 264(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 98
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 256(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v17
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 107
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 252(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v8, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 52
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v4, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 100
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl2r.v v12, (a1) # vscale x 16-byte Folded Reload
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v4, v8, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 52
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    lb a1, 8(a0)
; RV32-NEXT:    lb a2, 9(a0)
; RV32-NEXT:    sw a2, 200(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 10(a0)
; RV32-NEXT:    sw a2, 344(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 11(a0)
; RV32-NEXT:    sw a2, 412(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 24(a0)
; RV32-NEXT:    lb a3, 25(a0)
; RV32-NEXT:    sw a3, 196(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 26(a0)
; RV32-NEXT:    sw a3, 340(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 27(a0)
; RV32-NEXT:    sw a3, 408(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a3, 40(a0)
; RV32-NEXT:    lb a4, 41(a0)
; RV32-NEXT:    sw a4, 188(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 42(a0)
; RV32-NEXT:    sw a4, 332(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 43(a0)
; RV32-NEXT:    sw a4, 404(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a4, 56(a0)
; RV32-NEXT:    lb a5, 57(a0)
; RV32-NEXT:    sw a5, 184(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a5, 58(a0)
; RV32-NEXT:    sw a5, 328(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a5, 59(a0)
; RV32-NEXT:    sw a5, 400(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a5, 72(a0)
; RV32-NEXT:    lb a6, 73(a0)
; RV32-NEXT:    sw a6, 180(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 74(a0)
; RV32-NEXT:    sw a6, 320(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 75(a0)
; RV32-NEXT:    sw a6, 396(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a6, 88(a0)
; RV32-NEXT:    lb a7, 89(a0)
; RV32-NEXT:    sw a7, 176(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a7, 90(a0)
; RV32-NEXT:    sw a7, 316(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a7, 91(a0)
; RV32-NEXT:    sw a7, 392(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a7, 104(a0)
; RV32-NEXT:    lb t0, 105(a0)
; RV32-NEXT:    sw t0, 172(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb t0, 106(a0)
; RV32-NEXT:    sw t0, 312(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb t0, 107(a0)
; RV32-NEXT:    sw t0, 388(sp) # 4-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    vwmul.vx v12, v11, a1
; RV32-NEXT:    vwmacc.vx v12, a2, v28
; RV32-NEXT:    vmv1r.v v8, v28
; RV32-NEXT:    vwmacc.vx v12, a3, v29
; RV32-NEXT:    vwmacc.vx v12, a4, v18
; RV32-NEXT:    vwmacc.vx v12, a5, v19
; RV32-NEXT:    lb a1, 120(a0)
; RV32-NEXT:    lb a2, 121(a0)
; RV32-NEXT:    sw a2, 156(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 122(a0)
; RV32-NEXT:    sw a2, 296(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 123(a0)
; RV32-NEXT:    sw a2, 384(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a6, v10
; RV32-NEXT:    vwmacc.vx v12, a7, v30
; RV32-NEXT:    vwmacc.vx v12, a1, v21
; RV32-NEXT:    lb a1, 136(a0)
; RV32-NEXT:    lb a2, 137(a0)
; RV32-NEXT:    sw a2, 148(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 138(a0)
; RV32-NEXT:    sw a2, 288(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 139(a0)
; RV32-NEXT:    sw a2, 380(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v22
; RV32-NEXT:    lb a1, 152(a0)
; RV32-NEXT:    lb a2, 153(a0)
; RV32-NEXT:    sw a2, 140(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 154(a0)
; RV32-NEXT:    sw a2, 280(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 155(a0)
; RV32-NEXT:    sw a2, 376(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v31
; RV32-NEXT:    lb a1, 168(a0)
; RV32-NEXT:    lb a2, 169(a0)
; RV32-NEXT:    sw a2, 132(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 170(a0)
; RV32-NEXT:    sw a2, 272(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 171(a0)
; RV32-NEXT:    sw a2, 372(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 84
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v27, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v27
; RV32-NEXT:    lb a1, 184(a0)
; RV32-NEXT:    lb s9, 185(a0)
; RV32-NEXT:    lb a2, 186(a0)
; RV32-NEXT:    sw a2, 264(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 187(a0)
; RV32-NEXT:    sw a2, 368(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 103
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v15, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v15
; RV32-NEXT:    lb a1, 200(a0)
; RV32-NEXT:    lb s8, 201(a0)
; RV32-NEXT:    lb a2, 202(a0)
; RV32-NEXT:    sw a2, 256(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 203(a0)
; RV32-NEXT:    sw a2, 364(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v20
; RV32-NEXT:    lb a1, 216(a0)
; RV32-NEXT:    lb s3, 217(a0)
; RV32-NEXT:    lb a2, 218(a0)
; RV32-NEXT:    sw a2, 252(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 219(a0)
; RV32-NEXT:    sw a2, 360(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 89
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v24, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v24
; RV32-NEXT:    lb a1, 232(a0)
; RV32-NEXT:    lb s0, 233(a0)
; RV32-NEXT:    lb a2, 234(a0)
; RV32-NEXT:    sw a2, 244(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 235(a0)
; RV32-NEXT:    sw a2, 356(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v23
; RV32-NEXT:    lb a1, 248(a0)
; RV32-NEXT:    lb t6, 249(a0)
; RV32-NEXT:    lb a2, 250(a0)
; RV32-NEXT:    sw a2, 236(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 251(a0)
; RV32-NEXT:    sw a2, 352(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 85
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v26, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v26
; RV32-NEXT:    lb a1, 264(a0)
; RV32-NEXT:    lb t5, 265(a0)
; RV32-NEXT:    lb a2, 266(a0)
; RV32-NEXT:    sw a2, 228(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 267(a0)
; RV32-NEXT:    sw a2, 348(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v25
; RV32-NEXT:    lb a1, 280(a0)
; RV32-NEXT:    lb t4, 281(a0)
; RV32-NEXT:    lb a2, 282(a0)
; RV32-NEXT:    sw a2, 220(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 283(a0)
; RV32-NEXT:    sw a2, 336(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 114
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v9, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v9
; RV32-NEXT:    lb a1, 296(a0)
; RV32-NEXT:    lb t3, 297(a0)
; RV32-NEXT:    lb a2, 298(a0)
; RV32-NEXT:    sw a2, 216(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 299(a0)
; RV32-NEXT:    sw a2, 324(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 113
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v9, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v9
; RV32-NEXT:    lb a1, 312(a0)
; RV32-NEXT:    lb t2, 313(a0)
; RV32-NEXT:    lb a2, 314(a0)
; RV32-NEXT:    sw a2, 208(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 315(a0)
; RV32-NEXT:    sw a2, 308(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 102
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v16
; RV32-NEXT:    lb a1, 328(a0)
; RV32-NEXT:    lb t1, 329(a0)
; RV32-NEXT:    lb a2, 330(a0)
; RV32-NEXT:    sw a2, 204(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 331(a0)
; RV32-NEXT:    sw a2, 304(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v14
; RV32-NEXT:    lb a1, 344(a0)
; RV32-NEXT:    lb t0, 345(a0)
; RV32-NEXT:    lb a2, 346(a0)
; RV32-NEXT:    sw a2, 192(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 347(a0)
; RV32-NEXT:    sw a2, 300(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v1
; RV32-NEXT:    lb a1, 360(a0)
; RV32-NEXT:    lb a7, 361(a0)
; RV32-NEXT:    lb a2, 362(a0)
; RV32-NEXT:    sw a2, 168(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 363(a0)
; RV32-NEXT:    sw a2, 292(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v0
; RV32-NEXT:    lb a1, 376(a0)
; RV32-NEXT:    lb a6, 377(a0)
; RV32-NEXT:    lb a2, 378(a0)
; RV32-NEXT:    sw a2, 164(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 379(a0)
; RV32-NEXT:    sw a2, 284(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v2
; RV32-NEXT:    lb a1, 392(a0)
; RV32-NEXT:    lb a5, 393(a0)
; RV32-NEXT:    lb a2, 394(a0)
; RV32-NEXT:    sw a2, 160(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 395(a0)
; RV32-NEXT:    sw a2, 276(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw t0, 4(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 117
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v18, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v18
; RV32-NEXT:    lb a1, 408(a0)
; RV32-NEXT:    lb a4, 409(a0)
; RV32-NEXT:    lb a2, 410(a0)
; RV32-NEXT:    sw a2, 152(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 411(a0)
; RV32-NEXT:    sw a2, 268(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    li a3, 116
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    add a2, sp, a2
; RV32-NEXT:    addi a2, a2, 432
; RV32-NEXT:    vl1r.v v14, (a2) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v14
; RV32-NEXT:    lb a1, 424(a0)
; RV32-NEXT:    lb a3, 425(a0)
; RV32-NEXT:    lb a2, 426(a0)
; RV32-NEXT:    sw a2, 144(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a2, 427(a0)
; RV32-NEXT:    sw a2, 260(sp) # 4-byte Folded Spill
; RV32-NEXT:    vwmacc.vx v12, a1, v3
; RV32-NEXT:    lb s2, 440(a0)
; RV32-NEXT:    lb a2, 441(a0)
; RV32-NEXT:    lb a1, 442(a0)
; RV32-NEXT:    sw a1, 136(sp) # 4-byte Folded Spill
; RV32-NEXT:    lb a1, 443(a0)
; RV32-NEXT:    sw a1, 248(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 111
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v9, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, s2, v9
; RV32-NEXT:    lb s2, 456(a0)
; RV32-NEXT:    lb s11, 457(a0)
; RV32-NEXT:    lb ra, 458(a0)
; RV32-NEXT:    lb a1, 459(a0)
; RV32-NEXT:    sw a1, 240(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 110
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v19, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, s2, v19
; RV32-NEXT:    lb s2, 472(a0)
; RV32-NEXT:    lb s10, 473(a0)
; RV32-NEXT:    lb s5, 474(a0)
; RV32-NEXT:    lb a1, 475(a0)
; RV32-NEXT:    sw a1, 232(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 112
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v3, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, s2, v3
; RV32-NEXT:    lb s2, 488(a0)
; RV32-NEXT:    lb s7, 489(a0)
; RV32-NEXT:    lb s4, 490(a0)
; RV32-NEXT:    lb a1, 491(a0)
; RV32-NEXT:    sw a1, 224(sp) # 4-byte Folded Spill
; RV32-NEXT:    vmv1r.v v23, v17
; RV32-NEXT:    vwmacc.vx v12, s2, v17
; RV32-NEXT:    lb s1, 504(a0)
; RV32-NEXT:    lb s6, 505(a0)
; RV32-NEXT:    lb s2, 506(a0)
; RV32-NEXT:    lb a1, 507(a0)
; RV32-NEXT:    sw a1, 212(sp) # 4-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 107
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v25, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, s1, v25
; RV32-NEXT:    lw s1, 128(sp) # 4-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 48
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v4, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    addi a1, sp, 432
; RV32-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 100
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl2r.v v28, (a1) # vscale x 16-byte Folded Reload
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v4, v12, v28
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 48
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vmv1r.v v30, v11
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 200(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v12, v11, a1
; RV32-NEXT:    vmv1r.v v31, v8
; RV32-NEXT:    lw a1, 196(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v8
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 115
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v9, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 188(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v9
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 106
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 184(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 105
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v8
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 109
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v11, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v11
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 91
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 172(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v17
; RV32-NEXT:    vmv1r.v v20, v21
; RV32-NEXT:    lw a1, 156(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v21
; RV32-NEXT:    vmv1r.v v21, v22
; RV32-NEXT:    lw a1, 148(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v22
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t0, 90
; RV32-NEXT:    mul a1, a1, t0
; RV32-NEXT:    lw t0, 4(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v22, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 140(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v22
; RV32-NEXT:    lw a1, 132(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v27
; RV32-NEXT:    vwmacc.vx v12, s9, v15
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s9, 92
; RV32-NEXT:    mul a1, a1, s9
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, s8, v15
; RV32-NEXT:    vwmacc.vx v12, s3, v24
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li s3, 86
; RV32-NEXT:    mul a1, a1, s3
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v24, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, s0, v24
; RV32-NEXT:    vwmacc.vx v12, t6, v26
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t6, 93
; RV32-NEXT:    mul a1, a1, t6
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v26, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, t5, v26
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t5, 114
; RV32-NEXT:    mul a1, a1, t5
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v27, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, t4, v27
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t4, 113
; RV32-NEXT:    mul a1, a1, t4
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v7, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, t3, v7
; RV32-NEXT:    vwmacc.vx v12, t2, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li t2, 96
; RV32-NEXT:    mul a1, a1, t2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, t1, v16
; RV32-NEXT:    vwmacc.vx v12, t0, v1
; RV32-NEXT:    vwmacc.vx v12, a7, v0
; RV32-NEXT:    vwmacc.vx v12, a6, v2
; RV32-NEXT:    vwmacc.vx v12, a5, v18
; RV32-NEXT:    vwmacc.vx v12, a4, v14
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a4, 108
; RV32-NEXT:    mul a1, a1, a4
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v14, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a3, v14
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a3, 111
; RV32-NEXT:    mul a1, a1, a3
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v18, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a2, v18
; RV32-NEXT:    vwmacc.vx v12, s11, v19
; RV32-NEXT:    vmv1r.v v19, v3
; RV32-NEXT:    vwmacc.vx v12, s10, v3
; RV32-NEXT:    vwmacc.vx v12, s7, v23
; RV32-NEXT:    vwmacc.vx v12, s6, v25
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 44
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v0, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vmv4r.v v4, v0
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v0, v12, v28
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 44
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v0, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 344(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v12, v30, a1
; RV32-NEXT:    lw a1, 340(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v31
; RV32-NEXT:    lw a1, 332(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v9
; RV32-NEXT:    lw a1, 328(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v10
; RV32-NEXT:    lw a1, 320(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v8
; RV32-NEXT:    lw a1, 316(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v11
; RV32-NEXT:    lw a1, 312(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v17
; RV32-NEXT:    lw a1, 296(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v20
; RV32-NEXT:    lw a1, 288(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v21
; RV32-NEXT:    lw a1, 280(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v22
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 84
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 272(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 103
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v31, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 264(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v31
; RV32-NEXT:    lw a1, 256(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v15
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 89
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v11, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 252(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v11
; RV32-NEXT:    lw a1, 244(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v24
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 85
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 236(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v15
; RV32-NEXT:    lw a1, 228(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v26
; RV32-NEXT:    lw a1, 220(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v27
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 113
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 216(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v17
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 102
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v30, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 208(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v30
; RV32-NEXT:    lw a1, 204(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 192(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v8
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 104
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 168(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v8
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 94
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 164(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v8
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 117
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 160(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v8
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 116
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 152(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v16
; RV32-NEXT:    lw a1, 144(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v14
; RV32-NEXT:    lw a1, 136(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, a1, v18
; RV32-NEXT:    vmv1r.v v14, v18
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 110
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, ra, v8
; RV32-NEXT:    vwmacc.vx v12, s5, v19
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 98
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v9, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v12, s4, v9
; RV32-NEXT:    vwmacc.vx v12, s2, v25
; RV32-NEXT:    lw s2, 420(sp) # 4-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 40
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v0, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vmv4r.v v20, v0
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v0, v12, v28
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 40
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v0, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 36
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v24, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 88
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV32-NEXT:    lw a1, 412(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmul.vx v18, v12, a1
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 97
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 408(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 115
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 404(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 106
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 400(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 105
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 396(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 109
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 392(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 91
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 388(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 99
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 384(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 87
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 380(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 90
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 376(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v12
; RV32-NEXT:    lw a1, 372(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    lw a1, 368(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v31
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 92
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 364(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    lw a1, 360(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v11
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 86
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 356(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    lw a1, 352(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v15
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 93
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 348(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 114
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 336(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    lw a1, 324(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v17
; RV32-NEXT:    lw a1, 308(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v30
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 96
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 304(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 300(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 104
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 292(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 94
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 284(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 117
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 276(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    lw a1, 268(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 108
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 260(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v10
; RV32-NEXT:    lw a1, 248(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v14
; RV32-NEXT:    lw a1, 240(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v8
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 112
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 232(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v8
; RV32-NEXT:    lw a1, 224(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v9
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 107
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV32-NEXT:    lw a1, 212(sp) # 4-byte Folded Reload
; RV32-NEXT:    vwmacc.vx v18, a1, v8
; RV32-NEXT:    vmv4r.v v12, v24
; RV32-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV32-NEXT:    vwmacc.vv v24, v18, v28
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 36
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vs4r.v v24, (a1) # vscale x 32-byte Folded Spill
; RV32-NEXT:    addi a0, a0, 512
; RV32-NEXT:    lw a1, 416(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s2, s2, a1
; RV32-NEXT:    lw a1, 424(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s1, s1, a1
; RV32-NEXT:    lw a1, 104(sp) # 4-byte Folded Reload
; RV32-NEXT:    beq a0, a1, .LBB1_2
; RV32-NEXT:    j .LBB1_1
; RV32-NEXT:  .LBB1_2: # %loop_end
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 5
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 432
; RV32-NEXT:    vl4r.v v16, (a0) # vscale x 32-byte Folded Reload
; RV32-NEXT:    lw a7, 8(sp) # 4-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a7)
; RV32-NEXT:    lw a0, 116(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a0, a7, a0
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 28
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a0)
; RV32-NEXT:    lw a0, 120(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a0, a7, a0
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 24
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a0)
; RV32-NEXT:    lw a0, 108(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a0, a7, a0
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 20
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a0)
; RV32-NEXT:    lw a0, 124(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a0, a7, a0
; RV32-NEXT:    li a1, 20
; RV32-NEXT:    lw a2, 112(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a2, a7, a2
; RV32-NEXT:    lw a3, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a3, a7, a3
; RV32-NEXT:    lw a4, 416(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a4, a7, a4
; RV32-NEXT:    li a5, 36
; RV32-NEXT:    li a6, 40
; RV32-NEXT:    csrr t0, vlenb
; RV32-NEXT:    slli t0, t0, 4
; RV32-NEXT:    add t0, sp, t0
; RV32-NEXT:    addi t0, t0, 432
; RV32-NEXT:    vl4r.v v16, (t0) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a0)
; RV32-NEXT:    li a0, 44
; RV32-NEXT:    lw t0, 424(sp) # 4-byte Folded Reload
; RV32-NEXT:    mul a1, t0, a1
; RV32-NEXT:    mul a5, t0, a5
; RV32-NEXT:    mul a6, t0, a6
; RV32-NEXT:    mul a0, t0, a0
; RV32-NEXT:    add a1, a7, a1
; RV32-NEXT:    add a5, a7, a5
; RV32-NEXT:    add a6, a7, a6
; RV32-NEXT:    add a0, a7, a0
; RV32-NEXT:    csrr a7, vlenb
; RV32-NEXT:    li t0, 12
; RV32-NEXT:    mul a7, a7, t0
; RV32-NEXT:    add a7, sp, a7
; RV32-NEXT:    addi a7, a7, 432
; RV32-NEXT:    vl4r.v v16, (a7) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a1)
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a2)
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 432
; RV32-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v16, (a3)
; RV32-NEXT:    addi a1, sp, 432
; RV32-NEXT:    vl4r.v v8, (a1) # vscale x 32-byte Folded Reload
; RV32-NEXT:    vs4r.v v8, (a4)
; RV32-NEXT:    vs4r.v v4, (a5)
; RV32-NEXT:    vs4r.v v20, (a6)
; RV32-NEXT:    vs4r.v v12, (a0)
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 118
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add sp, sp, a0
; RV32-NEXT:    .cfi_def_cfa sp, 496
; RV32-NEXT:    lw ra, 492(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 488(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 484(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s2, 480(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s3, 476(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s4, 472(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s5, 468(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s6, 464(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s7, 460(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s8, 456(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s9, 452(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s10, 448(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s11, 444(sp) # 4-byte Folded Reload
; RV32-NEXT:    .cfi_restore ra
; RV32-NEXT:    .cfi_restore s0
; RV32-NEXT:    .cfi_restore s1
; RV32-NEXT:    .cfi_restore s2
; RV32-NEXT:    .cfi_restore s3
; RV32-NEXT:    .cfi_restore s4
; RV32-NEXT:    .cfi_restore s5
; RV32-NEXT:    .cfi_restore s6
; RV32-NEXT:    .cfi_restore s7
; RV32-NEXT:    .cfi_restore s8
; RV32-NEXT:    .cfi_restore s9
; RV32-NEXT:    .cfi_restore s10
; RV32-NEXT:    .cfi_restore s11
; RV32-NEXT:    addi sp, sp, 496
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: q4k_q8k_gemm_kernel:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    addi sp, sp, -976
; RV64-NEXT:    .cfi_def_cfa_offset 976
; RV64-NEXT:    sd ra, 968(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 960(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s1, 952(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s2, 944(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s3, 936(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s4, 928(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s5, 920(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s6, 912(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s7, 904(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s8, 896(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s9, 888(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s10, 880(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s11, 872(sp) # 8-byte Folded Spill
; RV64-NEXT:    .cfi_offset ra, -8
; RV64-NEXT:    .cfi_offset s0, -16
; RV64-NEXT:    .cfi_offset s1, -24
; RV64-NEXT:    .cfi_offset s2, -32
; RV64-NEXT:    .cfi_offset s3, -40
; RV64-NEXT:    .cfi_offset s4, -48
; RV64-NEXT:    .cfi_offset s5, -56
; RV64-NEXT:    .cfi_offset s6, -64
; RV64-NEXT:    .cfi_offset s7, -72
; RV64-NEXT:    .cfi_offset s8, -80
; RV64-NEXT:    .cfi_offset s9, -88
; RV64-NEXT:    .cfi_offset s10, -96
; RV64-NEXT:    .cfi_offset s11, -104
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 118
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    sub sp, sp, a4
; RV64-NEXT:    .cfi_escape 0x0f, 0x0f, 0x72, 0x00, 0x11, 0xd0, 0x07, 0x22, 0x11, 0xf6, 0x00, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 976 + 118 * vlenb
; RV64-NEXT:    sd a3, 16(sp) # 8-byte Folded Spill
; RV64-NEXT:    mv s1, a2
; RV64-NEXT:    mv s2, a1
; RV64-NEXT:    lui a1, 1
; RV64-NEXT:    vsetvli a2, zero, e32, m4, ta, ma
; RV64-NEXT:    vmv.v.i v8, 0
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li a2, 10
; RV64-NEXT:    li a3, 11
; RV64-NEXT:    li a4, 13
; RV64-NEXT:    li a5, 18
; RV64-NEXT:    li a6, 19
; RV64-NEXT:    li a7, 20
; RV64-NEXT:    li t0, 21
; RV64-NEXT:    li t1, 22
; RV64-NEXT:    li t2, 23
; RV64-NEXT:    li t3, 25
; RV64-NEXT:    li t4, 26
; RV64-NEXT:    li t5, 27
; RV64-NEXT:    li t6, 29
; RV64-NEXT:    add a1, a0, a1
; RV64-NEXT:    sd a1, 208(sp) # 8-byte Folded Spill
; RV64-NEXT:    slli s5, s0, 1
; RV64-NEXT:    slli s4, s0, 2
; RV64-NEXT:    slli s3, s0, 3
; RV64-NEXT:    mul a1, s0, a2
; RV64-NEXT:    sd a1, 192(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a1, s0, a3
; RV64-NEXT:    sd a1, 184(sp) # 8-byte Folded Spill
; RV64-NEXT:    slli a2, s0, 4
; RV64-NEXT:    mul a1, s0, a4
; RV64-NEXT:    sd a1, 176(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a1, s0, a5
; RV64-NEXT:    sd a1, 168(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a1, s0, a6
; RV64-NEXT:    sd a1, 160(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a1, s0, a7
; RV64-NEXT:    sd a1, 152(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a1, s0, t0
; RV64-NEXT:    sd a1, 144(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a1, s0, t1
; RV64-NEXT:    sd a1, 136(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a1, s0, t2
; RV64-NEXT:    sd a1, 128(sp) # 8-byte Folded Spill
; RV64-NEXT:    slli a1, s0, 5
; RV64-NEXT:    mul a3, s0, t3
; RV64-NEXT:    sd a3, 120(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a3, s0, t4
; RV64-NEXT:    sd a3, 112(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a3, s0, t5
; RV64-NEXT:    sd a3, 104(sp) # 8-byte Folded Spill
; RV64-NEXT:    mul a3, s0, t6
; RV64-NEXT:    sd a3, 96(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    li a4, 76
; RV64-NEXT:    mul a3, a3, a4
; RV64-NEXT:    add a3, sp, a3
; RV64-NEXT:    addi a3, a3, 864
; RV64-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    li a4, 72
; RV64-NEXT:    mul a3, a3, a4
; RV64-NEXT:    add a3, sp, a3
; RV64-NEXT:    addi a3, a3, 864
; RV64-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    li a4, 68
; RV64-NEXT:    mul a3, a3, a4
; RV64-NEXT:    add a3, sp, a3
; RV64-NEXT:    addi a3, a3, 864
; RV64-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    slli a3, a3, 6
; RV64-NEXT:    add a3, sp, a3
; RV64-NEXT:    addi a3, a3, 864
; RV64-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    li a4, 60
; RV64-NEXT:    mul a3, a3, a4
; RV64-NEXT:    add a3, sp, a3
; RV64-NEXT:    addi a3, a3, 864
; RV64-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    li a4, 56
; RV64-NEXT:    mul a3, a3, a4
; RV64-NEXT:    add a3, sp, a3
; RV64-NEXT:    addi a3, a3, 864
; RV64-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    li a4, 52
; RV64-NEXT:    mul a3, a3, a4
; RV64-NEXT:    add a3, sp, a3
; RV64-NEXT:    addi a3, a3, 864
; RV64-NEXT:    vs4r.v v8, (a3) # vscale x 32-byte Folded Spill
; RV64-NEXT:    add a3, s5, s0
; RV64-NEXT:    sd a3, 88(sp) # 8-byte Folded Spill
; RV64-NEXT:    add a3, s4, s0
; RV64-NEXT:    sd a3, 80(sp) # 8-byte Folded Spill
; RV64-NEXT:    sub a3, s3, s5
; RV64-NEXT:    sd a3, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sub a3, s3, s0
; RV64-NEXT:    sd a3, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    add a3, s3, s0
; RV64-NEXT:    sd a3, 56(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s4, 232(sp) # 8-byte Folded Spill
; RV64-NEXT:    sub a3, a2, s4
; RV64-NEXT:    sd a3, 216(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s5, 200(sp) # 8-byte Folded Spill
; RV64-NEXT:    sub a3, a2, s5
; RV64-NEXT:    sd a3, 48(sp) # 8-byte Folded Spill
; RV64-NEXT:    sub a3, a2, s0
; RV64-NEXT:    sd a3, 40(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 848(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd a2, 248(sp) # 8-byte Folded Spill
; RV64-NEXT:    add a2, a2, s0
; RV64-NEXT:    sd a2, 32(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd a1, 832(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s3, 240(sp) # 8-byte Folded Spill
; RV64-NEXT:    sub a1, a1, s3
; RV64-NEXT:    sd a1, 224(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 48
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 44
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 40
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 80
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 36
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v8, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:  .LBB1_1: # %loop
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    sd s2, 840(sp) # 8-byte Folded Spill
; RV64-NEXT:    vl1r.v v6, (s2)
; RV64-NEXT:    lb a6, 0(a0)
; RV64-NEXT:    lb a1, 1(a0)
; RV64-NEXT:    sd a1, 760(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a1, 2(a0)
; RV64-NEXT:    sd a1, 800(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a1, 3(a0)
; RV64-NEXT:    sd a1, 824(sp) # 8-byte Folded Spill
; RV64-NEXT:    ld a1, 848(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a1, s2, a1
; RV64-NEXT:    lb a2, 16(a0)
; RV64-NEXT:    lb a3, 17(a0)
; RV64-NEXT:    sd a3, 736(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 18(a0)
; RV64-NEXT:    sd a3, 784(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 19(a0)
; RV64-NEXT:    sd a3, 816(sp) # 8-byte Folded Spill
; RV64-NEXT:    ld s4, 200(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t0, s2, s4
; RV64-NEXT:    lb s0, 32(a0)
; RV64-NEXT:    lb a3, 33(a0)
; RV64-NEXT:    sd a3, 720(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 34(a0)
; RV64-NEXT:    sd a3, 768(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 35(a0)
; RV64-NEXT:    sd a3, 808(sp) # 8-byte Folded Spill
; RV64-NEXT:    ld t3, 88(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t3, s2, t3
; RV64-NEXT:    lb a7, 48(a0)
; RV64-NEXT:    lb a3, 49(a0)
; RV64-NEXT:    sd a3, 704(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 50(a0)
; RV64-NEXT:    sd a3, 744(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 51(a0)
; RV64-NEXT:    sd a3, 792(sp) # 8-byte Folded Spill
; RV64-NEXT:    ld t6, 232(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t2, s2, t6
; RV64-NEXT:    lb a3, 64(a0)
; RV64-NEXT:    lb a4, 65(a0)
; RV64-NEXT:    sd a4, 696(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 66(a0)
; RV64-NEXT:    sd a4, 728(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 67(a0)
; RV64-NEXT:    sd a4, 776(sp) # 8-byte Folded Spill
; RV64-NEXT:    ld t1, 80(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t1, s2, t1
; RV64-NEXT:    vl1r.v v12, (a1)
; RV64-NEXT:    lb a1, 80(a0)
; RV64-NEXT:    lb a4, 81(a0)
; RV64-NEXT:    sd a4, 688(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 82(a0)
; RV64-NEXT:    sd a4, 712(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 83(a0)
; RV64-NEXT:    sd a4, 752(sp) # 8-byte Folded Spill
; RV64-NEXT:    vl1r.v v13, (t0)
; RV64-NEXT:    ld t0, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t0, s2, t0
; RV64-NEXT:    vl1r.v v18, (t3)
; RV64-NEXT:    ld t3, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t3, s2, t3
; RV64-NEXT:    vl1r.v v19, (t2)
; RV64-NEXT:    ld t2, 240(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t2, s2, t2
; RV64-NEXT:    vl1r.v v24, (t1)
; RV64-NEXT:    ld t1, 56(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t1, s2, t1
; RV64-NEXT:    vl1r.v v29, (t0)
; RV64-NEXT:    ld t4, 192(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t4, s2, t4
; RV64-NEXT:    vl1r.v v16, (t3)
; RV64-NEXT:    ld t3, 184(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t3, s2, t3
; RV64-NEXT:    vl1r.v v27, (t2)
; RV64-NEXT:    ld t2, 216(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t2, s2, t2
; RV64-NEXT:    vl1r.v v7, (t1)
; RV64-NEXT:    ld t0, 176(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t0, s2, t0
; RV64-NEXT:    vl1r.v v5, (t4)
; RV64-NEXT:    ld t1, 48(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t1, s2, t1
; RV64-NEXT:    vl1r.v v4, (t3)
; RV64-NEXT:    ld t3, 40(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t3, s2, t3
; RV64-NEXT:    vl1r.v v3, (t2)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 92
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v3, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld t5, 248(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t5, s2, t5
; RV64-NEXT:    vl1r.v v28, (t0)
; RV64-NEXT:    ld t4, 32(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t4, s2, t4
; RV64-NEXT:    vl1r.v v2, (t1)
; RV64-NEXT:    ld t2, 168(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t2, s2, t2
; RV64-NEXT:    vl1r.v v0, (t3)
; RV64-NEXT:    ld t0, 160(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t0, s2, t0
; RV64-NEXT:    vl1r.v v30, (t5)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 93
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v30, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld t1, 152(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t1, s2, t1
; RV64-NEXT:    vl1r.v v20, (t4)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 114
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v20, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld t3, 144(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t3, s2, t3
; RV64-NEXT:    vl1r.v v15, (t2)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 113
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v15, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld t4, 136(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t4, s2, t4
; RV64-NEXT:    vl1r.v v14, (t0)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 102
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v14, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld t5, 128(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t5, s2, t5
; RV64-NEXT:    vl1r.v v1, (t1)
; RV64-NEXT:    ld t2, 224(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t2, s2, t2
; RV64-NEXT:    vl1r.v v31, (t3)
; RV64-NEXT:    ld t1, 120(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t1, s2, t1
; RV64-NEXT:    vl1r.v v26, (t4)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 104
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v26, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld t0, 112(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t0, s2, t0
; RV64-NEXT:    vl1r.v v25, (t5)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li a5, 94
; RV64-NEXT:    mul a4, a4, a5
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v25, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a5, 104(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a5, s2, a5
; RV64-NEXT:    vl1r.v v21, (t2)
; RV64-NEXT:    csrr a4, vlenb
; RV64-NEXT:    li t2, 117
; RV64-NEXT:    mul a4, a4, t2
; RV64-NEXT:    add a4, sp, a4
; RV64-NEXT:    addi a4, a4, 864
; RV64-NEXT:    vs1r.v v21, (a4) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a4, 832(sp) # 8-byte Folded Reload
; RV64-NEXT:    sub t2, a4, t6
; RV64-NEXT:    vl1r.v v22, (t1)
; RV64-NEXT:    csrr t1, vlenb
; RV64-NEXT:    li t3, 116
; RV64-NEXT:    mul t1, t1, t3
; RV64-NEXT:    add t1, sp, t1
; RV64-NEXT:    addi t1, t1, 864
; RV64-NEXT:    vs1r.v v22, (t1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld t1, 96(sp) # 8-byte Folded Reload
; RV64-NEXT:    add t1, s2, t1
; RV64-NEXT:    vl1r.v v23, (t0)
; RV64-NEXT:    csrr t0, vlenb
; RV64-NEXT:    li t3, 108
; RV64-NEXT:    mul t0, t0, t3
; RV64-NEXT:    add t0, sp, t0
; RV64-NEXT:    addi t0, t0, 864
; RV64-NEXT:    vs1r.v v23, (t0) # vscale x 8-byte Folded Spill
; RV64-NEXT:    vl1r.v v10, (a5)
; RV64-NEXT:    csrr a5, vlenb
; RV64-NEXT:    li t0, 111
; RV64-NEXT:    mul a5, a5, t0
; RV64-NEXT:    add a5, sp, a5
; RV64-NEXT:    addi a5, a5, 864
; RV64-NEXT:    vs1r.v v10, (a5) # vscale x 8-byte Folded Spill
; RV64-NEXT:    sd t2, 24(sp) # 8-byte Folded Spill
; RV64-NEXT:    add a5, s2, t2
; RV64-NEXT:    vl1r.v v17, (t1)
; RV64-NEXT:    csrr t0, vlenb
; RV64-NEXT:    li t1, 112
; RV64-NEXT:    mul t0, t0, t1
; RV64-NEXT:    add t0, sp, t0
; RV64-NEXT:    addi t0, t0, 864
; RV64-NEXT:    vs1r.v v17, (t0) # vscale x 8-byte Folded Spill
; RV64-NEXT:    vl1r.v v11, (a5)
; RV64-NEXT:    csrr a5, vlenb
; RV64-NEXT:    li t0, 110
; RV64-NEXT:    mul a5, a5, t0
; RV64-NEXT:    add a5, sp, a5
; RV64-NEXT:    addi a5, a5, 864
; RV64-NEXT:    vs1r.v v11, (a5) # vscale x 8-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    vwmul.vx v8, v6, a6
; RV64-NEXT:    lb a5, 96(a0)
; RV64-NEXT:    lb a6, 97(a0)
; RV64-NEXT:    sd a6, 320(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 98(a0)
; RV64-NEXT:    sd a6, 528(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 99(a0)
; RV64-NEXT:    sd a6, 680(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a2, v12
; RV64-NEXT:    vwmacc.vx v8, s0, v13
; RV64-NEXT:    vwmacc.vx v8, a7, v18
; RV64-NEXT:    vwmacc.vx v8, a3, v19
; RV64-NEXT:    lb a2, 112(a0)
; RV64-NEXT:    lb a3, 113(a0)
; RV64-NEXT:    sd a3, 296(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 114(a0)
; RV64-NEXT:    sd a3, 504(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 115(a0)
; RV64-NEXT:    sd a3, 672(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v24
; RV64-NEXT:    vwmacc.vx v8, a5, v29
; RV64-NEXT:    vwmacc.vx v8, a2, v16
; RV64-NEXT:    lb a1, 128(a0)
; RV64-NEXT:    lb a2, 129(a0)
; RV64-NEXT:    sd a2, 272(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 130(a0)
; RV64-NEXT:    sd a2, 480(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 131(a0)
; RV64-NEXT:    sd a2, 664(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    lb a1, 144(a0)
; RV64-NEXT:    lb a2, 145(a0)
; RV64-NEXT:    sd a2, 264(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 146(a0)
; RV64-NEXT:    sd a2, 472(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 147(a0)
; RV64-NEXT:    sd a2, 656(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v7
; RV64-NEXT:    lb a1, 160(a0)
; RV64-NEXT:    lb ra, 161(a0)
; RV64-NEXT:    lb a2, 162(a0)
; RV64-NEXT:    sd a2, 456(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 163(a0)
; RV64-NEXT:    sd a2, 648(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v5
; RV64-NEXT:    lb a1, 176(a0)
; RV64-NEXT:    lb s11, 177(a0)
; RV64-NEXT:    lb a2, 178(a0)
; RV64-NEXT:    sd a2, 448(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 179(a0)
; RV64-NEXT:    sd a2, 640(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v4
; RV64-NEXT:    lb a1, 192(a0)
; RV64-NEXT:    lb s10, 193(a0)
; RV64-NEXT:    lb a2, 194(a0)
; RV64-NEXT:    sd a2, 440(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 195(a0)
; RV64-NEXT:    sd a2, 632(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    lb a1, 208(a0)
; RV64-NEXT:    lb s9, 209(a0)
; RV64-NEXT:    lb a2, 210(a0)
; RV64-NEXT:    sd a2, 432(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 211(a0)
; RV64-NEXT:    sd a2, 624(sp) # 8-byte Folded Spill
; RV64-NEXT:    vmv1r.v v3, v28
; RV64-NEXT:    vwmacc.vx v8, a1, v28
; RV64-NEXT:    lb a1, 224(a0)
; RV64-NEXT:    lb s8, 225(a0)
; RV64-NEXT:    lb a2, 226(a0)
; RV64-NEXT:    sd a2, 424(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 227(a0)
; RV64-NEXT:    sd a2, 616(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v2
; RV64-NEXT:    lb a1, 240(a0)
; RV64-NEXT:    lb s7, 241(a0)
; RV64-NEXT:    lb a2, 242(a0)
; RV64-NEXT:    sd a2, 416(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 243(a0)
; RV64-NEXT:    sd a2, 608(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v0
; RV64-NEXT:    lb a1, 256(a0)
; RV64-NEXT:    lb s6, 257(a0)
; RV64-NEXT:    lb a2, 258(a0)
; RV64-NEXT:    sd a2, 408(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 259(a0)
; RV64-NEXT:    sd a2, 600(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v30
; RV64-NEXT:    lb a1, 272(a0)
; RV64-NEXT:    lb s5, 273(a0)
; RV64-NEXT:    lb a2, 274(a0)
; RV64-NEXT:    sd a2, 400(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 275(a0)
; RV64-NEXT:    sd a2, 592(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    lb a1, 288(a0)
; RV64-NEXT:    lb s3, 289(a0)
; RV64-NEXT:    lb a2, 290(a0)
; RV64-NEXT:    sd a2, 392(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 291(a0)
; RV64-NEXT:    sd a2, 584(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v15
; RV64-NEXT:    lb a1, 304(a0)
; RV64-NEXT:    lb s0, 305(a0)
; RV64-NEXT:    lb a2, 306(a0)
; RV64-NEXT:    sd a2, 384(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 307(a0)
; RV64-NEXT:    sd a2, 576(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v14
; RV64-NEXT:    lb a1, 320(a0)
; RV64-NEXT:    lb t6, 321(a0)
; RV64-NEXT:    lb a2, 322(a0)
; RV64-NEXT:    sd a2, 376(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 323(a0)
; RV64-NEXT:    sd a2, 568(sp) # 8-byte Folded Spill
; RV64-NEXT:    vmv1r.v v28, v1
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 96
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vs1r.v v1, (a2) # vscale x 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v1
; RV64-NEXT:    lb a1, 336(a0)
; RV64-NEXT:    lb t5, 337(a0)
; RV64-NEXT:    lb a2, 338(a0)
; RV64-NEXT:    sd a2, 360(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 339(a0)
; RV64-NEXT:    sd a2, 560(sp) # 8-byte Folded Spill
; RV64-NEXT:    vmv1r.v v1, v31
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 95
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vs1r.v v31, (a2) # vscale x 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v31
; RV64-NEXT:    lb a1, 352(a0)
; RV64-NEXT:    lb t4, 353(a0)
; RV64-NEXT:    lb a2, 354(a0)
; RV64-NEXT:    sd a2, 352(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 355(a0)
; RV64-NEXT:    sd a2, 552(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v26
; RV64-NEXT:    lb a1, 368(a0)
; RV64-NEXT:    lb t3, 369(a0)
; RV64-NEXT:    lb a2, 370(a0)
; RV64-NEXT:    sd a2, 344(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 371(a0)
; RV64-NEXT:    sd a2, 544(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v25
; RV64-NEXT:    lb a1, 384(a0)
; RV64-NEXT:    lb t2, 385(a0)
; RV64-NEXT:    lb a2, 386(a0)
; RV64-NEXT:    sd a2, 336(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 387(a0)
; RV64-NEXT:    sd a2, 536(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v21
; RV64-NEXT:    lb a1, 400(a0)
; RV64-NEXT:    lb t1, 401(a0)
; RV64-NEXT:    lb a2, 402(a0)
; RV64-NEXT:    sd a2, 328(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 403(a0)
; RV64-NEXT:    sd a2, 520(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v22
; RV64-NEXT:    lb a1, 416(a0)
; RV64-NEXT:    lb t0, 417(a0)
; RV64-NEXT:    lb a2, 418(a0)
; RV64-NEXT:    sd a2, 312(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 419(a0)
; RV64-NEXT:    sd a2, 512(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v23
; RV64-NEXT:    lb a1, 432(a0)
; RV64-NEXT:    lb a7, 433(a0)
; RV64-NEXT:    lb a2, 434(a0)
; RV64-NEXT:    sd a2, 304(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 435(a0)
; RV64-NEXT:    sd a2, 496(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v10
; RV64-NEXT:    lb a1, 448(a0)
; RV64-NEXT:    lb a6, 449(a0)
; RV64-NEXT:    lb a2, 450(a0)
; RV64-NEXT:    sd a2, 288(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 451(a0)
; RV64-NEXT:    sd a2, 488(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v11
; RV64-NEXT:    lb a2, 464(a0)
; RV64-NEXT:    lb a5, 465(a0)
; RV64-NEXT:    lb a1, 466(a0)
; RV64-NEXT:    sd a1, 280(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a1, 467(a0)
; RV64-NEXT:    sd a1, 464(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a2, v17
; RV64-NEXT:    sub a2, a4, s4
; RV64-NEXT:    add a2, s2, a2
; RV64-NEXT:    lb a1, 480(a0)
; RV64-NEXT:    vl1r.v v10, (a2)
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 98
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vs1r.v v10, (a2) # vscale x 8-byte Folded Spill
; RV64-NEXT:    lb a3, 481(a0)
; RV64-NEXT:    lb s2, 482(a0)
; RV64-NEXT:    lb a2, 483(a0)
; RV64-NEXT:    sd a2, 368(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v10
; RV64-NEXT:    ld a1, 848(sp) # 8-byte Folded Reload
; RV64-NEXT:    sub a2, a4, a1
; RV64-NEXT:    ld a4, 840(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a4, a4, a2
; RV64-NEXT:    lb a1, 496(a0)
; RV64-NEXT:    lb a2, 497(a0)
; RV64-NEXT:    vl1r.v v26, (a4)
; RV64-NEXT:    sd s1, 256(sp) # 8-byte Folded Spill
; RV64-NEXT:    vl1r.v v10, (s1)
; RV64-NEXT:    lb a4, 498(a0)
; RV64-NEXT:    lb s4, 499(a0)
; RV64-NEXT:    vwmacc.vx v8, a1, v26
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 107
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v26, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vsext.vf2 v14, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 80
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a1, a1, 5
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vwmacc.vv v20, v8, v14
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 100
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs2r.v v14, (a1) # vscale x 16-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 80
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vmv1r.v v11, v6
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 88
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v6, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 760(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v8, v6, a1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 97
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v12, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 736(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 115
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v13, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 720(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v13
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 106
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v18, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 704(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v18
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 105
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v19, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 696(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v19
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 109
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v24, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 688(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v24
; RV64-NEXT:    vmv1r.v v25, v29
; RV64-NEXT:    ld a1, 320(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v29
; RV64-NEXT:    ld a1, 296(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    ld a1, 272(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    ld a1, 264(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v7
; RV64-NEXT:    vwmacc.vx v8, ra, v5
; RV64-NEXT:    vwmacc.vx v8, s11, v4
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 92
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v6, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s10, v6
; RV64-NEXT:    vwmacc.vx v8, s9, v3
; RV64-NEXT:    vwmacc.vx v8, s8, v2
; RV64-NEXT:    vwmacc.vx v8, s7, v0
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 93
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v30, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s6, v30
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 114
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v31, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s5, v31
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 113
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s3, v17
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s1, 102
; RV64-NEXT:    mul a1, a1, s1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v29, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v29
; RV64-NEXT:    vwmacc.vx v8, t6, v28
; RV64-NEXT:    vwmacc.vx v8, t5, v1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t5, 104
; RV64-NEXT:    mul a1, a1, t5
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v1, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t4, v1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t4, 94
; RV64-NEXT:    mul a1, a1, t4
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v28, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t3, v28
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t3, 117
; RV64-NEXT:    mul a1, a1, t3
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t2, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t2, 116
; RV64-NEXT:    mul a1, a1, t2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t1, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t1, 108
; RV64-NEXT:    mul a1, a1, t1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t0, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 111
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a7, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a7, 110
; RV64-NEXT:    mul a1, a1, a7
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a6, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a6, 112
; RV64-NEXT:    mul a1, a1, a6
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a5, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a5, 98
; RV64-NEXT:    mul a1, a1, a5
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a3, v10
; RV64-NEXT:    vwmacc.vx v8, a2, v26
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 76
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 28
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v20, v8, v14
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 76
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 800(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v8, v11, a1
; RV64-NEXT:    ld a1, 784(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    ld a1, 768(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v13
; RV64-NEXT:    ld a1, 744(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v18
; RV64-NEXT:    ld a1, 728(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v19
; RV64-NEXT:    ld a1, 712(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v24
; RV64-NEXT:    ld a1, 528(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v25
; RV64-NEXT:    vmv1r.v v26, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 99
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v16, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 504(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    ld a1, 480(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    ld a1, 472(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v7
; RV64-NEXT:    ld a1, 456(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v5
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 103
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v4, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 448(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v4
; RV64-NEXT:    ld a1, 440(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v6
; RV64-NEXT:    ld a1, 432(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    ld a1, 424(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v2
; RV64-NEXT:    ld a1, 416(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v0
; RV64-NEXT:    vmv1r.v v18, v30
; RV64-NEXT:    ld a1, 408(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v30
; RV64-NEXT:    vmv1r.v v12, v31
; RV64-NEXT:    ld a1, 400(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v31
; RV64-NEXT:    vmv1r.v v24, v17
; RV64-NEXT:    ld a1, 392(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v17
; RV64-NEXT:    ld a1, 384(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v29
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 96
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v30, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 376(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v30
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v31, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 360(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v31
; RV64-NEXT:    ld a1, 352(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v1
; RV64-NEXT:    ld a1, 344(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v28
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 117
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v19, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 336(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v19
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 116
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v13, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 328(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v13
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 108
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v14, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 312(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v14
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 111
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 304(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v15
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 110
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v29, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 288(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v29
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 112
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 280(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    vwmacc.vx v8, s2, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 107
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a4, v17
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 72
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 24
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 100
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl2r.v v10, (a1) # vscale x 16-byte Folded Reload
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v20, v8, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 72
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 88
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 824(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v8, v20, a1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 97
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 816(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 115
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 808(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 106
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 792(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 105
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 776(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 109
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v20, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 752(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    ld a1, 680(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v25
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 91
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v25, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 672(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v26
; RV64-NEXT:    ld a1, 664(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 87
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v27, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 656(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v7
; RV64-NEXT:    vmv1r.v v26, v7
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 90
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v7, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 648(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v5
; RV64-NEXT:    ld a1, 640(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v4
; RV64-NEXT:    ld a1, 632(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v6
; RV64-NEXT:    vmv1r.v v4, v6
; RV64-NEXT:    ld a1, 624(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 89
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v3, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 616(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v2
; RV64-NEXT:    ld a1, 608(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v0
; RV64-NEXT:    ld a1, 600(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v18
; RV64-NEXT:    ld a1, 592(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    ld a1, 584(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v24
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 102
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v24, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 576(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v24
; RV64-NEXT:    ld a1, 568(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v30
; RV64-NEXT:    ld a1, 560(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v31
; RV64-NEXT:    ld a1, 552(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v1
; RV64-NEXT:    ld a1, 544(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v28
; RV64-NEXT:    ld a1, 536(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v19
; RV64-NEXT:    ld a1, 520(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v13
; RV64-NEXT:    ld a1, 512(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v14
; RV64-NEXT:    ld a1, 496(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v15
; RV64-NEXT:    ld a1, 488(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v29
; RV64-NEXT:    ld a1, 464(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 98
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 368(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    vwmacc.vx v8, s4, v17
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 68
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v20, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 20
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v20, v8, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 68
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v20, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    lb a1, 4(a0)
; RV64-NEXT:    lb a2, 5(a0)
; RV64-NEXT:    sd a2, 408(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 6(a0)
; RV64-NEXT:    sd a2, 656(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 7(a0)
; RV64-NEXT:    sd a2, 824(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 20(a0)
; RV64-NEXT:    lb a3, 21(a0)
; RV64-NEXT:    sd a3, 392(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 22(a0)
; RV64-NEXT:    sd a3, 648(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 23(a0)
; RV64-NEXT:    sd a3, 816(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 36(a0)
; RV64-NEXT:    lb a4, 37(a0)
; RV64-NEXT:    sd a4, 384(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 38(a0)
; RV64-NEXT:    sd a4, 640(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 39(a0)
; RV64-NEXT:    sd a4, 808(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 52(a0)
; RV64-NEXT:    lb a5, 53(a0)
; RV64-NEXT:    sd a5, 368(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a5, 54(a0)
; RV64-NEXT:    sd a5, 624(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a5, 55(a0)
; RV64-NEXT:    sd a5, 800(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a5, 68(a0)
; RV64-NEXT:    lb a6, 69(a0)
; RV64-NEXT:    sd a6, 360(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 70(a0)
; RV64-NEXT:    sd a6, 616(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 71(a0)
; RV64-NEXT:    sd a6, 792(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 84(a0)
; RV64-NEXT:    lb a7, 85(a0)
; RV64-NEXT:    sd a7, 352(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a7, 86(a0)
; RV64-NEXT:    sd a7, 608(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a7, 87(a0)
; RV64-NEXT:    sd a7, 784(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a7, 100(a0)
; RV64-NEXT:    lb t0, 101(a0)
; RV64-NEXT:    sd t0, 336(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb t0, 102(a0)
; RV64-NEXT:    sd t0, 592(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb t0, 103(a0)
; RV64-NEXT:    sd t0, 776(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr t0, vlenb
; RV64-NEXT:    li t1, 88
; RV64-NEXT:    mul t0, t0, t1
; RV64-NEXT:    add t0, sp, t0
; RV64-NEXT:    addi t0, t0, 864
; RV64-NEXT:    vl1r.v v19, (t0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    vwmul.vx v8, v19, a1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 97
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v13, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a2, v13
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 115
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a3, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 106
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v6, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a4, v6
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 105
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v7, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a5, v7
; RV64-NEXT:    lb a1, 116(a0)
; RV64-NEXT:    lb a2, 117(a0)
; RV64-NEXT:    sd a2, 304(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 118(a0)
; RV64-NEXT:    sd a2, 544(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 119(a0)
; RV64-NEXT:    sd a2, 768(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 109
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a6, v16
; RV64-NEXT:    vwmacc.vx v8, a7, v25
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 99
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    lb a1, 132(a0)
; RV64-NEXT:    lb a2, 133(a0)
; RV64-NEXT:    sd a2, 280(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 134(a0)
; RV64-NEXT:    sd a2, 520(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 135(a0)
; RV64-NEXT:    sd a2, 760(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    lb a1, 148(a0)
; RV64-NEXT:    lb a2, 149(a0)
; RV64-NEXT:    sd a2, 264(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 150(a0)
; RV64-NEXT:    sd a2, 496(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 151(a0)
; RV64-NEXT:    sd a2, 752(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v26
; RV64-NEXT:    lb a1, 164(a0)
; RV64-NEXT:    lb s10, 165(a0)
; RV64-NEXT:    lb a2, 166(a0)
; RV64-NEXT:    sd a2, 488(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 167(a0)
; RV64-NEXT:    sd a2, 744(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v5
; RV64-NEXT:    lb a1, 180(a0)
; RV64-NEXT:    lb s7, 181(a0)
; RV64-NEXT:    lb a2, 182(a0)
; RV64-NEXT:    sd a2, 480(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 183(a0)
; RV64-NEXT:    sd a2, 736(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 103
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    lb a1, 196(a0)
; RV64-NEXT:    lb t5, 197(a0)
; RV64-NEXT:    lb a2, 198(a0)
; RV64-NEXT:    sd a2, 472(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 199(a0)
; RV64-NEXT:    sd a2, 728(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v4
; RV64-NEXT:    lb a1, 212(a0)
; RV64-NEXT:    lb t4, 213(a0)
; RV64-NEXT:    lb a2, 214(a0)
; RV64-NEXT:    sd a2, 464(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 215(a0)
; RV64-NEXT:    sd a2, 720(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    lb a1, 228(a0)
; RV64-NEXT:    lb t3, 229(a0)
; RV64-NEXT:    lb a2, 230(a0)
; RV64-NEXT:    sd a2, 456(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 231(a0)
; RV64-NEXT:    sd a2, 712(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v2
; RV64-NEXT:    lb a1, 244(a0)
; RV64-NEXT:    lb t2, 245(a0)
; RV64-NEXT:    lb a2, 246(a0)
; RV64-NEXT:    sd a2, 448(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 247(a0)
; RV64-NEXT:    sd a2, 704(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v0
; RV64-NEXT:    lb a1, 260(a0)
; RV64-NEXT:    lb t1, 261(a0)
; RV64-NEXT:    lb a2, 262(a0)
; RV64-NEXT:    sd a2, 440(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 263(a0)
; RV64-NEXT:    sd a2, 696(sp) # 8-byte Folded Spill
; RV64-NEXT:    vmv1r.v v3, v18
; RV64-NEXT:    vwmacc.vx v8, a1, v18
; RV64-NEXT:    lb a1, 276(a0)
; RV64-NEXT:    lb t0, 277(a0)
; RV64-NEXT:    lb a2, 278(a0)
; RV64-NEXT:    sd a2, 432(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 279(a0)
; RV64-NEXT:    sd a2, 688(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 114
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v29, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v29
; RV64-NEXT:    lb a1, 292(a0)
; RV64-NEXT:    lb a7, 293(a0)
; RV64-NEXT:    lb a2, 294(a0)
; RV64-NEXT:    sd a2, 424(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 295(a0)
; RV64-NEXT:    sd a2, 680(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 113
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v27, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    lb a1, 308(a0)
; RV64-NEXT:    lb a6, 309(a0)
; RV64-NEXT:    lb a2, 310(a0)
; RV64-NEXT:    sd a2, 416(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 311(a0)
; RV64-NEXT:    sd a2, 672(sp) # 8-byte Folded Spill
; RV64-NEXT:    vmv1r.v v1, v24
; RV64-NEXT:    vwmacc.vx v8, a1, v24
; RV64-NEXT:    lb a1, 324(a0)
; RV64-NEXT:    lb a4, 325(a0)
; RV64-NEXT:    lb a2, 326(a0)
; RV64-NEXT:    sd a2, 400(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 327(a0)
; RV64-NEXT:    sd a2, 664(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v30
; RV64-NEXT:    lb a1, 340(a0)
; RV64-NEXT:    lb a3, 341(a0)
; RV64-NEXT:    lb a2, 342(a0)
; RV64-NEXT:    sd a2, 376(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 343(a0)
; RV64-NEXT:    sd a2, 632(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a1, v31
; RV64-NEXT:    lb a1, 356(a0)
; RV64-NEXT:    lb a2, 357(a0)
; RV64-NEXT:    lb a5, 358(a0)
; RV64-NEXT:    sd a5, 344(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a5, 359(a0)
; RV64-NEXT:    sd a5, 600(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd a6, 8(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a5, vlenb
; RV64-NEXT:    li a6, 104
; RV64-NEXT:    mul a5, a5, a6
; RV64-NEXT:    add a5, sp, a5
; RV64-NEXT:    addi a5, a5, 864
; RV64-NEXT:    vl1r.v v25, (a5) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v25
; RV64-NEXT:    lb a5, 372(a0)
; RV64-NEXT:    lb a1, 373(a0)
; RV64-NEXT:    lb t6, 374(a0)
; RV64-NEXT:    sd t6, 328(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb t6, 375(a0)
; RV64-NEXT:    sd t6, 584(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, a5, v28
; RV64-NEXT:    lb t6, 388(a0)
; RV64-NEXT:    lb a5, 389(a0)
; RV64-NEXT:    lb s0, 390(a0)
; RV64-NEXT:    sd s0, 320(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb s0, 391(a0)
; RV64-NEXT:    sd s0, 576(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li s0, 117
; RV64-NEXT:    mul a6, a6, s0
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 864
; RV64-NEXT:    vl1r.v v24, (a6) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t6, v24
; RV64-NEXT:    lb t6, 404(a0)
; RV64-NEXT:    lb ra, 405(a0)
; RV64-NEXT:    lb s0, 406(a0)
; RV64-NEXT:    sd s0, 312(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb s0, 407(a0)
; RV64-NEXT:    sd s0, 568(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li s0, 116
; RV64-NEXT:    mul a6, a6, s0
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 864
; RV64-NEXT:    vl1r.v v26, (a6) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t6, v26
; RV64-NEXT:    lb t6, 420(a0)
; RV64-NEXT:    lb s9, 421(a0)
; RV64-NEXT:    lb s0, 422(a0)
; RV64-NEXT:    sd s0, 296(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb s0, 423(a0)
; RV64-NEXT:    sd s0, 560(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, t6, v14
; RV64-NEXT:    lb t6, 436(a0)
; RV64-NEXT:    lb s8, 437(a0)
; RV64-NEXT:    lb s0, 438(a0)
; RV64-NEXT:    sd s0, 288(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb s0, 439(a0)
; RV64-NEXT:    sd s0, 552(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v8, t6, v15
; RV64-NEXT:    lb t6, 452(a0)
; RV64-NEXT:    lb s5, 453(a0)
; RV64-NEXT:    lb s0, 454(a0)
; RV64-NEXT:    sd s0, 272(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb s0, 455(a0)
; RV64-NEXT:    sd s0, 536(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li s0, 110
; RV64-NEXT:    mul a6, a6, s0
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 864
; RV64-NEXT:    vl1r.v v16, (a6) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t6, v16
; RV64-NEXT:    lb t6, 468(a0)
; RV64-NEXT:    lb s4, 469(a0)
; RV64-NEXT:    lb s11, 470(a0)
; RV64-NEXT:    lb s0, 471(a0)
; RV64-NEXT:    sd s0, 528(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li s0, 112
; RV64-NEXT:    mul a6, a6, s0
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 864
; RV64-NEXT:    vl1r.v v18, (a6) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t6, v18
; RV64-NEXT:    lb t6, 484(a0)
; RV64-NEXT:    lb s3, 485(a0)
; RV64-NEXT:    lb s6, 486(a0)
; RV64-NEXT:    lb s0, 487(a0)
; RV64-NEXT:    sd s0, 512(sp) # 8-byte Folded Spill
; RV64-NEXT:    vmv1r.v v17, v12
; RV64-NEXT:    vwmacc.vx v8, t6, v12
; RV64-NEXT:    lb s0, 500(a0)
; RV64-NEXT:    lb s2, 501(a0)
; RV64-NEXT:    lb t6, 502(a0)
; RV64-NEXT:    lb s1, 503(a0)
; RV64-NEXT:    sd s1, 504(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr s1, vlenb
; RV64-NEXT:    li a6, 107
; RV64-NEXT:    mul s1, s1, a6
; RV64-NEXT:    ld a6, 8(sp) # 8-byte Folded Reload
; RV64-NEXT:    add s1, sp, s1
; RV64-NEXT:    addi s1, s1, 864
; RV64-NEXT:    vl1r.v v12, (s1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v12
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    slli s0, s0, 6
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl4r.v v20, (s0) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    slli s0, s0, 4
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vs4r.v v20, (s0) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v20, v8, v10
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    slli s0, s0, 6
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vs4r.v v20, (s0) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld s0, 408(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v8, v19, s0
; RV64-NEXT:    vmv1r.v v21, v13
; RV64-NEXT:    ld s0, 392(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v13
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li s1, 115
; RV64-NEXT:    mul s0, s0, s1
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl1r.v v13, (s0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld s0, 384(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v13
; RV64-NEXT:    ld s0, 368(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v6
; RV64-NEXT:    ld s0, 360(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v7
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li s1, 109
; RV64-NEXT:    mul s0, s0, s1
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl1r.v v20, (s0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld s0, 352(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v20
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li s1, 91
; RV64-NEXT:    mul s0, s0, s1
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl1r.v v7, (s0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld s0, 336(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v7
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li s1, 99
; RV64-NEXT:    mul s0, s0, s1
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl1r.v v22, (s0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld s0, 304(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v22
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li s1, 87
; RV64-NEXT:    mul s0, s0, s1
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl1r.v v22, (s0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld s0, 280(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v22
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li s1, 90
; RV64-NEXT:    mul s0, s0, s1
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl1r.v v6, (s0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld s0, 264(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s0, v6
; RV64-NEXT:    vwmacc.vx v8, s10, v5
; RV64-NEXT:    csrr s0, vlenb
; RV64-NEXT:    li s1, 103
; RV64-NEXT:    mul s0, s0, s1
; RV64-NEXT:    add s0, sp, s0
; RV64-NEXT:    addi s0, s0, 864
; RV64-NEXT:    vl1r.v v23, (s0) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, s7, v23
; RV64-NEXT:    vwmacc.vx v8, t5, v4
; RV64-NEXT:    csrr t5, vlenb
; RV64-NEXT:    li s0, 89
; RV64-NEXT:    mul t5, t5, s0
; RV64-NEXT:    add t5, sp, t5
; RV64-NEXT:    addi t5, t5, 864
; RV64-NEXT:    vl1r.v v23, (t5) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, t4, v23
; RV64-NEXT:    vwmacc.vx v8, t3, v2
; RV64-NEXT:    vwmacc.vx v8, t2, v0
; RV64-NEXT:    vwmacc.vx v8, t1, v3
; RV64-NEXT:    vwmacc.vx v8, t0, v29
; RV64-NEXT:    vwmacc.vx v8, a7, v27
; RV64-NEXT:    vwmacc.vx v8, a6, v1
; RV64-NEXT:    vwmacc.vx v8, a4, v30
; RV64-NEXT:    vwmacc.vx v8, a3, v31
; RV64-NEXT:    vwmacc.vx v8, a2, v25
; RV64-NEXT:    vwmacc.vx v8, a1, v28
; RV64-NEXT:    vwmacc.vx v8, a5, v24
; RV64-NEXT:    vwmacc.vx v8, ra, v26
; RV64-NEXT:    vwmacc.vx v8, s9, v14
; RV64-NEXT:    vmv1r.v v31, v14
; RV64-NEXT:    vwmacc.vx v8, s8, v15
; RV64-NEXT:    vwmacc.vx v8, s5, v16
; RV64-NEXT:    vwmacc.vx v8, s4, v18
; RV64-NEXT:    vmv1r.v v30, v18
; RV64-NEXT:    vwmacc.vx v8, s3, v17
; RV64-NEXT:    vmv1r.v v28, v17
; RV64-NEXT:    vwmacc.vx v8, s2, v12
; RV64-NEXT:    vmv1r.v v29, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 60
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v24, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 12
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v24, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v24, v8, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 60
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v24, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vmv1r.v v11, v19
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 656(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v8, v19, a1
; RV64-NEXT:    ld a1, 648(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v21
; RV64-NEXT:    ld a1, 640(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v13
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 106
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v18, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 624(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v18
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 105
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v19, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 616(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v19
; RV64-NEXT:    vmv1r.v v10, v20
; RV64-NEXT:    ld a1, 608(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    vmv1r.v v20, v7
; RV64-NEXT:    ld a1, 592(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v7
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 99
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v21, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 544(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v21
; RV64-NEXT:    ld a1, 520(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v22
; RV64-NEXT:    vmv1r.v v7, v6
; RV64-NEXT:    ld a1, 496(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v6
; RV64-NEXT:    vmv1r.v v6, v5
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 84
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v5, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 488(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v5
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 103
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v5, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 480(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v5
; RV64-NEXT:    ld a1, 472(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v4
; RV64-NEXT:    ld a1, 464(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v23
; RV64-NEXT:    vmv1r.v v24, v2
; RV64-NEXT:    ld a1, 456(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v2
; RV64-NEXT:    vmv1r.v v25, v0
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 85
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v0, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 448(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v0
; RV64-NEXT:    vmv1r.v v26, v3
; RV64-NEXT:    ld a1, 440(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 114
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v27, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 432(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 113
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v3, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 424(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    vmv1r.v v14, v1
; RV64-NEXT:    ld a1, 416(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 96
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v2, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 400(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v2
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v1, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 376(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 104
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v0, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 344(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v0
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 94
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 328(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v15
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 117
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 320(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 116
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 312(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v17
; RV64-NEXT:    ld a1, 296(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v31
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 111
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 288(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 110
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 272(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v17
; RV64-NEXT:    vwmacc.vx v8, s11, v30
; RV64-NEXT:    vwmacc.vx v8, s6, v28
; RV64-NEXT:    vwmacc.vx v8, t6, v29
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 56
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v28, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v28, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 100
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl2r.v v12, (a1) # vscale x 16-byte Folded Reload
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v28, v8, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 56
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v28, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 824(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v8, v11, a1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 97
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v28, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 816(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v28
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 115
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v29, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 808(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v29
; RV64-NEXT:    ld a1, 800(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v18
; RV64-NEXT:    ld a1, 792(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v19
; RV64-NEXT:    ld a1, 784(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v10
; RV64-NEXT:    ld a1, 776(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v20
; RV64-NEXT:    vmv1r.v v30, v20
; RV64-NEXT:    ld a1, 768(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v21
; RV64-NEXT:    ld a1, 760(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v22
; RV64-NEXT:    ld a1, 752(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v7
; RV64-NEXT:    vmv1r.v v31, v7
; RV64-NEXT:    ld a1, 744(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v6
; RV64-NEXT:    ld a1, 736(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v5
; RV64-NEXT:    ld a1, 728(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v4
; RV64-NEXT:    vmv1r.v v20, v4
; RV64-NEXT:    ld a1, 720(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v23
; RV64-NEXT:    ld a1, 712(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v24
; RV64-NEXT:    vmv1r.v v23, v24
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 86
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs1r.v v24, (a1) # vscale x 8-byte Folded Spill
; RV64-NEXT:    ld a1, 704(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v25
; RV64-NEXT:    ld a1, 696(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v26
; RV64-NEXT:    vmv1r.v v25, v26
; RV64-NEXT:    ld a1, 688(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v27
; RV64-NEXT:    ld a1, 680(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    ld a1, 672(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v14
; RV64-NEXT:    ld a1, 664(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v2
; RV64-NEXT:    vmv1r.v v14, v2
; RV64-NEXT:    ld a1, 632(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v1
; RV64-NEXT:    ld a1, 600(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v0
; RV64-NEXT:    ld a1, 584(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v15
; RV64-NEXT:    vmv1r.v v2, v15
; RV64-NEXT:    ld a1, 576(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 116
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 568(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 108
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v3, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 560(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v3
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 111
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 552(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    ld a1, 536(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v17
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 112
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 528(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 98
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 512(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v17
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 107
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 504(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v8, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 52
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v4, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 100
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl2r.v v12, (a1) # vscale x 16-byte Folded Reload
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v4, v8, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 52
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    lb a1, 8(a0)
; RV64-NEXT:    lb a2, 9(a0)
; RV64-NEXT:    sd a2, 400(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 10(a0)
; RV64-NEXT:    sd a2, 688(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 11(a0)
; RV64-NEXT:    sd a2, 824(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 24(a0)
; RV64-NEXT:    lb a3, 25(a0)
; RV64-NEXT:    sd a3, 392(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 26(a0)
; RV64-NEXT:    sd a3, 680(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 27(a0)
; RV64-NEXT:    sd a3, 816(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a3, 40(a0)
; RV64-NEXT:    lb a4, 41(a0)
; RV64-NEXT:    sd a4, 376(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 42(a0)
; RV64-NEXT:    sd a4, 664(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 43(a0)
; RV64-NEXT:    sd a4, 808(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a4, 56(a0)
; RV64-NEXT:    lb a5, 57(a0)
; RV64-NEXT:    sd a5, 368(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a5, 58(a0)
; RV64-NEXT:    sd a5, 656(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a5, 59(a0)
; RV64-NEXT:    sd a5, 800(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a5, 72(a0)
; RV64-NEXT:    lb a6, 73(a0)
; RV64-NEXT:    sd a6, 360(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 74(a0)
; RV64-NEXT:    sd a6, 640(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 75(a0)
; RV64-NEXT:    sd a6, 792(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a6, 88(a0)
; RV64-NEXT:    lb a7, 89(a0)
; RV64-NEXT:    sd a7, 352(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a7, 90(a0)
; RV64-NEXT:    sd a7, 632(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a7, 91(a0)
; RV64-NEXT:    sd a7, 784(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a7, 104(a0)
; RV64-NEXT:    lb t0, 105(a0)
; RV64-NEXT:    sd t0, 344(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb t0, 106(a0)
; RV64-NEXT:    sd t0, 624(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb t0, 107(a0)
; RV64-NEXT:    sd t0, 776(sp) # 8-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    vwmul.vx v12, v11, a1
; RV64-NEXT:    vwmacc.vx v12, a2, v28
; RV64-NEXT:    vmv1r.v v8, v28
; RV64-NEXT:    vwmacc.vx v12, a3, v29
; RV64-NEXT:    vwmacc.vx v12, a4, v18
; RV64-NEXT:    vwmacc.vx v12, a5, v19
; RV64-NEXT:    lb a1, 120(a0)
; RV64-NEXT:    lb a2, 121(a0)
; RV64-NEXT:    sd a2, 312(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 122(a0)
; RV64-NEXT:    sd a2, 592(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 123(a0)
; RV64-NEXT:    sd a2, 768(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a6, v10
; RV64-NEXT:    vwmacc.vx v12, a7, v30
; RV64-NEXT:    vwmacc.vx v12, a1, v21
; RV64-NEXT:    lb a1, 136(a0)
; RV64-NEXT:    lb a2, 137(a0)
; RV64-NEXT:    sd a2, 296(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 138(a0)
; RV64-NEXT:    sd a2, 576(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 139(a0)
; RV64-NEXT:    sd a2, 760(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v22
; RV64-NEXT:    lb a1, 152(a0)
; RV64-NEXT:    lb a2, 153(a0)
; RV64-NEXT:    sd a2, 280(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 154(a0)
; RV64-NEXT:    sd a2, 560(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 155(a0)
; RV64-NEXT:    sd a2, 752(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v31
; RV64-NEXT:    lb a1, 168(a0)
; RV64-NEXT:    lb a2, 169(a0)
; RV64-NEXT:    sd a2, 264(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 170(a0)
; RV64-NEXT:    sd a2, 544(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 171(a0)
; RV64-NEXT:    sd a2, 744(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 84
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v27, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v27
; RV64-NEXT:    lb a1, 184(a0)
; RV64-NEXT:    lb s9, 185(a0)
; RV64-NEXT:    lb a2, 186(a0)
; RV64-NEXT:    sd a2, 528(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 187(a0)
; RV64-NEXT:    sd a2, 736(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 103
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v15, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v15
; RV64-NEXT:    lb a1, 200(a0)
; RV64-NEXT:    lb s8, 201(a0)
; RV64-NEXT:    lb a2, 202(a0)
; RV64-NEXT:    sd a2, 512(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 203(a0)
; RV64-NEXT:    sd a2, 728(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v20
; RV64-NEXT:    lb a1, 216(a0)
; RV64-NEXT:    lb s3, 217(a0)
; RV64-NEXT:    lb a2, 218(a0)
; RV64-NEXT:    sd a2, 504(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 219(a0)
; RV64-NEXT:    sd a2, 720(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 89
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v24, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v24
; RV64-NEXT:    lb a1, 232(a0)
; RV64-NEXT:    lb s0, 233(a0)
; RV64-NEXT:    lb a2, 234(a0)
; RV64-NEXT:    sd a2, 488(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 235(a0)
; RV64-NEXT:    sd a2, 712(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v23
; RV64-NEXT:    lb a1, 248(a0)
; RV64-NEXT:    lb t6, 249(a0)
; RV64-NEXT:    lb a2, 250(a0)
; RV64-NEXT:    sd a2, 472(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 251(a0)
; RV64-NEXT:    sd a2, 704(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 85
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v26, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v26
; RV64-NEXT:    lb a1, 264(a0)
; RV64-NEXT:    lb t5, 265(a0)
; RV64-NEXT:    lb a2, 266(a0)
; RV64-NEXT:    sd a2, 456(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 267(a0)
; RV64-NEXT:    sd a2, 696(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v25
; RV64-NEXT:    lb a1, 280(a0)
; RV64-NEXT:    lb t4, 281(a0)
; RV64-NEXT:    lb a2, 282(a0)
; RV64-NEXT:    sd a2, 440(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 283(a0)
; RV64-NEXT:    sd a2, 672(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 114
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v9, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v9
; RV64-NEXT:    lb a1, 296(a0)
; RV64-NEXT:    lb t3, 297(a0)
; RV64-NEXT:    lb a2, 298(a0)
; RV64-NEXT:    sd a2, 432(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 299(a0)
; RV64-NEXT:    sd a2, 648(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 113
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v9, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v9
; RV64-NEXT:    lb a1, 312(a0)
; RV64-NEXT:    lb t2, 313(a0)
; RV64-NEXT:    lb a2, 314(a0)
; RV64-NEXT:    sd a2, 416(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 315(a0)
; RV64-NEXT:    sd a2, 616(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 102
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v16, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v16
; RV64-NEXT:    lb a1, 328(a0)
; RV64-NEXT:    lb t1, 329(a0)
; RV64-NEXT:    lb a2, 330(a0)
; RV64-NEXT:    sd a2, 408(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 331(a0)
; RV64-NEXT:    sd a2, 608(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v14
; RV64-NEXT:    lb a1, 344(a0)
; RV64-NEXT:    lb t0, 345(a0)
; RV64-NEXT:    lb a2, 346(a0)
; RV64-NEXT:    sd a2, 384(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 347(a0)
; RV64-NEXT:    sd a2, 600(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v1
; RV64-NEXT:    lb a1, 360(a0)
; RV64-NEXT:    lb a7, 361(a0)
; RV64-NEXT:    lb a2, 362(a0)
; RV64-NEXT:    sd a2, 336(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 363(a0)
; RV64-NEXT:    sd a2, 584(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v0
; RV64-NEXT:    lb a1, 376(a0)
; RV64-NEXT:    lb a6, 377(a0)
; RV64-NEXT:    lb a2, 378(a0)
; RV64-NEXT:    sd a2, 328(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 379(a0)
; RV64-NEXT:    sd a2, 568(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v2
; RV64-NEXT:    lb a1, 392(a0)
; RV64-NEXT:    lb a5, 393(a0)
; RV64-NEXT:    lb a2, 394(a0)
; RV64-NEXT:    sd a2, 320(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 395(a0)
; RV64-NEXT:    sd a2, 552(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd t0, 8(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 117
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v18, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v18
; RV64-NEXT:    lb a1, 408(a0)
; RV64-NEXT:    lb a4, 409(a0)
; RV64-NEXT:    lb a2, 410(a0)
; RV64-NEXT:    sd a2, 304(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 411(a0)
; RV64-NEXT:    sd a2, 536(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    li a3, 116
; RV64-NEXT:    mul a2, a2, a3
; RV64-NEXT:    add a2, sp, a2
; RV64-NEXT:    addi a2, a2, 864
; RV64-NEXT:    vl1r.v v14, (a2) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v14
; RV64-NEXT:    lb a1, 424(a0)
; RV64-NEXT:    lb a3, 425(a0)
; RV64-NEXT:    lb a2, 426(a0)
; RV64-NEXT:    sd a2, 288(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a2, 427(a0)
; RV64-NEXT:    sd a2, 520(sp) # 8-byte Folded Spill
; RV64-NEXT:    vwmacc.vx v12, a1, v3
; RV64-NEXT:    lb s2, 440(a0)
; RV64-NEXT:    lb a2, 441(a0)
; RV64-NEXT:    lb a1, 442(a0)
; RV64-NEXT:    sd a1, 272(sp) # 8-byte Folded Spill
; RV64-NEXT:    lb a1, 443(a0)
; RV64-NEXT:    sd a1, 496(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 111
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v9, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, s2, v9
; RV64-NEXT:    lb s2, 456(a0)
; RV64-NEXT:    lb s11, 457(a0)
; RV64-NEXT:    lb ra, 458(a0)
; RV64-NEXT:    lb a1, 459(a0)
; RV64-NEXT:    sd a1, 480(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 110
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v19, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, s2, v19
; RV64-NEXT:    lb s2, 472(a0)
; RV64-NEXT:    lb s10, 473(a0)
; RV64-NEXT:    lb s5, 474(a0)
; RV64-NEXT:    lb a1, 475(a0)
; RV64-NEXT:    sd a1, 464(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 112
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v3, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, s2, v3
; RV64-NEXT:    lb s2, 488(a0)
; RV64-NEXT:    lb s7, 489(a0)
; RV64-NEXT:    lb s4, 490(a0)
; RV64-NEXT:    lb a1, 491(a0)
; RV64-NEXT:    sd a1, 448(sp) # 8-byte Folded Spill
; RV64-NEXT:    vmv1r.v v23, v17
; RV64-NEXT:    vwmacc.vx v12, s2, v17
; RV64-NEXT:    lb s1, 504(a0)
; RV64-NEXT:    lb s6, 505(a0)
; RV64-NEXT:    lb s2, 506(a0)
; RV64-NEXT:    lb a1, 507(a0)
; RV64-NEXT:    sd a1, 424(sp) # 8-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 107
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v25, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, s1, v25
; RV64-NEXT:    ld s1, 256(sp) # 8-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 48
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v4, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    addi a1, sp, 864
; RV64-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 100
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl2r.v v28, (a1) # vscale x 16-byte Folded Reload
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v4, v12, v28
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 48
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v4, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vmv1r.v v30, v11
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 400(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v12, v11, a1
; RV64-NEXT:    vmv1r.v v31, v8
; RV64-NEXT:    ld a1, 392(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v8
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 115
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v9, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 376(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v9
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 106
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 368(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 105
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 360(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v8
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 109
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v11, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 352(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v11
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 91
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 344(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v17
; RV64-NEXT:    vmv1r.v v20, v21
; RV64-NEXT:    ld a1, 312(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v21
; RV64-NEXT:    vmv1r.v v21, v22
; RV64-NEXT:    ld a1, 296(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v22
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t0, 90
; RV64-NEXT:    mul a1, a1, t0
; RV64-NEXT:    ld t0, 8(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v22, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 280(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v22
; RV64-NEXT:    ld a1, 264(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v27
; RV64-NEXT:    vwmacc.vx v12, s9, v15
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s9, 92
; RV64-NEXT:    mul a1, a1, s9
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, s8, v15
; RV64-NEXT:    vwmacc.vx v12, s3, v24
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li s3, 86
; RV64-NEXT:    mul a1, a1, s3
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v24, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, s0, v24
; RV64-NEXT:    vwmacc.vx v12, t6, v26
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t6, 93
; RV64-NEXT:    mul a1, a1, t6
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v26, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, t5, v26
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t5, 114
; RV64-NEXT:    mul a1, a1, t5
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v27, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, t4, v27
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t4, 113
; RV64-NEXT:    mul a1, a1, t4
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v7, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, t3, v7
; RV64-NEXT:    vwmacc.vx v12, t2, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li t2, 96
; RV64-NEXT:    mul a1, a1, t2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, t1, v16
; RV64-NEXT:    vwmacc.vx v12, t0, v1
; RV64-NEXT:    vwmacc.vx v12, a7, v0
; RV64-NEXT:    vwmacc.vx v12, a6, v2
; RV64-NEXT:    vwmacc.vx v12, a5, v18
; RV64-NEXT:    vwmacc.vx v12, a4, v14
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a4, 108
; RV64-NEXT:    mul a1, a1, a4
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v14, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a3, v14
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a3, 111
; RV64-NEXT:    mul a1, a1, a3
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v18, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a2, v18
; RV64-NEXT:    vwmacc.vx v12, s11, v19
; RV64-NEXT:    vmv1r.v v19, v3
; RV64-NEXT:    vwmacc.vx v12, s10, v3
; RV64-NEXT:    vwmacc.vx v12, s7, v23
; RV64-NEXT:    vwmacc.vx v12, s6, v25
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 44
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v0, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vmv4r.v v4, v0
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v0, v12, v28
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 44
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v0, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 688(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v12, v30, a1
; RV64-NEXT:    ld a1, 680(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v31
; RV64-NEXT:    ld a1, 664(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v9
; RV64-NEXT:    ld a1, 656(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v10
; RV64-NEXT:    ld a1, 640(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v8
; RV64-NEXT:    ld a1, 632(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v11
; RV64-NEXT:    ld a1, 624(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v17
; RV64-NEXT:    ld a1, 592(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v20
; RV64-NEXT:    ld a1, 576(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v21
; RV64-NEXT:    ld a1, 560(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v22
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 84
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 544(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 103
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v31, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 528(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v31
; RV64-NEXT:    ld a1, 512(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v15
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 89
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v11, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 504(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v11
; RV64-NEXT:    ld a1, 488(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v24
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 85
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v15, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 472(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v15
; RV64-NEXT:    ld a1, 456(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v26
; RV64-NEXT:    ld a1, 440(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v27
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 113
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v17, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 432(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v17
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 102
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v30, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 416(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v30
; RV64-NEXT:    ld a1, 408(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 384(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v8
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 104
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 336(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v8
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 94
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 328(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v8
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 117
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 320(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v8
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 116
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v16, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 304(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v16
; RV64-NEXT:    ld a1, 288(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v14
; RV64-NEXT:    ld a1, 272(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, a1, v18
; RV64-NEXT:    vmv1r.v v14, v18
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 110
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, ra, v8
; RV64-NEXT:    vwmacc.vx v12, s5, v19
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 98
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v9, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v12, s4, v9
; RV64-NEXT:    vwmacc.vx v12, s2, v25
; RV64-NEXT:    ld s2, 840(sp) # 8-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 40
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v0, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vmv4r.v v20, v0
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v0, v12, v28
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 40
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v0, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 36
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v24, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 88
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; RV64-NEXT:    ld a1, 824(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmul.vx v18, v12, a1
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 97
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 816(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 115
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 808(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 106
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 800(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 105
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 792(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 109
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 784(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 91
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 776(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 99
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 768(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 87
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 760(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 90
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v12, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 752(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v12
; RV64-NEXT:    ld a1, 744(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    ld a1, 736(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v31
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 92
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 728(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    ld a1, 720(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v11
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 86
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 712(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    ld a1, 704(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v15
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 93
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 696(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 114
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 672(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    ld a1, 648(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v17
; RV64-NEXT:    ld a1, 616(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v30
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 96
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 608(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 600(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 104
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 584(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 94
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 568(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 117
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 552(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    ld a1, 536(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 108
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v10, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 520(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v10
; RV64-NEXT:    ld a1, 496(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v14
; RV64-NEXT:    ld a1, 480(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v8
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 112
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 464(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v8
; RV64-NEXT:    ld a1, 448(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v9
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 107
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl1r.v v8, (a1) # vscale x 8-byte Folded Reload
; RV64-NEXT:    ld a1, 424(sp) # 8-byte Folded Reload
; RV64-NEXT:    vwmacc.vx v18, a1, v8
; RV64-NEXT:    vmv4r.v v12, v24
; RV64-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; RV64-NEXT:    vwmacc.vv v24, v18, v28
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 36
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vs4r.v v24, (a1) # vscale x 32-byte Folded Spill
; RV64-NEXT:    addi a0, a0, 512
; RV64-NEXT:    ld a1, 832(sp) # 8-byte Folded Reload
; RV64-NEXT:    add s2, s2, a1
; RV64-NEXT:    ld a1, 848(sp) # 8-byte Folded Reload
; RV64-NEXT:    add s1, s1, a1
; RV64-NEXT:    ld a1, 208(sp) # 8-byte Folded Reload
; RV64-NEXT:    beq a0, a1, .LBB1_2
; RV64-NEXT:    j .LBB1_1
; RV64-NEXT:  .LBB1_2: # %loop_end
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 5
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 864
; RV64-NEXT:    vl4r.v v16, (a0) # vscale x 32-byte Folded Reload
; RV64-NEXT:    ld a7, 16(sp) # 8-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a7)
; RV64-NEXT:    ld a0, 232(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a0, a7, a0
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 28
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a0)
; RV64-NEXT:    ld a0, 240(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a0, a7, a0
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 24
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a0)
; RV64-NEXT:    ld a0, 216(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a0, a7, a0
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 20
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a0)
; RV64-NEXT:    ld a0, 248(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a0, a7, a0
; RV64-NEXT:    li a1, 20
; RV64-NEXT:    ld a2, 224(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a2, a7, a2
; RV64-NEXT:    ld a3, 24(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a3, a7, a3
; RV64-NEXT:    ld a4, 832(sp) # 8-byte Folded Reload
; RV64-NEXT:    add a4, a7, a4
; RV64-NEXT:    li a5, 36
; RV64-NEXT:    li a6, 40
; RV64-NEXT:    csrr t0, vlenb
; RV64-NEXT:    slli t0, t0, 4
; RV64-NEXT:    add t0, sp, t0
; RV64-NEXT:    addi t0, t0, 864
; RV64-NEXT:    vl4r.v v16, (t0) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a0)
; RV64-NEXT:    li a0, 44
; RV64-NEXT:    ld t0, 848(sp) # 8-byte Folded Reload
; RV64-NEXT:    mul a1, t0, a1
; RV64-NEXT:    mul a5, t0, a5
; RV64-NEXT:    mul a6, t0, a6
; RV64-NEXT:    mul a0, t0, a0
; RV64-NEXT:    add a1, a7, a1
; RV64-NEXT:    add a5, a7, a5
; RV64-NEXT:    add a6, a7, a6
; RV64-NEXT:    add a0, a7, a0
; RV64-NEXT:    csrr a7, vlenb
; RV64-NEXT:    li t0, 12
; RV64-NEXT:    mul a7, a7, t0
; RV64-NEXT:    add a7, sp, a7
; RV64-NEXT:    addi a7, a7, 864
; RV64-NEXT:    vl4r.v v16, (a7) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a1)
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a2)
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 864
; RV64-NEXT:    vl4r.v v16, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v16, (a3)
; RV64-NEXT:    addi a1, sp, 864
; RV64-NEXT:    vl4r.v v8, (a1) # vscale x 32-byte Folded Reload
; RV64-NEXT:    vs4r.v v8, (a4)
; RV64-NEXT:    vs4r.v v4, (a5)
; RV64-NEXT:    vs4r.v v20, (a6)
; RV64-NEXT:    vs4r.v v12, (a0)
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 118
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add sp, sp, a0
; RV64-NEXT:    .cfi_def_cfa sp, 976
; RV64-NEXT:    ld ra, 968(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 960(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s1, 952(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s2, 944(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s3, 936(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s4, 928(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s5, 920(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s6, 912(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s7, 904(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s8, 896(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s9, 888(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s10, 880(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s11, 872(sp) # 8-byte Folded Reload
; RV64-NEXT:    .cfi_restore ra
; RV64-NEXT:    .cfi_restore s0
; RV64-NEXT:    .cfi_restore s1
; RV64-NEXT:    .cfi_restore s2
; RV64-NEXT:    .cfi_restore s3
; RV64-NEXT:    .cfi_restore s4
; RV64-NEXT:    .cfi_restore s5
; RV64-NEXT:    .cfi_restore s6
; RV64-NEXT:    .cfi_restore s7
; RV64-NEXT:    .cfi_restore s8
; RV64-NEXT:    .cfi_restore s9
; RV64-NEXT:    .cfi_restore s10
; RV64-NEXT:    .cfi_restore s11
; RV64-NEXT:    addi sp, sp, 976
; RV64-NEXT:    .cfi_def_cfa_offset 0
; RV64-NEXT:    ret
entry:
  br label %loop
loop:
  %acc_0 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_0_new, %loop ]
  %acc_1 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_1_new, %loop ]
  %acc_2 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_2_new, %loop ]
  %acc_3 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_3_new, %loop ]
  %acc_4 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_4_new, %loop ]
  %acc_5 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_5_new, %loop ]
  %acc_6 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_6_new, %loop ]
  %acc_7 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_7_new, %loop ]
  %acc_8 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_8_new, %loop ]
  %acc_9 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_9_new, %loop ]
  %acc_10 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_10_new, %loop ]
  %acc_11 = phi <vscale x 8 x i32> [ zeroinitializer, %entry ], [ %acc_11_new, %loop ]
  %a_iter_ptr = phi ptr [ %a_ptr, %entry ], [ %a_iter_next, %loop ]
  %w_iter_ptr = phi ptr [ %w_ptr, %entry ], [ %w_iter_next, %loop ]
  %scale_iter_ptr = phi ptr [ %scale_ptr, %entry ], [ %scale_iter_next, %loop ]
  %loop_idx = phi i32 [0, %entry], [%loop_next, %loop]
  %w_0_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 0
  %w_0_i8 = load <vscale x 8 x i8>, ptr %w_0_ptr
  %w_0_i16 = sext <vscale x 8 x i8> %w_0_i8 to <vscale x 8 x i16>

  %a_0_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 0
  %a_0_0_ptr = getelementptr i8, ptr %a_0_ptr, i32 0
  %a_0_0_i8 = load i8, ptr %a_0_0_ptr
  %a_0_0_i16 = sext i8 %a_0_0_i8 to i16
  %a_0_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_0_i16, i32 0
  %a_0_0_vsplat = shufflevector <vscale x 8 x i16> %a_0_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_0 = mul <vscale x 8 x i16> %a_0_0_vsplat, %w_0_i16
  %add_0_0 = add <vscale x 8 x i16> %mul_0_0, zeroinitializer
  %a_0_1_ptr = getelementptr i8, ptr %a_0_ptr, i32 1
  %a_0_1_i8 = load i8, ptr %a_0_1_ptr
  %a_0_1_i16 = sext i8 %a_0_1_i8 to i16
  %a_0_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_1_i16, i32 0
  %a_0_1_vsplat = shufflevector <vscale x 8 x i16> %a_0_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_1 = mul <vscale x 8 x i16> %a_0_1_vsplat, %w_0_i16
  %add_0_1 = add <vscale x 8 x i16> %mul_0_1, zeroinitializer
  %a_0_2_ptr = getelementptr i8, ptr %a_0_ptr, i32 2
  %a_0_2_i8 = load i8, ptr %a_0_2_ptr
  %a_0_2_i16 = sext i8 %a_0_2_i8 to i16
  %a_0_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_2_i16, i32 0
  %a_0_2_vsplat = shufflevector <vscale x 8 x i16> %a_0_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_2 = mul <vscale x 8 x i16> %a_0_2_vsplat, %w_0_i16
  %add_0_2 = add <vscale x 8 x i16> %mul_0_2, zeroinitializer
  %a_0_3_ptr = getelementptr i8, ptr %a_0_ptr, i32 3
  %a_0_3_i8 = load i8, ptr %a_0_3_ptr
  %a_0_3_i16 = sext i8 %a_0_3_i8 to i16
  %a_0_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_3_i16, i32 0
  %a_0_3_vsplat = shufflevector <vscale x 8 x i16> %a_0_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_3 = mul <vscale x 8 x i16> %a_0_3_vsplat, %w_0_i16
  %add_0_3 = add <vscale x 8 x i16> %mul_0_3, zeroinitializer
  %a_0_4_ptr = getelementptr i8, ptr %a_0_ptr, i32 4
  %a_0_4_i8 = load i8, ptr %a_0_4_ptr
  %a_0_4_i16 = sext i8 %a_0_4_i8 to i16
  %a_0_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_4_i16, i32 0
  %a_0_4_vsplat = shufflevector <vscale x 8 x i16> %a_0_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_4 = mul <vscale x 8 x i16> %a_0_4_vsplat, %w_0_i16
  %add_0_4 = add <vscale x 8 x i16> %mul_0_4, zeroinitializer
  %a_0_5_ptr = getelementptr i8, ptr %a_0_ptr, i32 5
  %a_0_5_i8 = load i8, ptr %a_0_5_ptr
  %a_0_5_i16 = sext i8 %a_0_5_i8 to i16
  %a_0_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_5_i16, i32 0
  %a_0_5_vsplat = shufflevector <vscale x 8 x i16> %a_0_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_5 = mul <vscale x 8 x i16> %a_0_5_vsplat, %w_0_i16
  %add_0_5 = add <vscale x 8 x i16> %mul_0_5, zeroinitializer
  %a_0_6_ptr = getelementptr i8, ptr %a_0_ptr, i32 6
  %a_0_6_i8 = load i8, ptr %a_0_6_ptr
  %a_0_6_i16 = sext i8 %a_0_6_i8 to i16
  %a_0_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_6_i16, i32 0
  %a_0_6_vsplat = shufflevector <vscale x 8 x i16> %a_0_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_6 = mul <vscale x 8 x i16> %a_0_6_vsplat, %w_0_i16
  %add_0_6 = add <vscale x 8 x i16> %mul_0_6, zeroinitializer
  %a_0_7_ptr = getelementptr i8, ptr %a_0_ptr, i32 7
  %a_0_7_i8 = load i8, ptr %a_0_7_ptr
  %a_0_7_i16 = sext i8 %a_0_7_i8 to i16
  %a_0_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_7_i16, i32 0
  %a_0_7_vsplat = shufflevector <vscale x 8 x i16> %a_0_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_7 = mul <vscale x 8 x i16> %a_0_7_vsplat, %w_0_i16
  %add_0_7 = add <vscale x 8 x i16> %mul_0_7, zeroinitializer
  %a_0_8_ptr = getelementptr i8, ptr %a_0_ptr, i32 8
  %a_0_8_i8 = load i8, ptr %a_0_8_ptr
  %a_0_8_i16 = sext i8 %a_0_8_i8 to i16
  %a_0_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_8_i16, i32 0
  %a_0_8_vsplat = shufflevector <vscale x 8 x i16> %a_0_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_8 = mul <vscale x 8 x i16> %a_0_8_vsplat, %w_0_i16
  %add_0_8 = add <vscale x 8 x i16> %mul_0_8, zeroinitializer
  %a_0_9_ptr = getelementptr i8, ptr %a_0_ptr, i32 9
  %a_0_9_i8 = load i8, ptr %a_0_9_ptr
  %a_0_9_i16 = sext i8 %a_0_9_i8 to i16
  %a_0_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_9_i16, i32 0
  %a_0_9_vsplat = shufflevector <vscale x 8 x i16> %a_0_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_9 = mul <vscale x 8 x i16> %a_0_9_vsplat, %w_0_i16
  %add_0_9 = add <vscale x 8 x i16> %mul_0_9, zeroinitializer
  %a_0_10_ptr = getelementptr i8, ptr %a_0_ptr, i32 10
  %a_0_10_i8 = load i8, ptr %a_0_10_ptr
  %a_0_10_i16 = sext i8 %a_0_10_i8 to i16
  %a_0_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_10_i16, i32 0
  %a_0_10_vsplat = shufflevector <vscale x 8 x i16> %a_0_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_10 = mul <vscale x 8 x i16> %a_0_10_vsplat, %w_0_i16
  %add_0_10 = add <vscale x 8 x i16> %mul_0_10, zeroinitializer
  %a_0_11_ptr = getelementptr i8, ptr %a_0_ptr, i32 11
  %a_0_11_i8 = load i8, ptr %a_0_11_ptr
  %a_0_11_i16 = sext i8 %a_0_11_i8 to i16
  %a_0_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_0_11_i16, i32 0
  %a_0_11_vsplat = shufflevector <vscale x 8 x i16> %a_0_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_0_11 = mul <vscale x 8 x i16> %a_0_11_vsplat, %w_0_i16
  %add_0_11 = add <vscale x 8 x i16> %mul_0_11, zeroinitializer

  %w_1_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 1
  %w_1_i8 = load <vscale x 8 x i8>, ptr %w_1_ptr
  %w_1_i16 = sext <vscale x 8 x i8> %w_1_i8 to <vscale x 8 x i16>

  %a_1_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 1
  %a_1_0_ptr = getelementptr i8, ptr %a_1_ptr, i32 0
  %a_1_0_i8 = load i8, ptr %a_1_0_ptr
  %a_1_0_i16 = sext i8 %a_1_0_i8 to i16
  %a_1_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_0_i16, i32 0
  %a_1_0_vsplat = shufflevector <vscale x 8 x i16> %a_1_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_0 = mul <vscale x 8 x i16> %a_1_0_vsplat, %w_1_i16
  %add_1_0 = add <vscale x 8 x i16> %mul_1_0, %add_0_0
  %a_1_1_ptr = getelementptr i8, ptr %a_1_ptr, i32 1
  %a_1_1_i8 = load i8, ptr %a_1_1_ptr
  %a_1_1_i16 = sext i8 %a_1_1_i8 to i16
  %a_1_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_1_i16, i32 0
  %a_1_1_vsplat = shufflevector <vscale x 8 x i16> %a_1_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_1 = mul <vscale x 8 x i16> %a_1_1_vsplat, %w_1_i16
  %add_1_1 = add <vscale x 8 x i16> %mul_1_1, %add_0_1
  %a_1_2_ptr = getelementptr i8, ptr %a_1_ptr, i32 2
  %a_1_2_i8 = load i8, ptr %a_1_2_ptr
  %a_1_2_i16 = sext i8 %a_1_2_i8 to i16
  %a_1_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_2_i16, i32 0
  %a_1_2_vsplat = shufflevector <vscale x 8 x i16> %a_1_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_2 = mul <vscale x 8 x i16> %a_1_2_vsplat, %w_1_i16
  %add_1_2 = add <vscale x 8 x i16> %mul_1_2, %add_0_2
  %a_1_3_ptr = getelementptr i8, ptr %a_1_ptr, i32 3
  %a_1_3_i8 = load i8, ptr %a_1_3_ptr
  %a_1_3_i16 = sext i8 %a_1_3_i8 to i16
  %a_1_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_3_i16, i32 0
  %a_1_3_vsplat = shufflevector <vscale x 8 x i16> %a_1_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_3 = mul <vscale x 8 x i16> %a_1_3_vsplat, %w_1_i16
  %add_1_3 = add <vscale x 8 x i16> %mul_1_3, %add_0_3
  %a_1_4_ptr = getelementptr i8, ptr %a_1_ptr, i32 4
  %a_1_4_i8 = load i8, ptr %a_1_4_ptr
  %a_1_4_i16 = sext i8 %a_1_4_i8 to i16
  %a_1_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_4_i16, i32 0
  %a_1_4_vsplat = shufflevector <vscale x 8 x i16> %a_1_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_4 = mul <vscale x 8 x i16> %a_1_4_vsplat, %w_1_i16
  %add_1_4 = add <vscale x 8 x i16> %mul_1_4, %add_0_4
  %a_1_5_ptr = getelementptr i8, ptr %a_1_ptr, i32 5
  %a_1_5_i8 = load i8, ptr %a_1_5_ptr
  %a_1_5_i16 = sext i8 %a_1_5_i8 to i16
  %a_1_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_5_i16, i32 0
  %a_1_5_vsplat = shufflevector <vscale x 8 x i16> %a_1_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_5 = mul <vscale x 8 x i16> %a_1_5_vsplat, %w_1_i16
  %add_1_5 = add <vscale x 8 x i16> %mul_1_5, %add_0_5
  %a_1_6_ptr = getelementptr i8, ptr %a_1_ptr, i32 6
  %a_1_6_i8 = load i8, ptr %a_1_6_ptr
  %a_1_6_i16 = sext i8 %a_1_6_i8 to i16
  %a_1_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_6_i16, i32 0
  %a_1_6_vsplat = shufflevector <vscale x 8 x i16> %a_1_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_6 = mul <vscale x 8 x i16> %a_1_6_vsplat, %w_1_i16
  %add_1_6 = add <vscale x 8 x i16> %mul_1_6, %add_0_6
  %a_1_7_ptr = getelementptr i8, ptr %a_1_ptr, i32 7
  %a_1_7_i8 = load i8, ptr %a_1_7_ptr
  %a_1_7_i16 = sext i8 %a_1_7_i8 to i16
  %a_1_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_7_i16, i32 0
  %a_1_7_vsplat = shufflevector <vscale x 8 x i16> %a_1_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_7 = mul <vscale x 8 x i16> %a_1_7_vsplat, %w_1_i16
  %add_1_7 = add <vscale x 8 x i16> %mul_1_7, %add_0_7
  %a_1_8_ptr = getelementptr i8, ptr %a_1_ptr, i32 8
  %a_1_8_i8 = load i8, ptr %a_1_8_ptr
  %a_1_8_i16 = sext i8 %a_1_8_i8 to i16
  %a_1_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_8_i16, i32 0
  %a_1_8_vsplat = shufflevector <vscale x 8 x i16> %a_1_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_8 = mul <vscale x 8 x i16> %a_1_8_vsplat, %w_1_i16
  %add_1_8 = add <vscale x 8 x i16> %mul_1_8, %add_0_8
  %a_1_9_ptr = getelementptr i8, ptr %a_1_ptr, i32 9
  %a_1_9_i8 = load i8, ptr %a_1_9_ptr
  %a_1_9_i16 = sext i8 %a_1_9_i8 to i16
  %a_1_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_9_i16, i32 0
  %a_1_9_vsplat = shufflevector <vscale x 8 x i16> %a_1_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_9 = mul <vscale x 8 x i16> %a_1_9_vsplat, %w_1_i16
  %add_1_9 = add <vscale x 8 x i16> %mul_1_9, %add_0_9
  %a_1_10_ptr = getelementptr i8, ptr %a_1_ptr, i32 10
  %a_1_10_i8 = load i8, ptr %a_1_10_ptr
  %a_1_10_i16 = sext i8 %a_1_10_i8 to i16
  %a_1_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_10_i16, i32 0
  %a_1_10_vsplat = shufflevector <vscale x 8 x i16> %a_1_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_10 = mul <vscale x 8 x i16> %a_1_10_vsplat, %w_1_i16
  %add_1_10 = add <vscale x 8 x i16> %mul_1_10, %add_0_10
  %a_1_11_ptr = getelementptr i8, ptr %a_1_ptr, i32 11
  %a_1_11_i8 = load i8, ptr %a_1_11_ptr
  %a_1_11_i16 = sext i8 %a_1_11_i8 to i16
  %a_1_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_1_11_i16, i32 0
  %a_1_11_vsplat = shufflevector <vscale x 8 x i16> %a_1_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_1_11 = mul <vscale x 8 x i16> %a_1_11_vsplat, %w_1_i16
  %add_1_11 = add <vscale x 8 x i16> %mul_1_11, %add_0_11

  %w_2_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 2
  %w_2_i8 = load <vscale x 8 x i8>, ptr %w_2_ptr
  %w_2_i16 = sext <vscale x 8 x i8> %w_2_i8 to <vscale x 8 x i16>

  %a_2_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 2
  %a_2_0_ptr = getelementptr i8, ptr %a_2_ptr, i32 0
  %a_2_0_i8 = load i8, ptr %a_2_0_ptr
  %a_2_0_i16 = sext i8 %a_2_0_i8 to i16
  %a_2_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_0_i16, i32 0
  %a_2_0_vsplat = shufflevector <vscale x 8 x i16> %a_2_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_0 = mul <vscale x 8 x i16> %a_2_0_vsplat, %w_2_i16
  %add_2_0 = add <vscale x 8 x i16> %mul_2_0, %add_1_0
  %a_2_1_ptr = getelementptr i8, ptr %a_2_ptr, i32 1
  %a_2_1_i8 = load i8, ptr %a_2_1_ptr
  %a_2_1_i16 = sext i8 %a_2_1_i8 to i16
  %a_2_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_1_i16, i32 0
  %a_2_1_vsplat = shufflevector <vscale x 8 x i16> %a_2_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_1 = mul <vscale x 8 x i16> %a_2_1_vsplat, %w_2_i16
  %add_2_1 = add <vscale x 8 x i16> %mul_2_1, %add_1_1
  %a_2_2_ptr = getelementptr i8, ptr %a_2_ptr, i32 2
  %a_2_2_i8 = load i8, ptr %a_2_2_ptr
  %a_2_2_i16 = sext i8 %a_2_2_i8 to i16
  %a_2_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_2_i16, i32 0
  %a_2_2_vsplat = shufflevector <vscale x 8 x i16> %a_2_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_2 = mul <vscale x 8 x i16> %a_2_2_vsplat, %w_2_i16
  %add_2_2 = add <vscale x 8 x i16> %mul_2_2, %add_1_2
  %a_2_3_ptr = getelementptr i8, ptr %a_2_ptr, i32 3
  %a_2_3_i8 = load i8, ptr %a_2_3_ptr
  %a_2_3_i16 = sext i8 %a_2_3_i8 to i16
  %a_2_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_3_i16, i32 0
  %a_2_3_vsplat = shufflevector <vscale x 8 x i16> %a_2_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_3 = mul <vscale x 8 x i16> %a_2_3_vsplat, %w_2_i16
  %add_2_3 = add <vscale x 8 x i16> %mul_2_3, %add_1_3
  %a_2_4_ptr = getelementptr i8, ptr %a_2_ptr, i32 4
  %a_2_4_i8 = load i8, ptr %a_2_4_ptr
  %a_2_4_i16 = sext i8 %a_2_4_i8 to i16
  %a_2_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_4_i16, i32 0
  %a_2_4_vsplat = shufflevector <vscale x 8 x i16> %a_2_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_4 = mul <vscale x 8 x i16> %a_2_4_vsplat, %w_2_i16
  %add_2_4 = add <vscale x 8 x i16> %mul_2_4, %add_1_4
  %a_2_5_ptr = getelementptr i8, ptr %a_2_ptr, i32 5
  %a_2_5_i8 = load i8, ptr %a_2_5_ptr
  %a_2_5_i16 = sext i8 %a_2_5_i8 to i16
  %a_2_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_5_i16, i32 0
  %a_2_5_vsplat = shufflevector <vscale x 8 x i16> %a_2_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_5 = mul <vscale x 8 x i16> %a_2_5_vsplat, %w_2_i16
  %add_2_5 = add <vscale x 8 x i16> %mul_2_5, %add_1_5
  %a_2_6_ptr = getelementptr i8, ptr %a_2_ptr, i32 6
  %a_2_6_i8 = load i8, ptr %a_2_6_ptr
  %a_2_6_i16 = sext i8 %a_2_6_i8 to i16
  %a_2_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_6_i16, i32 0
  %a_2_6_vsplat = shufflevector <vscale x 8 x i16> %a_2_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_6 = mul <vscale x 8 x i16> %a_2_6_vsplat, %w_2_i16
  %add_2_6 = add <vscale x 8 x i16> %mul_2_6, %add_1_6
  %a_2_7_ptr = getelementptr i8, ptr %a_2_ptr, i32 7
  %a_2_7_i8 = load i8, ptr %a_2_7_ptr
  %a_2_7_i16 = sext i8 %a_2_7_i8 to i16
  %a_2_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_7_i16, i32 0
  %a_2_7_vsplat = shufflevector <vscale x 8 x i16> %a_2_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_7 = mul <vscale x 8 x i16> %a_2_7_vsplat, %w_2_i16
  %add_2_7 = add <vscale x 8 x i16> %mul_2_7, %add_1_7
  %a_2_8_ptr = getelementptr i8, ptr %a_2_ptr, i32 8
  %a_2_8_i8 = load i8, ptr %a_2_8_ptr
  %a_2_8_i16 = sext i8 %a_2_8_i8 to i16
  %a_2_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_8_i16, i32 0
  %a_2_8_vsplat = shufflevector <vscale x 8 x i16> %a_2_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_8 = mul <vscale x 8 x i16> %a_2_8_vsplat, %w_2_i16
  %add_2_8 = add <vscale x 8 x i16> %mul_2_8, %add_1_8
  %a_2_9_ptr = getelementptr i8, ptr %a_2_ptr, i32 9
  %a_2_9_i8 = load i8, ptr %a_2_9_ptr
  %a_2_9_i16 = sext i8 %a_2_9_i8 to i16
  %a_2_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_9_i16, i32 0
  %a_2_9_vsplat = shufflevector <vscale x 8 x i16> %a_2_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_9 = mul <vscale x 8 x i16> %a_2_9_vsplat, %w_2_i16
  %add_2_9 = add <vscale x 8 x i16> %mul_2_9, %add_1_9
  %a_2_10_ptr = getelementptr i8, ptr %a_2_ptr, i32 10
  %a_2_10_i8 = load i8, ptr %a_2_10_ptr
  %a_2_10_i16 = sext i8 %a_2_10_i8 to i16
  %a_2_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_10_i16, i32 0
  %a_2_10_vsplat = shufflevector <vscale x 8 x i16> %a_2_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_10 = mul <vscale x 8 x i16> %a_2_10_vsplat, %w_2_i16
  %add_2_10 = add <vscale x 8 x i16> %mul_2_10, %add_1_10
  %a_2_11_ptr = getelementptr i8, ptr %a_2_ptr, i32 11
  %a_2_11_i8 = load i8, ptr %a_2_11_ptr
  %a_2_11_i16 = sext i8 %a_2_11_i8 to i16
  %a_2_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_2_11_i16, i32 0
  %a_2_11_vsplat = shufflevector <vscale x 8 x i16> %a_2_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_2_11 = mul <vscale x 8 x i16> %a_2_11_vsplat, %w_2_i16
  %add_2_11 = add <vscale x 8 x i16> %mul_2_11, %add_1_11

  %w_3_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 3
  %w_3_i8 = load <vscale x 8 x i8>, ptr %w_3_ptr
  %w_3_i16 = sext <vscale x 8 x i8> %w_3_i8 to <vscale x 8 x i16>

  %a_3_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 3
  %a_3_0_ptr = getelementptr i8, ptr %a_3_ptr, i32 0
  %a_3_0_i8 = load i8, ptr %a_3_0_ptr
  %a_3_0_i16 = sext i8 %a_3_0_i8 to i16
  %a_3_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_0_i16, i32 0
  %a_3_0_vsplat = shufflevector <vscale x 8 x i16> %a_3_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_0 = mul <vscale x 8 x i16> %a_3_0_vsplat, %w_3_i16
  %add_3_0 = add <vscale x 8 x i16> %mul_3_0, %add_2_0
  %a_3_1_ptr = getelementptr i8, ptr %a_3_ptr, i32 1
  %a_3_1_i8 = load i8, ptr %a_3_1_ptr
  %a_3_1_i16 = sext i8 %a_3_1_i8 to i16
  %a_3_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_1_i16, i32 0
  %a_3_1_vsplat = shufflevector <vscale x 8 x i16> %a_3_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_1 = mul <vscale x 8 x i16> %a_3_1_vsplat, %w_3_i16
  %add_3_1 = add <vscale x 8 x i16> %mul_3_1, %add_2_1
  %a_3_2_ptr = getelementptr i8, ptr %a_3_ptr, i32 2
  %a_3_2_i8 = load i8, ptr %a_3_2_ptr
  %a_3_2_i16 = sext i8 %a_3_2_i8 to i16
  %a_3_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_2_i16, i32 0
  %a_3_2_vsplat = shufflevector <vscale x 8 x i16> %a_3_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_2 = mul <vscale x 8 x i16> %a_3_2_vsplat, %w_3_i16
  %add_3_2 = add <vscale x 8 x i16> %mul_3_2, %add_2_2
  %a_3_3_ptr = getelementptr i8, ptr %a_3_ptr, i32 3
  %a_3_3_i8 = load i8, ptr %a_3_3_ptr
  %a_3_3_i16 = sext i8 %a_3_3_i8 to i16
  %a_3_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_3_i16, i32 0
  %a_3_3_vsplat = shufflevector <vscale x 8 x i16> %a_3_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_3 = mul <vscale x 8 x i16> %a_3_3_vsplat, %w_3_i16
  %add_3_3 = add <vscale x 8 x i16> %mul_3_3, %add_2_3
  %a_3_4_ptr = getelementptr i8, ptr %a_3_ptr, i32 4
  %a_3_4_i8 = load i8, ptr %a_3_4_ptr
  %a_3_4_i16 = sext i8 %a_3_4_i8 to i16
  %a_3_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_4_i16, i32 0
  %a_3_4_vsplat = shufflevector <vscale x 8 x i16> %a_3_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_4 = mul <vscale x 8 x i16> %a_3_4_vsplat, %w_3_i16
  %add_3_4 = add <vscale x 8 x i16> %mul_3_4, %add_2_4
  %a_3_5_ptr = getelementptr i8, ptr %a_3_ptr, i32 5
  %a_3_5_i8 = load i8, ptr %a_3_5_ptr
  %a_3_5_i16 = sext i8 %a_3_5_i8 to i16
  %a_3_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_5_i16, i32 0
  %a_3_5_vsplat = shufflevector <vscale x 8 x i16> %a_3_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_5 = mul <vscale x 8 x i16> %a_3_5_vsplat, %w_3_i16
  %add_3_5 = add <vscale x 8 x i16> %mul_3_5, %add_2_5
  %a_3_6_ptr = getelementptr i8, ptr %a_3_ptr, i32 6
  %a_3_6_i8 = load i8, ptr %a_3_6_ptr
  %a_3_6_i16 = sext i8 %a_3_6_i8 to i16
  %a_3_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_6_i16, i32 0
  %a_3_6_vsplat = shufflevector <vscale x 8 x i16> %a_3_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_6 = mul <vscale x 8 x i16> %a_3_6_vsplat, %w_3_i16
  %add_3_6 = add <vscale x 8 x i16> %mul_3_6, %add_2_6
  %a_3_7_ptr = getelementptr i8, ptr %a_3_ptr, i32 7
  %a_3_7_i8 = load i8, ptr %a_3_7_ptr
  %a_3_7_i16 = sext i8 %a_3_7_i8 to i16
  %a_3_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_7_i16, i32 0
  %a_3_7_vsplat = shufflevector <vscale x 8 x i16> %a_3_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_7 = mul <vscale x 8 x i16> %a_3_7_vsplat, %w_3_i16
  %add_3_7 = add <vscale x 8 x i16> %mul_3_7, %add_2_7
  %a_3_8_ptr = getelementptr i8, ptr %a_3_ptr, i32 8
  %a_3_8_i8 = load i8, ptr %a_3_8_ptr
  %a_3_8_i16 = sext i8 %a_3_8_i8 to i16
  %a_3_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_8_i16, i32 0
  %a_3_8_vsplat = shufflevector <vscale x 8 x i16> %a_3_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_8 = mul <vscale x 8 x i16> %a_3_8_vsplat, %w_3_i16
  %add_3_8 = add <vscale x 8 x i16> %mul_3_8, %add_2_8
  %a_3_9_ptr = getelementptr i8, ptr %a_3_ptr, i32 9
  %a_3_9_i8 = load i8, ptr %a_3_9_ptr
  %a_3_9_i16 = sext i8 %a_3_9_i8 to i16
  %a_3_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_9_i16, i32 0
  %a_3_9_vsplat = shufflevector <vscale x 8 x i16> %a_3_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_9 = mul <vscale x 8 x i16> %a_3_9_vsplat, %w_3_i16
  %add_3_9 = add <vscale x 8 x i16> %mul_3_9, %add_2_9
  %a_3_10_ptr = getelementptr i8, ptr %a_3_ptr, i32 10
  %a_3_10_i8 = load i8, ptr %a_3_10_ptr
  %a_3_10_i16 = sext i8 %a_3_10_i8 to i16
  %a_3_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_10_i16, i32 0
  %a_3_10_vsplat = shufflevector <vscale x 8 x i16> %a_3_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_10 = mul <vscale x 8 x i16> %a_3_10_vsplat, %w_3_i16
  %add_3_10 = add <vscale x 8 x i16> %mul_3_10, %add_2_10
  %a_3_11_ptr = getelementptr i8, ptr %a_3_ptr, i32 11
  %a_3_11_i8 = load i8, ptr %a_3_11_ptr
  %a_3_11_i16 = sext i8 %a_3_11_i8 to i16
  %a_3_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_3_11_i16, i32 0
  %a_3_11_vsplat = shufflevector <vscale x 8 x i16> %a_3_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_3_11 = mul <vscale x 8 x i16> %a_3_11_vsplat, %w_3_i16
  %add_3_11 = add <vscale x 8 x i16> %mul_3_11, %add_2_11

  %w_4_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 4
  %w_4_i8 = load <vscale x 8 x i8>, ptr %w_4_ptr
  %w_4_i16 = sext <vscale x 8 x i8> %w_4_i8 to <vscale x 8 x i16>

  %a_4_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 4
  %a_4_0_ptr = getelementptr i8, ptr %a_4_ptr, i32 0
  %a_4_0_i8 = load i8, ptr %a_4_0_ptr
  %a_4_0_i16 = sext i8 %a_4_0_i8 to i16
  %a_4_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_0_i16, i32 0
  %a_4_0_vsplat = shufflevector <vscale x 8 x i16> %a_4_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_0 = mul <vscale x 8 x i16> %a_4_0_vsplat, %w_4_i16
  %add_4_0 = add <vscale x 8 x i16> %mul_4_0, %add_3_0
  %a_4_1_ptr = getelementptr i8, ptr %a_4_ptr, i32 1
  %a_4_1_i8 = load i8, ptr %a_4_1_ptr
  %a_4_1_i16 = sext i8 %a_4_1_i8 to i16
  %a_4_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_1_i16, i32 0
  %a_4_1_vsplat = shufflevector <vscale x 8 x i16> %a_4_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_1 = mul <vscale x 8 x i16> %a_4_1_vsplat, %w_4_i16
  %add_4_1 = add <vscale x 8 x i16> %mul_4_1, %add_3_1
  %a_4_2_ptr = getelementptr i8, ptr %a_4_ptr, i32 2
  %a_4_2_i8 = load i8, ptr %a_4_2_ptr
  %a_4_2_i16 = sext i8 %a_4_2_i8 to i16
  %a_4_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_2_i16, i32 0
  %a_4_2_vsplat = shufflevector <vscale x 8 x i16> %a_4_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_2 = mul <vscale x 8 x i16> %a_4_2_vsplat, %w_4_i16
  %add_4_2 = add <vscale x 8 x i16> %mul_4_2, %add_3_2
  %a_4_3_ptr = getelementptr i8, ptr %a_4_ptr, i32 3
  %a_4_3_i8 = load i8, ptr %a_4_3_ptr
  %a_4_3_i16 = sext i8 %a_4_3_i8 to i16
  %a_4_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_3_i16, i32 0
  %a_4_3_vsplat = shufflevector <vscale x 8 x i16> %a_4_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_3 = mul <vscale x 8 x i16> %a_4_3_vsplat, %w_4_i16
  %add_4_3 = add <vscale x 8 x i16> %mul_4_3, %add_3_3
  %a_4_4_ptr = getelementptr i8, ptr %a_4_ptr, i32 4
  %a_4_4_i8 = load i8, ptr %a_4_4_ptr
  %a_4_4_i16 = sext i8 %a_4_4_i8 to i16
  %a_4_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_4_i16, i32 0
  %a_4_4_vsplat = shufflevector <vscale x 8 x i16> %a_4_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_4 = mul <vscale x 8 x i16> %a_4_4_vsplat, %w_4_i16
  %add_4_4 = add <vscale x 8 x i16> %mul_4_4, %add_3_4
  %a_4_5_ptr = getelementptr i8, ptr %a_4_ptr, i32 5
  %a_4_5_i8 = load i8, ptr %a_4_5_ptr
  %a_4_5_i16 = sext i8 %a_4_5_i8 to i16
  %a_4_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_5_i16, i32 0
  %a_4_5_vsplat = shufflevector <vscale x 8 x i16> %a_4_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_5 = mul <vscale x 8 x i16> %a_4_5_vsplat, %w_4_i16
  %add_4_5 = add <vscale x 8 x i16> %mul_4_5, %add_3_5
  %a_4_6_ptr = getelementptr i8, ptr %a_4_ptr, i32 6
  %a_4_6_i8 = load i8, ptr %a_4_6_ptr
  %a_4_6_i16 = sext i8 %a_4_6_i8 to i16
  %a_4_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_6_i16, i32 0
  %a_4_6_vsplat = shufflevector <vscale x 8 x i16> %a_4_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_6 = mul <vscale x 8 x i16> %a_4_6_vsplat, %w_4_i16
  %add_4_6 = add <vscale x 8 x i16> %mul_4_6, %add_3_6
  %a_4_7_ptr = getelementptr i8, ptr %a_4_ptr, i32 7
  %a_4_7_i8 = load i8, ptr %a_4_7_ptr
  %a_4_7_i16 = sext i8 %a_4_7_i8 to i16
  %a_4_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_7_i16, i32 0
  %a_4_7_vsplat = shufflevector <vscale x 8 x i16> %a_4_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_7 = mul <vscale x 8 x i16> %a_4_7_vsplat, %w_4_i16
  %add_4_7 = add <vscale x 8 x i16> %mul_4_7, %add_3_7
  %a_4_8_ptr = getelementptr i8, ptr %a_4_ptr, i32 8
  %a_4_8_i8 = load i8, ptr %a_4_8_ptr
  %a_4_8_i16 = sext i8 %a_4_8_i8 to i16
  %a_4_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_8_i16, i32 0
  %a_4_8_vsplat = shufflevector <vscale x 8 x i16> %a_4_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_8 = mul <vscale x 8 x i16> %a_4_8_vsplat, %w_4_i16
  %add_4_8 = add <vscale x 8 x i16> %mul_4_8, %add_3_8
  %a_4_9_ptr = getelementptr i8, ptr %a_4_ptr, i32 9
  %a_4_9_i8 = load i8, ptr %a_4_9_ptr
  %a_4_9_i16 = sext i8 %a_4_9_i8 to i16
  %a_4_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_9_i16, i32 0
  %a_4_9_vsplat = shufflevector <vscale x 8 x i16> %a_4_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_9 = mul <vscale x 8 x i16> %a_4_9_vsplat, %w_4_i16
  %add_4_9 = add <vscale x 8 x i16> %mul_4_9, %add_3_9
  %a_4_10_ptr = getelementptr i8, ptr %a_4_ptr, i32 10
  %a_4_10_i8 = load i8, ptr %a_4_10_ptr
  %a_4_10_i16 = sext i8 %a_4_10_i8 to i16
  %a_4_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_10_i16, i32 0
  %a_4_10_vsplat = shufflevector <vscale x 8 x i16> %a_4_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_10 = mul <vscale x 8 x i16> %a_4_10_vsplat, %w_4_i16
  %add_4_10 = add <vscale x 8 x i16> %mul_4_10, %add_3_10
  %a_4_11_ptr = getelementptr i8, ptr %a_4_ptr, i32 11
  %a_4_11_i8 = load i8, ptr %a_4_11_ptr
  %a_4_11_i16 = sext i8 %a_4_11_i8 to i16
  %a_4_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_4_11_i16, i32 0
  %a_4_11_vsplat = shufflevector <vscale x 8 x i16> %a_4_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_4_11 = mul <vscale x 8 x i16> %a_4_11_vsplat, %w_4_i16
  %add_4_11 = add <vscale x 8 x i16> %mul_4_11, %add_3_11

  %w_5_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 5
  %w_5_i8 = load <vscale x 8 x i8>, ptr %w_5_ptr
  %w_5_i16 = sext <vscale x 8 x i8> %w_5_i8 to <vscale x 8 x i16>

  %a_5_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 5
  %a_5_0_ptr = getelementptr i8, ptr %a_5_ptr, i32 0
  %a_5_0_i8 = load i8, ptr %a_5_0_ptr
  %a_5_0_i16 = sext i8 %a_5_0_i8 to i16
  %a_5_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_0_i16, i32 0
  %a_5_0_vsplat = shufflevector <vscale x 8 x i16> %a_5_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_0 = mul <vscale x 8 x i16> %a_5_0_vsplat, %w_5_i16
  %add_5_0 = add <vscale x 8 x i16> %mul_5_0, %add_4_0
  %a_5_1_ptr = getelementptr i8, ptr %a_5_ptr, i32 1
  %a_5_1_i8 = load i8, ptr %a_5_1_ptr
  %a_5_1_i16 = sext i8 %a_5_1_i8 to i16
  %a_5_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_1_i16, i32 0
  %a_5_1_vsplat = shufflevector <vscale x 8 x i16> %a_5_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_1 = mul <vscale x 8 x i16> %a_5_1_vsplat, %w_5_i16
  %add_5_1 = add <vscale x 8 x i16> %mul_5_1, %add_4_1
  %a_5_2_ptr = getelementptr i8, ptr %a_5_ptr, i32 2
  %a_5_2_i8 = load i8, ptr %a_5_2_ptr
  %a_5_2_i16 = sext i8 %a_5_2_i8 to i16
  %a_5_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_2_i16, i32 0
  %a_5_2_vsplat = shufflevector <vscale x 8 x i16> %a_5_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_2 = mul <vscale x 8 x i16> %a_5_2_vsplat, %w_5_i16
  %add_5_2 = add <vscale x 8 x i16> %mul_5_2, %add_4_2
  %a_5_3_ptr = getelementptr i8, ptr %a_5_ptr, i32 3
  %a_5_3_i8 = load i8, ptr %a_5_3_ptr
  %a_5_3_i16 = sext i8 %a_5_3_i8 to i16
  %a_5_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_3_i16, i32 0
  %a_5_3_vsplat = shufflevector <vscale x 8 x i16> %a_5_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_3 = mul <vscale x 8 x i16> %a_5_3_vsplat, %w_5_i16
  %add_5_3 = add <vscale x 8 x i16> %mul_5_3, %add_4_3
  %a_5_4_ptr = getelementptr i8, ptr %a_5_ptr, i32 4
  %a_5_4_i8 = load i8, ptr %a_5_4_ptr
  %a_5_4_i16 = sext i8 %a_5_4_i8 to i16
  %a_5_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_4_i16, i32 0
  %a_5_4_vsplat = shufflevector <vscale x 8 x i16> %a_5_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_4 = mul <vscale x 8 x i16> %a_5_4_vsplat, %w_5_i16
  %add_5_4 = add <vscale x 8 x i16> %mul_5_4, %add_4_4
  %a_5_5_ptr = getelementptr i8, ptr %a_5_ptr, i32 5
  %a_5_5_i8 = load i8, ptr %a_5_5_ptr
  %a_5_5_i16 = sext i8 %a_5_5_i8 to i16
  %a_5_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_5_i16, i32 0
  %a_5_5_vsplat = shufflevector <vscale x 8 x i16> %a_5_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_5 = mul <vscale x 8 x i16> %a_5_5_vsplat, %w_5_i16
  %add_5_5 = add <vscale x 8 x i16> %mul_5_5, %add_4_5
  %a_5_6_ptr = getelementptr i8, ptr %a_5_ptr, i32 6
  %a_5_6_i8 = load i8, ptr %a_5_6_ptr
  %a_5_6_i16 = sext i8 %a_5_6_i8 to i16
  %a_5_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_6_i16, i32 0
  %a_5_6_vsplat = shufflevector <vscale x 8 x i16> %a_5_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_6 = mul <vscale x 8 x i16> %a_5_6_vsplat, %w_5_i16
  %add_5_6 = add <vscale x 8 x i16> %mul_5_6, %add_4_6
  %a_5_7_ptr = getelementptr i8, ptr %a_5_ptr, i32 7
  %a_5_7_i8 = load i8, ptr %a_5_7_ptr
  %a_5_7_i16 = sext i8 %a_5_7_i8 to i16
  %a_5_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_7_i16, i32 0
  %a_5_7_vsplat = shufflevector <vscale x 8 x i16> %a_5_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_7 = mul <vscale x 8 x i16> %a_5_7_vsplat, %w_5_i16
  %add_5_7 = add <vscale x 8 x i16> %mul_5_7, %add_4_7
  %a_5_8_ptr = getelementptr i8, ptr %a_5_ptr, i32 8
  %a_5_8_i8 = load i8, ptr %a_5_8_ptr
  %a_5_8_i16 = sext i8 %a_5_8_i8 to i16
  %a_5_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_8_i16, i32 0
  %a_5_8_vsplat = shufflevector <vscale x 8 x i16> %a_5_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_8 = mul <vscale x 8 x i16> %a_5_8_vsplat, %w_5_i16
  %add_5_8 = add <vscale x 8 x i16> %mul_5_8, %add_4_8
  %a_5_9_ptr = getelementptr i8, ptr %a_5_ptr, i32 9
  %a_5_9_i8 = load i8, ptr %a_5_9_ptr
  %a_5_9_i16 = sext i8 %a_5_9_i8 to i16
  %a_5_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_9_i16, i32 0
  %a_5_9_vsplat = shufflevector <vscale x 8 x i16> %a_5_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_9 = mul <vscale x 8 x i16> %a_5_9_vsplat, %w_5_i16
  %add_5_9 = add <vscale x 8 x i16> %mul_5_9, %add_4_9
  %a_5_10_ptr = getelementptr i8, ptr %a_5_ptr, i32 10
  %a_5_10_i8 = load i8, ptr %a_5_10_ptr
  %a_5_10_i16 = sext i8 %a_5_10_i8 to i16
  %a_5_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_10_i16, i32 0
  %a_5_10_vsplat = shufflevector <vscale x 8 x i16> %a_5_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_10 = mul <vscale x 8 x i16> %a_5_10_vsplat, %w_5_i16
  %add_5_10 = add <vscale x 8 x i16> %mul_5_10, %add_4_10
  %a_5_11_ptr = getelementptr i8, ptr %a_5_ptr, i32 11
  %a_5_11_i8 = load i8, ptr %a_5_11_ptr
  %a_5_11_i16 = sext i8 %a_5_11_i8 to i16
  %a_5_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_5_11_i16, i32 0
  %a_5_11_vsplat = shufflevector <vscale x 8 x i16> %a_5_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_5_11 = mul <vscale x 8 x i16> %a_5_11_vsplat, %w_5_i16
  %add_5_11 = add <vscale x 8 x i16> %mul_5_11, %add_4_11

  %w_6_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 6
  %w_6_i8 = load <vscale x 8 x i8>, ptr %w_6_ptr
  %w_6_i16 = sext <vscale x 8 x i8> %w_6_i8 to <vscale x 8 x i16>

  %a_6_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 6
  %a_6_0_ptr = getelementptr i8, ptr %a_6_ptr, i32 0
  %a_6_0_i8 = load i8, ptr %a_6_0_ptr
  %a_6_0_i16 = sext i8 %a_6_0_i8 to i16
  %a_6_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_0_i16, i32 0
  %a_6_0_vsplat = shufflevector <vscale x 8 x i16> %a_6_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_0 = mul <vscale x 8 x i16> %a_6_0_vsplat, %w_6_i16
  %add_6_0 = add <vscale x 8 x i16> %mul_6_0, %add_5_0
  %a_6_1_ptr = getelementptr i8, ptr %a_6_ptr, i32 1
  %a_6_1_i8 = load i8, ptr %a_6_1_ptr
  %a_6_1_i16 = sext i8 %a_6_1_i8 to i16
  %a_6_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_1_i16, i32 0
  %a_6_1_vsplat = shufflevector <vscale x 8 x i16> %a_6_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_1 = mul <vscale x 8 x i16> %a_6_1_vsplat, %w_6_i16
  %add_6_1 = add <vscale x 8 x i16> %mul_6_1, %add_5_1
  %a_6_2_ptr = getelementptr i8, ptr %a_6_ptr, i32 2
  %a_6_2_i8 = load i8, ptr %a_6_2_ptr
  %a_6_2_i16 = sext i8 %a_6_2_i8 to i16
  %a_6_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_2_i16, i32 0
  %a_6_2_vsplat = shufflevector <vscale x 8 x i16> %a_6_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_2 = mul <vscale x 8 x i16> %a_6_2_vsplat, %w_6_i16
  %add_6_2 = add <vscale x 8 x i16> %mul_6_2, %add_5_2
  %a_6_3_ptr = getelementptr i8, ptr %a_6_ptr, i32 3
  %a_6_3_i8 = load i8, ptr %a_6_3_ptr
  %a_6_3_i16 = sext i8 %a_6_3_i8 to i16
  %a_6_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_3_i16, i32 0
  %a_6_3_vsplat = shufflevector <vscale x 8 x i16> %a_6_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_3 = mul <vscale x 8 x i16> %a_6_3_vsplat, %w_6_i16
  %add_6_3 = add <vscale x 8 x i16> %mul_6_3, %add_5_3
  %a_6_4_ptr = getelementptr i8, ptr %a_6_ptr, i32 4
  %a_6_4_i8 = load i8, ptr %a_6_4_ptr
  %a_6_4_i16 = sext i8 %a_6_4_i8 to i16
  %a_6_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_4_i16, i32 0
  %a_6_4_vsplat = shufflevector <vscale x 8 x i16> %a_6_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_4 = mul <vscale x 8 x i16> %a_6_4_vsplat, %w_6_i16
  %add_6_4 = add <vscale x 8 x i16> %mul_6_4, %add_5_4
  %a_6_5_ptr = getelementptr i8, ptr %a_6_ptr, i32 5
  %a_6_5_i8 = load i8, ptr %a_6_5_ptr
  %a_6_5_i16 = sext i8 %a_6_5_i8 to i16
  %a_6_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_5_i16, i32 0
  %a_6_5_vsplat = shufflevector <vscale x 8 x i16> %a_6_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_5 = mul <vscale x 8 x i16> %a_6_5_vsplat, %w_6_i16
  %add_6_5 = add <vscale x 8 x i16> %mul_6_5, %add_5_5
  %a_6_6_ptr = getelementptr i8, ptr %a_6_ptr, i32 6
  %a_6_6_i8 = load i8, ptr %a_6_6_ptr
  %a_6_6_i16 = sext i8 %a_6_6_i8 to i16
  %a_6_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_6_i16, i32 0
  %a_6_6_vsplat = shufflevector <vscale x 8 x i16> %a_6_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_6 = mul <vscale x 8 x i16> %a_6_6_vsplat, %w_6_i16
  %add_6_6 = add <vscale x 8 x i16> %mul_6_6, %add_5_6
  %a_6_7_ptr = getelementptr i8, ptr %a_6_ptr, i32 7
  %a_6_7_i8 = load i8, ptr %a_6_7_ptr
  %a_6_7_i16 = sext i8 %a_6_7_i8 to i16
  %a_6_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_7_i16, i32 0
  %a_6_7_vsplat = shufflevector <vscale x 8 x i16> %a_6_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_7 = mul <vscale x 8 x i16> %a_6_7_vsplat, %w_6_i16
  %add_6_7 = add <vscale x 8 x i16> %mul_6_7, %add_5_7
  %a_6_8_ptr = getelementptr i8, ptr %a_6_ptr, i32 8
  %a_6_8_i8 = load i8, ptr %a_6_8_ptr
  %a_6_8_i16 = sext i8 %a_6_8_i8 to i16
  %a_6_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_8_i16, i32 0
  %a_6_8_vsplat = shufflevector <vscale x 8 x i16> %a_6_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_8 = mul <vscale x 8 x i16> %a_6_8_vsplat, %w_6_i16
  %add_6_8 = add <vscale x 8 x i16> %mul_6_8, %add_5_8
  %a_6_9_ptr = getelementptr i8, ptr %a_6_ptr, i32 9
  %a_6_9_i8 = load i8, ptr %a_6_9_ptr
  %a_6_9_i16 = sext i8 %a_6_9_i8 to i16
  %a_6_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_9_i16, i32 0
  %a_6_9_vsplat = shufflevector <vscale x 8 x i16> %a_6_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_9 = mul <vscale x 8 x i16> %a_6_9_vsplat, %w_6_i16
  %add_6_9 = add <vscale x 8 x i16> %mul_6_9, %add_5_9
  %a_6_10_ptr = getelementptr i8, ptr %a_6_ptr, i32 10
  %a_6_10_i8 = load i8, ptr %a_6_10_ptr
  %a_6_10_i16 = sext i8 %a_6_10_i8 to i16
  %a_6_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_10_i16, i32 0
  %a_6_10_vsplat = shufflevector <vscale x 8 x i16> %a_6_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_10 = mul <vscale x 8 x i16> %a_6_10_vsplat, %w_6_i16
  %add_6_10 = add <vscale x 8 x i16> %mul_6_10, %add_5_10
  %a_6_11_ptr = getelementptr i8, ptr %a_6_ptr, i32 11
  %a_6_11_i8 = load i8, ptr %a_6_11_ptr
  %a_6_11_i16 = sext i8 %a_6_11_i8 to i16
  %a_6_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_6_11_i16, i32 0
  %a_6_11_vsplat = shufflevector <vscale x 8 x i16> %a_6_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_6_11 = mul <vscale x 8 x i16> %a_6_11_vsplat, %w_6_i16
  %add_6_11 = add <vscale x 8 x i16> %mul_6_11, %add_5_11

  %w_7_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 7
  %w_7_i8 = load <vscale x 8 x i8>, ptr %w_7_ptr
  %w_7_i16 = sext <vscale x 8 x i8> %w_7_i8 to <vscale x 8 x i16>

  %a_7_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 7
  %a_7_0_ptr = getelementptr i8, ptr %a_7_ptr, i32 0
  %a_7_0_i8 = load i8, ptr %a_7_0_ptr
  %a_7_0_i16 = sext i8 %a_7_0_i8 to i16
  %a_7_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_0_i16, i32 0
  %a_7_0_vsplat = shufflevector <vscale x 8 x i16> %a_7_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_0 = mul <vscale x 8 x i16> %a_7_0_vsplat, %w_7_i16
  %add_7_0 = add <vscale x 8 x i16> %mul_7_0, %add_6_0
  %a_7_1_ptr = getelementptr i8, ptr %a_7_ptr, i32 1
  %a_7_1_i8 = load i8, ptr %a_7_1_ptr
  %a_7_1_i16 = sext i8 %a_7_1_i8 to i16
  %a_7_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_1_i16, i32 0
  %a_7_1_vsplat = shufflevector <vscale x 8 x i16> %a_7_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_1 = mul <vscale x 8 x i16> %a_7_1_vsplat, %w_7_i16
  %add_7_1 = add <vscale x 8 x i16> %mul_7_1, %add_6_1
  %a_7_2_ptr = getelementptr i8, ptr %a_7_ptr, i32 2
  %a_7_2_i8 = load i8, ptr %a_7_2_ptr
  %a_7_2_i16 = sext i8 %a_7_2_i8 to i16
  %a_7_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_2_i16, i32 0
  %a_7_2_vsplat = shufflevector <vscale x 8 x i16> %a_7_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_2 = mul <vscale x 8 x i16> %a_7_2_vsplat, %w_7_i16
  %add_7_2 = add <vscale x 8 x i16> %mul_7_2, %add_6_2
  %a_7_3_ptr = getelementptr i8, ptr %a_7_ptr, i32 3
  %a_7_3_i8 = load i8, ptr %a_7_3_ptr
  %a_7_3_i16 = sext i8 %a_7_3_i8 to i16
  %a_7_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_3_i16, i32 0
  %a_7_3_vsplat = shufflevector <vscale x 8 x i16> %a_7_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_3 = mul <vscale x 8 x i16> %a_7_3_vsplat, %w_7_i16
  %add_7_3 = add <vscale x 8 x i16> %mul_7_3, %add_6_3
  %a_7_4_ptr = getelementptr i8, ptr %a_7_ptr, i32 4
  %a_7_4_i8 = load i8, ptr %a_7_4_ptr
  %a_7_4_i16 = sext i8 %a_7_4_i8 to i16
  %a_7_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_4_i16, i32 0
  %a_7_4_vsplat = shufflevector <vscale x 8 x i16> %a_7_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_4 = mul <vscale x 8 x i16> %a_7_4_vsplat, %w_7_i16
  %add_7_4 = add <vscale x 8 x i16> %mul_7_4, %add_6_4
  %a_7_5_ptr = getelementptr i8, ptr %a_7_ptr, i32 5
  %a_7_5_i8 = load i8, ptr %a_7_5_ptr
  %a_7_5_i16 = sext i8 %a_7_5_i8 to i16
  %a_7_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_5_i16, i32 0
  %a_7_5_vsplat = shufflevector <vscale x 8 x i16> %a_7_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_5 = mul <vscale x 8 x i16> %a_7_5_vsplat, %w_7_i16
  %add_7_5 = add <vscale x 8 x i16> %mul_7_5, %add_6_5
  %a_7_6_ptr = getelementptr i8, ptr %a_7_ptr, i32 6
  %a_7_6_i8 = load i8, ptr %a_7_6_ptr
  %a_7_6_i16 = sext i8 %a_7_6_i8 to i16
  %a_7_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_6_i16, i32 0
  %a_7_6_vsplat = shufflevector <vscale x 8 x i16> %a_7_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_6 = mul <vscale x 8 x i16> %a_7_6_vsplat, %w_7_i16
  %add_7_6 = add <vscale x 8 x i16> %mul_7_6, %add_6_6
  %a_7_7_ptr = getelementptr i8, ptr %a_7_ptr, i32 7
  %a_7_7_i8 = load i8, ptr %a_7_7_ptr
  %a_7_7_i16 = sext i8 %a_7_7_i8 to i16
  %a_7_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_7_i16, i32 0
  %a_7_7_vsplat = shufflevector <vscale x 8 x i16> %a_7_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_7 = mul <vscale x 8 x i16> %a_7_7_vsplat, %w_7_i16
  %add_7_7 = add <vscale x 8 x i16> %mul_7_7, %add_6_7
  %a_7_8_ptr = getelementptr i8, ptr %a_7_ptr, i32 8
  %a_7_8_i8 = load i8, ptr %a_7_8_ptr
  %a_7_8_i16 = sext i8 %a_7_8_i8 to i16
  %a_7_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_8_i16, i32 0
  %a_7_8_vsplat = shufflevector <vscale x 8 x i16> %a_7_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_8 = mul <vscale x 8 x i16> %a_7_8_vsplat, %w_7_i16
  %add_7_8 = add <vscale x 8 x i16> %mul_7_8, %add_6_8
  %a_7_9_ptr = getelementptr i8, ptr %a_7_ptr, i32 9
  %a_7_9_i8 = load i8, ptr %a_7_9_ptr
  %a_7_9_i16 = sext i8 %a_7_9_i8 to i16
  %a_7_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_9_i16, i32 0
  %a_7_9_vsplat = shufflevector <vscale x 8 x i16> %a_7_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_9 = mul <vscale x 8 x i16> %a_7_9_vsplat, %w_7_i16
  %add_7_9 = add <vscale x 8 x i16> %mul_7_9, %add_6_9
  %a_7_10_ptr = getelementptr i8, ptr %a_7_ptr, i32 10
  %a_7_10_i8 = load i8, ptr %a_7_10_ptr
  %a_7_10_i16 = sext i8 %a_7_10_i8 to i16
  %a_7_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_10_i16, i32 0
  %a_7_10_vsplat = shufflevector <vscale x 8 x i16> %a_7_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_10 = mul <vscale x 8 x i16> %a_7_10_vsplat, %w_7_i16
  %add_7_10 = add <vscale x 8 x i16> %mul_7_10, %add_6_10
  %a_7_11_ptr = getelementptr i8, ptr %a_7_ptr, i32 11
  %a_7_11_i8 = load i8, ptr %a_7_11_ptr
  %a_7_11_i16 = sext i8 %a_7_11_i8 to i16
  %a_7_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_7_11_i16, i32 0
  %a_7_11_vsplat = shufflevector <vscale x 8 x i16> %a_7_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_7_11 = mul <vscale x 8 x i16> %a_7_11_vsplat, %w_7_i16
  %add_7_11 = add <vscale x 8 x i16> %mul_7_11, %add_6_11

  %w_8_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 8
  %w_8_i8 = load <vscale x 8 x i8>, ptr %w_8_ptr
  %w_8_i16 = sext <vscale x 8 x i8> %w_8_i8 to <vscale x 8 x i16>

  %a_8_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 8
  %a_8_0_ptr = getelementptr i8, ptr %a_8_ptr, i32 0
  %a_8_0_i8 = load i8, ptr %a_8_0_ptr
  %a_8_0_i16 = sext i8 %a_8_0_i8 to i16
  %a_8_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_0_i16, i32 0
  %a_8_0_vsplat = shufflevector <vscale x 8 x i16> %a_8_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_0 = mul <vscale x 8 x i16> %a_8_0_vsplat, %w_8_i16
  %add_8_0 = add <vscale x 8 x i16> %mul_8_0, %add_7_0
  %a_8_1_ptr = getelementptr i8, ptr %a_8_ptr, i32 1
  %a_8_1_i8 = load i8, ptr %a_8_1_ptr
  %a_8_1_i16 = sext i8 %a_8_1_i8 to i16
  %a_8_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_1_i16, i32 0
  %a_8_1_vsplat = shufflevector <vscale x 8 x i16> %a_8_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_1 = mul <vscale x 8 x i16> %a_8_1_vsplat, %w_8_i16
  %add_8_1 = add <vscale x 8 x i16> %mul_8_1, %add_7_1
  %a_8_2_ptr = getelementptr i8, ptr %a_8_ptr, i32 2
  %a_8_2_i8 = load i8, ptr %a_8_2_ptr
  %a_8_2_i16 = sext i8 %a_8_2_i8 to i16
  %a_8_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_2_i16, i32 0
  %a_8_2_vsplat = shufflevector <vscale x 8 x i16> %a_8_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_2 = mul <vscale x 8 x i16> %a_8_2_vsplat, %w_8_i16
  %add_8_2 = add <vscale x 8 x i16> %mul_8_2, %add_7_2
  %a_8_3_ptr = getelementptr i8, ptr %a_8_ptr, i32 3
  %a_8_3_i8 = load i8, ptr %a_8_3_ptr
  %a_8_3_i16 = sext i8 %a_8_3_i8 to i16
  %a_8_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_3_i16, i32 0
  %a_8_3_vsplat = shufflevector <vscale x 8 x i16> %a_8_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_3 = mul <vscale x 8 x i16> %a_8_3_vsplat, %w_8_i16
  %add_8_3 = add <vscale x 8 x i16> %mul_8_3, %add_7_3
  %a_8_4_ptr = getelementptr i8, ptr %a_8_ptr, i32 4
  %a_8_4_i8 = load i8, ptr %a_8_4_ptr
  %a_8_4_i16 = sext i8 %a_8_4_i8 to i16
  %a_8_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_4_i16, i32 0
  %a_8_4_vsplat = shufflevector <vscale x 8 x i16> %a_8_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_4 = mul <vscale x 8 x i16> %a_8_4_vsplat, %w_8_i16
  %add_8_4 = add <vscale x 8 x i16> %mul_8_4, %add_7_4
  %a_8_5_ptr = getelementptr i8, ptr %a_8_ptr, i32 5
  %a_8_5_i8 = load i8, ptr %a_8_5_ptr
  %a_8_5_i16 = sext i8 %a_8_5_i8 to i16
  %a_8_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_5_i16, i32 0
  %a_8_5_vsplat = shufflevector <vscale x 8 x i16> %a_8_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_5 = mul <vscale x 8 x i16> %a_8_5_vsplat, %w_8_i16
  %add_8_5 = add <vscale x 8 x i16> %mul_8_5, %add_7_5
  %a_8_6_ptr = getelementptr i8, ptr %a_8_ptr, i32 6
  %a_8_6_i8 = load i8, ptr %a_8_6_ptr
  %a_8_6_i16 = sext i8 %a_8_6_i8 to i16
  %a_8_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_6_i16, i32 0
  %a_8_6_vsplat = shufflevector <vscale x 8 x i16> %a_8_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_6 = mul <vscale x 8 x i16> %a_8_6_vsplat, %w_8_i16
  %add_8_6 = add <vscale x 8 x i16> %mul_8_6, %add_7_6
  %a_8_7_ptr = getelementptr i8, ptr %a_8_ptr, i32 7
  %a_8_7_i8 = load i8, ptr %a_8_7_ptr
  %a_8_7_i16 = sext i8 %a_8_7_i8 to i16
  %a_8_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_7_i16, i32 0
  %a_8_7_vsplat = shufflevector <vscale x 8 x i16> %a_8_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_7 = mul <vscale x 8 x i16> %a_8_7_vsplat, %w_8_i16
  %add_8_7 = add <vscale x 8 x i16> %mul_8_7, %add_7_7
  %a_8_8_ptr = getelementptr i8, ptr %a_8_ptr, i32 8
  %a_8_8_i8 = load i8, ptr %a_8_8_ptr
  %a_8_8_i16 = sext i8 %a_8_8_i8 to i16
  %a_8_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_8_i16, i32 0
  %a_8_8_vsplat = shufflevector <vscale x 8 x i16> %a_8_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_8 = mul <vscale x 8 x i16> %a_8_8_vsplat, %w_8_i16
  %add_8_8 = add <vscale x 8 x i16> %mul_8_8, %add_7_8
  %a_8_9_ptr = getelementptr i8, ptr %a_8_ptr, i32 9
  %a_8_9_i8 = load i8, ptr %a_8_9_ptr
  %a_8_9_i16 = sext i8 %a_8_9_i8 to i16
  %a_8_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_9_i16, i32 0
  %a_8_9_vsplat = shufflevector <vscale x 8 x i16> %a_8_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_9 = mul <vscale x 8 x i16> %a_8_9_vsplat, %w_8_i16
  %add_8_9 = add <vscale x 8 x i16> %mul_8_9, %add_7_9
  %a_8_10_ptr = getelementptr i8, ptr %a_8_ptr, i32 10
  %a_8_10_i8 = load i8, ptr %a_8_10_ptr
  %a_8_10_i16 = sext i8 %a_8_10_i8 to i16
  %a_8_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_10_i16, i32 0
  %a_8_10_vsplat = shufflevector <vscale x 8 x i16> %a_8_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_10 = mul <vscale x 8 x i16> %a_8_10_vsplat, %w_8_i16
  %add_8_10 = add <vscale x 8 x i16> %mul_8_10, %add_7_10
  %a_8_11_ptr = getelementptr i8, ptr %a_8_ptr, i32 11
  %a_8_11_i8 = load i8, ptr %a_8_11_ptr
  %a_8_11_i16 = sext i8 %a_8_11_i8 to i16
  %a_8_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_8_11_i16, i32 0
  %a_8_11_vsplat = shufflevector <vscale x 8 x i16> %a_8_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_8_11 = mul <vscale x 8 x i16> %a_8_11_vsplat, %w_8_i16
  %add_8_11 = add <vscale x 8 x i16> %mul_8_11, %add_7_11

  %w_9_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 9
  %w_9_i8 = load <vscale x 8 x i8>, ptr %w_9_ptr
  %w_9_i16 = sext <vscale x 8 x i8> %w_9_i8 to <vscale x 8 x i16>

  %a_9_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 9
  %a_9_0_ptr = getelementptr i8, ptr %a_9_ptr, i32 0
  %a_9_0_i8 = load i8, ptr %a_9_0_ptr
  %a_9_0_i16 = sext i8 %a_9_0_i8 to i16
  %a_9_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_0_i16, i32 0
  %a_9_0_vsplat = shufflevector <vscale x 8 x i16> %a_9_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_0 = mul <vscale x 8 x i16> %a_9_0_vsplat, %w_9_i16
  %add_9_0 = add <vscale x 8 x i16> %mul_9_0, %add_8_0
  %a_9_1_ptr = getelementptr i8, ptr %a_9_ptr, i32 1
  %a_9_1_i8 = load i8, ptr %a_9_1_ptr
  %a_9_1_i16 = sext i8 %a_9_1_i8 to i16
  %a_9_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_1_i16, i32 0
  %a_9_1_vsplat = shufflevector <vscale x 8 x i16> %a_9_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_1 = mul <vscale x 8 x i16> %a_9_1_vsplat, %w_9_i16
  %add_9_1 = add <vscale x 8 x i16> %mul_9_1, %add_8_1
  %a_9_2_ptr = getelementptr i8, ptr %a_9_ptr, i32 2
  %a_9_2_i8 = load i8, ptr %a_9_2_ptr
  %a_9_2_i16 = sext i8 %a_9_2_i8 to i16
  %a_9_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_2_i16, i32 0
  %a_9_2_vsplat = shufflevector <vscale x 8 x i16> %a_9_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_2 = mul <vscale x 8 x i16> %a_9_2_vsplat, %w_9_i16
  %add_9_2 = add <vscale x 8 x i16> %mul_9_2, %add_8_2
  %a_9_3_ptr = getelementptr i8, ptr %a_9_ptr, i32 3
  %a_9_3_i8 = load i8, ptr %a_9_3_ptr
  %a_9_3_i16 = sext i8 %a_9_3_i8 to i16
  %a_9_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_3_i16, i32 0
  %a_9_3_vsplat = shufflevector <vscale x 8 x i16> %a_9_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_3 = mul <vscale x 8 x i16> %a_9_3_vsplat, %w_9_i16
  %add_9_3 = add <vscale x 8 x i16> %mul_9_3, %add_8_3
  %a_9_4_ptr = getelementptr i8, ptr %a_9_ptr, i32 4
  %a_9_4_i8 = load i8, ptr %a_9_4_ptr
  %a_9_4_i16 = sext i8 %a_9_4_i8 to i16
  %a_9_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_4_i16, i32 0
  %a_9_4_vsplat = shufflevector <vscale x 8 x i16> %a_9_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_4 = mul <vscale x 8 x i16> %a_9_4_vsplat, %w_9_i16
  %add_9_4 = add <vscale x 8 x i16> %mul_9_4, %add_8_4
  %a_9_5_ptr = getelementptr i8, ptr %a_9_ptr, i32 5
  %a_9_5_i8 = load i8, ptr %a_9_5_ptr
  %a_9_5_i16 = sext i8 %a_9_5_i8 to i16
  %a_9_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_5_i16, i32 0
  %a_9_5_vsplat = shufflevector <vscale x 8 x i16> %a_9_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_5 = mul <vscale x 8 x i16> %a_9_5_vsplat, %w_9_i16
  %add_9_5 = add <vscale x 8 x i16> %mul_9_5, %add_8_5
  %a_9_6_ptr = getelementptr i8, ptr %a_9_ptr, i32 6
  %a_9_6_i8 = load i8, ptr %a_9_6_ptr
  %a_9_6_i16 = sext i8 %a_9_6_i8 to i16
  %a_9_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_6_i16, i32 0
  %a_9_6_vsplat = shufflevector <vscale x 8 x i16> %a_9_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_6 = mul <vscale x 8 x i16> %a_9_6_vsplat, %w_9_i16
  %add_9_6 = add <vscale x 8 x i16> %mul_9_6, %add_8_6
  %a_9_7_ptr = getelementptr i8, ptr %a_9_ptr, i32 7
  %a_9_7_i8 = load i8, ptr %a_9_7_ptr
  %a_9_7_i16 = sext i8 %a_9_7_i8 to i16
  %a_9_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_7_i16, i32 0
  %a_9_7_vsplat = shufflevector <vscale x 8 x i16> %a_9_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_7 = mul <vscale x 8 x i16> %a_9_7_vsplat, %w_9_i16
  %add_9_7 = add <vscale x 8 x i16> %mul_9_7, %add_8_7
  %a_9_8_ptr = getelementptr i8, ptr %a_9_ptr, i32 8
  %a_9_8_i8 = load i8, ptr %a_9_8_ptr
  %a_9_8_i16 = sext i8 %a_9_8_i8 to i16
  %a_9_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_8_i16, i32 0
  %a_9_8_vsplat = shufflevector <vscale x 8 x i16> %a_9_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_8 = mul <vscale x 8 x i16> %a_9_8_vsplat, %w_9_i16
  %add_9_8 = add <vscale x 8 x i16> %mul_9_8, %add_8_8
  %a_9_9_ptr = getelementptr i8, ptr %a_9_ptr, i32 9
  %a_9_9_i8 = load i8, ptr %a_9_9_ptr
  %a_9_9_i16 = sext i8 %a_9_9_i8 to i16
  %a_9_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_9_i16, i32 0
  %a_9_9_vsplat = shufflevector <vscale x 8 x i16> %a_9_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_9 = mul <vscale x 8 x i16> %a_9_9_vsplat, %w_9_i16
  %add_9_9 = add <vscale x 8 x i16> %mul_9_9, %add_8_9
  %a_9_10_ptr = getelementptr i8, ptr %a_9_ptr, i32 10
  %a_9_10_i8 = load i8, ptr %a_9_10_ptr
  %a_9_10_i16 = sext i8 %a_9_10_i8 to i16
  %a_9_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_10_i16, i32 0
  %a_9_10_vsplat = shufflevector <vscale x 8 x i16> %a_9_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_10 = mul <vscale x 8 x i16> %a_9_10_vsplat, %w_9_i16
  %add_9_10 = add <vscale x 8 x i16> %mul_9_10, %add_8_10
  %a_9_11_ptr = getelementptr i8, ptr %a_9_ptr, i32 11
  %a_9_11_i8 = load i8, ptr %a_9_11_ptr
  %a_9_11_i16 = sext i8 %a_9_11_i8 to i16
  %a_9_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_9_11_i16, i32 0
  %a_9_11_vsplat = shufflevector <vscale x 8 x i16> %a_9_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_9_11 = mul <vscale x 8 x i16> %a_9_11_vsplat, %w_9_i16
  %add_9_11 = add <vscale x 8 x i16> %mul_9_11, %add_8_11

  %w_10_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 10
  %w_10_i8 = load <vscale x 8 x i8>, ptr %w_10_ptr
  %w_10_i16 = sext <vscale x 8 x i8> %w_10_i8 to <vscale x 8 x i16>

  %a_10_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 10
  %a_10_0_ptr = getelementptr i8, ptr %a_10_ptr, i32 0
  %a_10_0_i8 = load i8, ptr %a_10_0_ptr
  %a_10_0_i16 = sext i8 %a_10_0_i8 to i16
  %a_10_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_0_i16, i32 0
  %a_10_0_vsplat = shufflevector <vscale x 8 x i16> %a_10_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_0 = mul <vscale x 8 x i16> %a_10_0_vsplat, %w_10_i16
  %add_10_0 = add <vscale x 8 x i16> %mul_10_0, %add_9_0
  %a_10_1_ptr = getelementptr i8, ptr %a_10_ptr, i32 1
  %a_10_1_i8 = load i8, ptr %a_10_1_ptr
  %a_10_1_i16 = sext i8 %a_10_1_i8 to i16
  %a_10_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_1_i16, i32 0
  %a_10_1_vsplat = shufflevector <vscale x 8 x i16> %a_10_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_1 = mul <vscale x 8 x i16> %a_10_1_vsplat, %w_10_i16
  %add_10_1 = add <vscale x 8 x i16> %mul_10_1, %add_9_1
  %a_10_2_ptr = getelementptr i8, ptr %a_10_ptr, i32 2
  %a_10_2_i8 = load i8, ptr %a_10_2_ptr
  %a_10_2_i16 = sext i8 %a_10_2_i8 to i16
  %a_10_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_2_i16, i32 0
  %a_10_2_vsplat = shufflevector <vscale x 8 x i16> %a_10_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_2 = mul <vscale x 8 x i16> %a_10_2_vsplat, %w_10_i16
  %add_10_2 = add <vscale x 8 x i16> %mul_10_2, %add_9_2
  %a_10_3_ptr = getelementptr i8, ptr %a_10_ptr, i32 3
  %a_10_3_i8 = load i8, ptr %a_10_3_ptr
  %a_10_3_i16 = sext i8 %a_10_3_i8 to i16
  %a_10_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_3_i16, i32 0
  %a_10_3_vsplat = shufflevector <vscale x 8 x i16> %a_10_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_3 = mul <vscale x 8 x i16> %a_10_3_vsplat, %w_10_i16
  %add_10_3 = add <vscale x 8 x i16> %mul_10_3, %add_9_3
  %a_10_4_ptr = getelementptr i8, ptr %a_10_ptr, i32 4
  %a_10_4_i8 = load i8, ptr %a_10_4_ptr
  %a_10_4_i16 = sext i8 %a_10_4_i8 to i16
  %a_10_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_4_i16, i32 0
  %a_10_4_vsplat = shufflevector <vscale x 8 x i16> %a_10_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_4 = mul <vscale x 8 x i16> %a_10_4_vsplat, %w_10_i16
  %add_10_4 = add <vscale x 8 x i16> %mul_10_4, %add_9_4
  %a_10_5_ptr = getelementptr i8, ptr %a_10_ptr, i32 5
  %a_10_5_i8 = load i8, ptr %a_10_5_ptr
  %a_10_5_i16 = sext i8 %a_10_5_i8 to i16
  %a_10_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_5_i16, i32 0
  %a_10_5_vsplat = shufflevector <vscale x 8 x i16> %a_10_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_5 = mul <vscale x 8 x i16> %a_10_5_vsplat, %w_10_i16
  %add_10_5 = add <vscale x 8 x i16> %mul_10_5, %add_9_5
  %a_10_6_ptr = getelementptr i8, ptr %a_10_ptr, i32 6
  %a_10_6_i8 = load i8, ptr %a_10_6_ptr
  %a_10_6_i16 = sext i8 %a_10_6_i8 to i16
  %a_10_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_6_i16, i32 0
  %a_10_6_vsplat = shufflevector <vscale x 8 x i16> %a_10_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_6 = mul <vscale x 8 x i16> %a_10_6_vsplat, %w_10_i16
  %add_10_6 = add <vscale x 8 x i16> %mul_10_6, %add_9_6
  %a_10_7_ptr = getelementptr i8, ptr %a_10_ptr, i32 7
  %a_10_7_i8 = load i8, ptr %a_10_7_ptr
  %a_10_7_i16 = sext i8 %a_10_7_i8 to i16
  %a_10_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_7_i16, i32 0
  %a_10_7_vsplat = shufflevector <vscale x 8 x i16> %a_10_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_7 = mul <vscale x 8 x i16> %a_10_7_vsplat, %w_10_i16
  %add_10_7 = add <vscale x 8 x i16> %mul_10_7, %add_9_7
  %a_10_8_ptr = getelementptr i8, ptr %a_10_ptr, i32 8
  %a_10_8_i8 = load i8, ptr %a_10_8_ptr
  %a_10_8_i16 = sext i8 %a_10_8_i8 to i16
  %a_10_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_8_i16, i32 0
  %a_10_8_vsplat = shufflevector <vscale x 8 x i16> %a_10_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_8 = mul <vscale x 8 x i16> %a_10_8_vsplat, %w_10_i16
  %add_10_8 = add <vscale x 8 x i16> %mul_10_8, %add_9_8
  %a_10_9_ptr = getelementptr i8, ptr %a_10_ptr, i32 9
  %a_10_9_i8 = load i8, ptr %a_10_9_ptr
  %a_10_9_i16 = sext i8 %a_10_9_i8 to i16
  %a_10_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_9_i16, i32 0
  %a_10_9_vsplat = shufflevector <vscale x 8 x i16> %a_10_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_9 = mul <vscale x 8 x i16> %a_10_9_vsplat, %w_10_i16
  %add_10_9 = add <vscale x 8 x i16> %mul_10_9, %add_9_9
  %a_10_10_ptr = getelementptr i8, ptr %a_10_ptr, i32 10
  %a_10_10_i8 = load i8, ptr %a_10_10_ptr
  %a_10_10_i16 = sext i8 %a_10_10_i8 to i16
  %a_10_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_10_i16, i32 0
  %a_10_10_vsplat = shufflevector <vscale x 8 x i16> %a_10_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_10 = mul <vscale x 8 x i16> %a_10_10_vsplat, %w_10_i16
  %add_10_10 = add <vscale x 8 x i16> %mul_10_10, %add_9_10
  %a_10_11_ptr = getelementptr i8, ptr %a_10_ptr, i32 11
  %a_10_11_i8 = load i8, ptr %a_10_11_ptr
  %a_10_11_i16 = sext i8 %a_10_11_i8 to i16
  %a_10_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_10_11_i16, i32 0
  %a_10_11_vsplat = shufflevector <vscale x 8 x i16> %a_10_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_10_11 = mul <vscale x 8 x i16> %a_10_11_vsplat, %w_10_i16
  %add_10_11 = add <vscale x 8 x i16> %mul_10_11, %add_9_11

  %w_11_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 11
  %w_11_i8 = load <vscale x 8 x i8>, ptr %w_11_ptr
  %w_11_i16 = sext <vscale x 8 x i8> %w_11_i8 to <vscale x 8 x i16>

  %a_11_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 11
  %a_11_0_ptr = getelementptr i8, ptr %a_11_ptr, i32 0
  %a_11_0_i8 = load i8, ptr %a_11_0_ptr
  %a_11_0_i16 = sext i8 %a_11_0_i8 to i16
  %a_11_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_0_i16, i32 0
  %a_11_0_vsplat = shufflevector <vscale x 8 x i16> %a_11_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_0 = mul <vscale x 8 x i16> %a_11_0_vsplat, %w_11_i16
  %add_11_0 = add <vscale x 8 x i16> %mul_11_0, %add_10_0
  %a_11_1_ptr = getelementptr i8, ptr %a_11_ptr, i32 1
  %a_11_1_i8 = load i8, ptr %a_11_1_ptr
  %a_11_1_i16 = sext i8 %a_11_1_i8 to i16
  %a_11_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_1_i16, i32 0
  %a_11_1_vsplat = shufflevector <vscale x 8 x i16> %a_11_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_1 = mul <vscale x 8 x i16> %a_11_1_vsplat, %w_11_i16
  %add_11_1 = add <vscale x 8 x i16> %mul_11_1, %add_10_1
  %a_11_2_ptr = getelementptr i8, ptr %a_11_ptr, i32 2
  %a_11_2_i8 = load i8, ptr %a_11_2_ptr
  %a_11_2_i16 = sext i8 %a_11_2_i8 to i16
  %a_11_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_2_i16, i32 0
  %a_11_2_vsplat = shufflevector <vscale x 8 x i16> %a_11_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_2 = mul <vscale x 8 x i16> %a_11_2_vsplat, %w_11_i16
  %add_11_2 = add <vscale x 8 x i16> %mul_11_2, %add_10_2
  %a_11_3_ptr = getelementptr i8, ptr %a_11_ptr, i32 3
  %a_11_3_i8 = load i8, ptr %a_11_3_ptr
  %a_11_3_i16 = sext i8 %a_11_3_i8 to i16
  %a_11_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_3_i16, i32 0
  %a_11_3_vsplat = shufflevector <vscale x 8 x i16> %a_11_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_3 = mul <vscale x 8 x i16> %a_11_3_vsplat, %w_11_i16
  %add_11_3 = add <vscale x 8 x i16> %mul_11_3, %add_10_3
  %a_11_4_ptr = getelementptr i8, ptr %a_11_ptr, i32 4
  %a_11_4_i8 = load i8, ptr %a_11_4_ptr
  %a_11_4_i16 = sext i8 %a_11_4_i8 to i16
  %a_11_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_4_i16, i32 0
  %a_11_4_vsplat = shufflevector <vscale x 8 x i16> %a_11_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_4 = mul <vscale x 8 x i16> %a_11_4_vsplat, %w_11_i16
  %add_11_4 = add <vscale x 8 x i16> %mul_11_4, %add_10_4
  %a_11_5_ptr = getelementptr i8, ptr %a_11_ptr, i32 5
  %a_11_5_i8 = load i8, ptr %a_11_5_ptr
  %a_11_5_i16 = sext i8 %a_11_5_i8 to i16
  %a_11_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_5_i16, i32 0
  %a_11_5_vsplat = shufflevector <vscale x 8 x i16> %a_11_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_5 = mul <vscale x 8 x i16> %a_11_5_vsplat, %w_11_i16
  %add_11_5 = add <vscale x 8 x i16> %mul_11_5, %add_10_5
  %a_11_6_ptr = getelementptr i8, ptr %a_11_ptr, i32 6
  %a_11_6_i8 = load i8, ptr %a_11_6_ptr
  %a_11_6_i16 = sext i8 %a_11_6_i8 to i16
  %a_11_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_6_i16, i32 0
  %a_11_6_vsplat = shufflevector <vscale x 8 x i16> %a_11_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_6 = mul <vscale x 8 x i16> %a_11_6_vsplat, %w_11_i16
  %add_11_6 = add <vscale x 8 x i16> %mul_11_6, %add_10_6
  %a_11_7_ptr = getelementptr i8, ptr %a_11_ptr, i32 7
  %a_11_7_i8 = load i8, ptr %a_11_7_ptr
  %a_11_7_i16 = sext i8 %a_11_7_i8 to i16
  %a_11_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_7_i16, i32 0
  %a_11_7_vsplat = shufflevector <vscale x 8 x i16> %a_11_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_7 = mul <vscale x 8 x i16> %a_11_7_vsplat, %w_11_i16
  %add_11_7 = add <vscale x 8 x i16> %mul_11_7, %add_10_7
  %a_11_8_ptr = getelementptr i8, ptr %a_11_ptr, i32 8
  %a_11_8_i8 = load i8, ptr %a_11_8_ptr
  %a_11_8_i16 = sext i8 %a_11_8_i8 to i16
  %a_11_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_8_i16, i32 0
  %a_11_8_vsplat = shufflevector <vscale x 8 x i16> %a_11_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_8 = mul <vscale x 8 x i16> %a_11_8_vsplat, %w_11_i16
  %add_11_8 = add <vscale x 8 x i16> %mul_11_8, %add_10_8
  %a_11_9_ptr = getelementptr i8, ptr %a_11_ptr, i32 9
  %a_11_9_i8 = load i8, ptr %a_11_9_ptr
  %a_11_9_i16 = sext i8 %a_11_9_i8 to i16
  %a_11_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_9_i16, i32 0
  %a_11_9_vsplat = shufflevector <vscale x 8 x i16> %a_11_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_9 = mul <vscale x 8 x i16> %a_11_9_vsplat, %w_11_i16
  %add_11_9 = add <vscale x 8 x i16> %mul_11_9, %add_10_9
  %a_11_10_ptr = getelementptr i8, ptr %a_11_ptr, i32 10
  %a_11_10_i8 = load i8, ptr %a_11_10_ptr
  %a_11_10_i16 = sext i8 %a_11_10_i8 to i16
  %a_11_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_10_i16, i32 0
  %a_11_10_vsplat = shufflevector <vscale x 8 x i16> %a_11_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_10 = mul <vscale x 8 x i16> %a_11_10_vsplat, %w_11_i16
  %add_11_10 = add <vscale x 8 x i16> %mul_11_10, %add_10_10
  %a_11_11_ptr = getelementptr i8, ptr %a_11_ptr, i32 11
  %a_11_11_i8 = load i8, ptr %a_11_11_ptr
  %a_11_11_i16 = sext i8 %a_11_11_i8 to i16
  %a_11_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_11_11_i16, i32 0
  %a_11_11_vsplat = shufflevector <vscale x 8 x i16> %a_11_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_11_11 = mul <vscale x 8 x i16> %a_11_11_vsplat, %w_11_i16
  %add_11_11 = add <vscale x 8 x i16> %mul_11_11, %add_10_11

  %w_12_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 12
  %w_12_i8 = load <vscale x 8 x i8>, ptr %w_12_ptr
  %w_12_i16 = sext <vscale x 8 x i8> %w_12_i8 to <vscale x 8 x i16>

  %a_12_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 12
  %a_12_0_ptr = getelementptr i8, ptr %a_12_ptr, i32 0
  %a_12_0_i8 = load i8, ptr %a_12_0_ptr
  %a_12_0_i16 = sext i8 %a_12_0_i8 to i16
  %a_12_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_0_i16, i32 0
  %a_12_0_vsplat = shufflevector <vscale x 8 x i16> %a_12_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_0 = mul <vscale x 8 x i16> %a_12_0_vsplat, %w_12_i16
  %add_12_0 = add <vscale x 8 x i16> %mul_12_0, %add_11_0
  %a_12_1_ptr = getelementptr i8, ptr %a_12_ptr, i32 1
  %a_12_1_i8 = load i8, ptr %a_12_1_ptr
  %a_12_1_i16 = sext i8 %a_12_1_i8 to i16
  %a_12_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_1_i16, i32 0
  %a_12_1_vsplat = shufflevector <vscale x 8 x i16> %a_12_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_1 = mul <vscale x 8 x i16> %a_12_1_vsplat, %w_12_i16
  %add_12_1 = add <vscale x 8 x i16> %mul_12_1, %add_11_1
  %a_12_2_ptr = getelementptr i8, ptr %a_12_ptr, i32 2
  %a_12_2_i8 = load i8, ptr %a_12_2_ptr
  %a_12_2_i16 = sext i8 %a_12_2_i8 to i16
  %a_12_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_2_i16, i32 0
  %a_12_2_vsplat = shufflevector <vscale x 8 x i16> %a_12_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_2 = mul <vscale x 8 x i16> %a_12_2_vsplat, %w_12_i16
  %add_12_2 = add <vscale x 8 x i16> %mul_12_2, %add_11_2
  %a_12_3_ptr = getelementptr i8, ptr %a_12_ptr, i32 3
  %a_12_3_i8 = load i8, ptr %a_12_3_ptr
  %a_12_3_i16 = sext i8 %a_12_3_i8 to i16
  %a_12_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_3_i16, i32 0
  %a_12_3_vsplat = shufflevector <vscale x 8 x i16> %a_12_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_3 = mul <vscale x 8 x i16> %a_12_3_vsplat, %w_12_i16
  %add_12_3 = add <vscale x 8 x i16> %mul_12_3, %add_11_3
  %a_12_4_ptr = getelementptr i8, ptr %a_12_ptr, i32 4
  %a_12_4_i8 = load i8, ptr %a_12_4_ptr
  %a_12_4_i16 = sext i8 %a_12_4_i8 to i16
  %a_12_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_4_i16, i32 0
  %a_12_4_vsplat = shufflevector <vscale x 8 x i16> %a_12_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_4 = mul <vscale x 8 x i16> %a_12_4_vsplat, %w_12_i16
  %add_12_4 = add <vscale x 8 x i16> %mul_12_4, %add_11_4
  %a_12_5_ptr = getelementptr i8, ptr %a_12_ptr, i32 5
  %a_12_5_i8 = load i8, ptr %a_12_5_ptr
  %a_12_5_i16 = sext i8 %a_12_5_i8 to i16
  %a_12_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_5_i16, i32 0
  %a_12_5_vsplat = shufflevector <vscale x 8 x i16> %a_12_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_5 = mul <vscale x 8 x i16> %a_12_5_vsplat, %w_12_i16
  %add_12_5 = add <vscale x 8 x i16> %mul_12_5, %add_11_5
  %a_12_6_ptr = getelementptr i8, ptr %a_12_ptr, i32 6
  %a_12_6_i8 = load i8, ptr %a_12_6_ptr
  %a_12_6_i16 = sext i8 %a_12_6_i8 to i16
  %a_12_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_6_i16, i32 0
  %a_12_6_vsplat = shufflevector <vscale x 8 x i16> %a_12_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_6 = mul <vscale x 8 x i16> %a_12_6_vsplat, %w_12_i16
  %add_12_6 = add <vscale x 8 x i16> %mul_12_6, %add_11_6
  %a_12_7_ptr = getelementptr i8, ptr %a_12_ptr, i32 7
  %a_12_7_i8 = load i8, ptr %a_12_7_ptr
  %a_12_7_i16 = sext i8 %a_12_7_i8 to i16
  %a_12_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_7_i16, i32 0
  %a_12_7_vsplat = shufflevector <vscale x 8 x i16> %a_12_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_7 = mul <vscale x 8 x i16> %a_12_7_vsplat, %w_12_i16
  %add_12_7 = add <vscale x 8 x i16> %mul_12_7, %add_11_7
  %a_12_8_ptr = getelementptr i8, ptr %a_12_ptr, i32 8
  %a_12_8_i8 = load i8, ptr %a_12_8_ptr
  %a_12_8_i16 = sext i8 %a_12_8_i8 to i16
  %a_12_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_8_i16, i32 0
  %a_12_8_vsplat = shufflevector <vscale x 8 x i16> %a_12_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_8 = mul <vscale x 8 x i16> %a_12_8_vsplat, %w_12_i16
  %add_12_8 = add <vscale x 8 x i16> %mul_12_8, %add_11_8
  %a_12_9_ptr = getelementptr i8, ptr %a_12_ptr, i32 9
  %a_12_9_i8 = load i8, ptr %a_12_9_ptr
  %a_12_9_i16 = sext i8 %a_12_9_i8 to i16
  %a_12_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_9_i16, i32 0
  %a_12_9_vsplat = shufflevector <vscale x 8 x i16> %a_12_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_9 = mul <vscale x 8 x i16> %a_12_9_vsplat, %w_12_i16
  %add_12_9 = add <vscale x 8 x i16> %mul_12_9, %add_11_9
  %a_12_10_ptr = getelementptr i8, ptr %a_12_ptr, i32 10
  %a_12_10_i8 = load i8, ptr %a_12_10_ptr
  %a_12_10_i16 = sext i8 %a_12_10_i8 to i16
  %a_12_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_10_i16, i32 0
  %a_12_10_vsplat = shufflevector <vscale x 8 x i16> %a_12_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_10 = mul <vscale x 8 x i16> %a_12_10_vsplat, %w_12_i16
  %add_12_10 = add <vscale x 8 x i16> %mul_12_10, %add_11_10
  %a_12_11_ptr = getelementptr i8, ptr %a_12_ptr, i32 11
  %a_12_11_i8 = load i8, ptr %a_12_11_ptr
  %a_12_11_i16 = sext i8 %a_12_11_i8 to i16
  %a_12_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_12_11_i16, i32 0
  %a_12_11_vsplat = shufflevector <vscale x 8 x i16> %a_12_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_12_11 = mul <vscale x 8 x i16> %a_12_11_vsplat, %w_12_i16
  %add_12_11 = add <vscale x 8 x i16> %mul_12_11, %add_11_11

  %w_13_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 13
  %w_13_i8 = load <vscale x 8 x i8>, ptr %w_13_ptr
  %w_13_i16 = sext <vscale x 8 x i8> %w_13_i8 to <vscale x 8 x i16>

  %a_13_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 13
  %a_13_0_ptr = getelementptr i8, ptr %a_13_ptr, i32 0
  %a_13_0_i8 = load i8, ptr %a_13_0_ptr
  %a_13_0_i16 = sext i8 %a_13_0_i8 to i16
  %a_13_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_0_i16, i32 0
  %a_13_0_vsplat = shufflevector <vscale x 8 x i16> %a_13_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_0 = mul <vscale x 8 x i16> %a_13_0_vsplat, %w_13_i16
  %add_13_0 = add <vscale x 8 x i16> %mul_13_0, %add_12_0
  %a_13_1_ptr = getelementptr i8, ptr %a_13_ptr, i32 1
  %a_13_1_i8 = load i8, ptr %a_13_1_ptr
  %a_13_1_i16 = sext i8 %a_13_1_i8 to i16
  %a_13_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_1_i16, i32 0
  %a_13_1_vsplat = shufflevector <vscale x 8 x i16> %a_13_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_1 = mul <vscale x 8 x i16> %a_13_1_vsplat, %w_13_i16
  %add_13_1 = add <vscale x 8 x i16> %mul_13_1, %add_12_1
  %a_13_2_ptr = getelementptr i8, ptr %a_13_ptr, i32 2
  %a_13_2_i8 = load i8, ptr %a_13_2_ptr
  %a_13_2_i16 = sext i8 %a_13_2_i8 to i16
  %a_13_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_2_i16, i32 0
  %a_13_2_vsplat = shufflevector <vscale x 8 x i16> %a_13_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_2 = mul <vscale x 8 x i16> %a_13_2_vsplat, %w_13_i16
  %add_13_2 = add <vscale x 8 x i16> %mul_13_2, %add_12_2
  %a_13_3_ptr = getelementptr i8, ptr %a_13_ptr, i32 3
  %a_13_3_i8 = load i8, ptr %a_13_3_ptr
  %a_13_3_i16 = sext i8 %a_13_3_i8 to i16
  %a_13_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_3_i16, i32 0
  %a_13_3_vsplat = shufflevector <vscale x 8 x i16> %a_13_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_3 = mul <vscale x 8 x i16> %a_13_3_vsplat, %w_13_i16
  %add_13_3 = add <vscale x 8 x i16> %mul_13_3, %add_12_3
  %a_13_4_ptr = getelementptr i8, ptr %a_13_ptr, i32 4
  %a_13_4_i8 = load i8, ptr %a_13_4_ptr
  %a_13_4_i16 = sext i8 %a_13_4_i8 to i16
  %a_13_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_4_i16, i32 0
  %a_13_4_vsplat = shufflevector <vscale x 8 x i16> %a_13_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_4 = mul <vscale x 8 x i16> %a_13_4_vsplat, %w_13_i16
  %add_13_4 = add <vscale x 8 x i16> %mul_13_4, %add_12_4
  %a_13_5_ptr = getelementptr i8, ptr %a_13_ptr, i32 5
  %a_13_5_i8 = load i8, ptr %a_13_5_ptr
  %a_13_5_i16 = sext i8 %a_13_5_i8 to i16
  %a_13_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_5_i16, i32 0
  %a_13_5_vsplat = shufflevector <vscale x 8 x i16> %a_13_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_5 = mul <vscale x 8 x i16> %a_13_5_vsplat, %w_13_i16
  %add_13_5 = add <vscale x 8 x i16> %mul_13_5, %add_12_5
  %a_13_6_ptr = getelementptr i8, ptr %a_13_ptr, i32 6
  %a_13_6_i8 = load i8, ptr %a_13_6_ptr
  %a_13_6_i16 = sext i8 %a_13_6_i8 to i16
  %a_13_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_6_i16, i32 0
  %a_13_6_vsplat = shufflevector <vscale x 8 x i16> %a_13_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_6 = mul <vscale x 8 x i16> %a_13_6_vsplat, %w_13_i16
  %add_13_6 = add <vscale x 8 x i16> %mul_13_6, %add_12_6
  %a_13_7_ptr = getelementptr i8, ptr %a_13_ptr, i32 7
  %a_13_7_i8 = load i8, ptr %a_13_7_ptr
  %a_13_7_i16 = sext i8 %a_13_7_i8 to i16
  %a_13_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_7_i16, i32 0
  %a_13_7_vsplat = shufflevector <vscale x 8 x i16> %a_13_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_7 = mul <vscale x 8 x i16> %a_13_7_vsplat, %w_13_i16
  %add_13_7 = add <vscale x 8 x i16> %mul_13_7, %add_12_7
  %a_13_8_ptr = getelementptr i8, ptr %a_13_ptr, i32 8
  %a_13_8_i8 = load i8, ptr %a_13_8_ptr
  %a_13_8_i16 = sext i8 %a_13_8_i8 to i16
  %a_13_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_8_i16, i32 0
  %a_13_8_vsplat = shufflevector <vscale x 8 x i16> %a_13_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_8 = mul <vscale x 8 x i16> %a_13_8_vsplat, %w_13_i16
  %add_13_8 = add <vscale x 8 x i16> %mul_13_8, %add_12_8
  %a_13_9_ptr = getelementptr i8, ptr %a_13_ptr, i32 9
  %a_13_9_i8 = load i8, ptr %a_13_9_ptr
  %a_13_9_i16 = sext i8 %a_13_9_i8 to i16
  %a_13_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_9_i16, i32 0
  %a_13_9_vsplat = shufflevector <vscale x 8 x i16> %a_13_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_9 = mul <vscale x 8 x i16> %a_13_9_vsplat, %w_13_i16
  %add_13_9 = add <vscale x 8 x i16> %mul_13_9, %add_12_9
  %a_13_10_ptr = getelementptr i8, ptr %a_13_ptr, i32 10
  %a_13_10_i8 = load i8, ptr %a_13_10_ptr
  %a_13_10_i16 = sext i8 %a_13_10_i8 to i16
  %a_13_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_10_i16, i32 0
  %a_13_10_vsplat = shufflevector <vscale x 8 x i16> %a_13_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_10 = mul <vscale x 8 x i16> %a_13_10_vsplat, %w_13_i16
  %add_13_10 = add <vscale x 8 x i16> %mul_13_10, %add_12_10
  %a_13_11_ptr = getelementptr i8, ptr %a_13_ptr, i32 11
  %a_13_11_i8 = load i8, ptr %a_13_11_ptr
  %a_13_11_i16 = sext i8 %a_13_11_i8 to i16
  %a_13_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_13_11_i16, i32 0
  %a_13_11_vsplat = shufflevector <vscale x 8 x i16> %a_13_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_13_11 = mul <vscale x 8 x i16> %a_13_11_vsplat, %w_13_i16
  %add_13_11 = add <vscale x 8 x i16> %mul_13_11, %add_12_11

  %w_14_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 14
  %w_14_i8 = load <vscale x 8 x i8>, ptr %w_14_ptr
  %w_14_i16 = sext <vscale x 8 x i8> %w_14_i8 to <vscale x 8 x i16>

  %a_14_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 14
  %a_14_0_ptr = getelementptr i8, ptr %a_14_ptr, i32 0
  %a_14_0_i8 = load i8, ptr %a_14_0_ptr
  %a_14_0_i16 = sext i8 %a_14_0_i8 to i16
  %a_14_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_0_i16, i32 0
  %a_14_0_vsplat = shufflevector <vscale x 8 x i16> %a_14_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_0 = mul <vscale x 8 x i16> %a_14_0_vsplat, %w_14_i16
  %add_14_0 = add <vscale x 8 x i16> %mul_14_0, %add_13_0
  %a_14_1_ptr = getelementptr i8, ptr %a_14_ptr, i32 1
  %a_14_1_i8 = load i8, ptr %a_14_1_ptr
  %a_14_1_i16 = sext i8 %a_14_1_i8 to i16
  %a_14_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_1_i16, i32 0
  %a_14_1_vsplat = shufflevector <vscale x 8 x i16> %a_14_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_1 = mul <vscale x 8 x i16> %a_14_1_vsplat, %w_14_i16
  %add_14_1 = add <vscale x 8 x i16> %mul_14_1, %add_13_1
  %a_14_2_ptr = getelementptr i8, ptr %a_14_ptr, i32 2
  %a_14_2_i8 = load i8, ptr %a_14_2_ptr
  %a_14_2_i16 = sext i8 %a_14_2_i8 to i16
  %a_14_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_2_i16, i32 0
  %a_14_2_vsplat = shufflevector <vscale x 8 x i16> %a_14_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_2 = mul <vscale x 8 x i16> %a_14_2_vsplat, %w_14_i16
  %add_14_2 = add <vscale x 8 x i16> %mul_14_2, %add_13_2
  %a_14_3_ptr = getelementptr i8, ptr %a_14_ptr, i32 3
  %a_14_3_i8 = load i8, ptr %a_14_3_ptr
  %a_14_3_i16 = sext i8 %a_14_3_i8 to i16
  %a_14_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_3_i16, i32 0
  %a_14_3_vsplat = shufflevector <vscale x 8 x i16> %a_14_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_3 = mul <vscale x 8 x i16> %a_14_3_vsplat, %w_14_i16
  %add_14_3 = add <vscale x 8 x i16> %mul_14_3, %add_13_3
  %a_14_4_ptr = getelementptr i8, ptr %a_14_ptr, i32 4
  %a_14_4_i8 = load i8, ptr %a_14_4_ptr
  %a_14_4_i16 = sext i8 %a_14_4_i8 to i16
  %a_14_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_4_i16, i32 0
  %a_14_4_vsplat = shufflevector <vscale x 8 x i16> %a_14_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_4 = mul <vscale x 8 x i16> %a_14_4_vsplat, %w_14_i16
  %add_14_4 = add <vscale x 8 x i16> %mul_14_4, %add_13_4
  %a_14_5_ptr = getelementptr i8, ptr %a_14_ptr, i32 5
  %a_14_5_i8 = load i8, ptr %a_14_5_ptr
  %a_14_5_i16 = sext i8 %a_14_5_i8 to i16
  %a_14_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_5_i16, i32 0
  %a_14_5_vsplat = shufflevector <vscale x 8 x i16> %a_14_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_5 = mul <vscale x 8 x i16> %a_14_5_vsplat, %w_14_i16
  %add_14_5 = add <vscale x 8 x i16> %mul_14_5, %add_13_5
  %a_14_6_ptr = getelementptr i8, ptr %a_14_ptr, i32 6
  %a_14_6_i8 = load i8, ptr %a_14_6_ptr
  %a_14_6_i16 = sext i8 %a_14_6_i8 to i16
  %a_14_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_6_i16, i32 0
  %a_14_6_vsplat = shufflevector <vscale x 8 x i16> %a_14_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_6 = mul <vscale x 8 x i16> %a_14_6_vsplat, %w_14_i16
  %add_14_6 = add <vscale x 8 x i16> %mul_14_6, %add_13_6
  %a_14_7_ptr = getelementptr i8, ptr %a_14_ptr, i32 7
  %a_14_7_i8 = load i8, ptr %a_14_7_ptr
  %a_14_7_i16 = sext i8 %a_14_7_i8 to i16
  %a_14_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_7_i16, i32 0
  %a_14_7_vsplat = shufflevector <vscale x 8 x i16> %a_14_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_7 = mul <vscale x 8 x i16> %a_14_7_vsplat, %w_14_i16
  %add_14_7 = add <vscale x 8 x i16> %mul_14_7, %add_13_7
  %a_14_8_ptr = getelementptr i8, ptr %a_14_ptr, i32 8
  %a_14_8_i8 = load i8, ptr %a_14_8_ptr
  %a_14_8_i16 = sext i8 %a_14_8_i8 to i16
  %a_14_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_8_i16, i32 0
  %a_14_8_vsplat = shufflevector <vscale x 8 x i16> %a_14_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_8 = mul <vscale x 8 x i16> %a_14_8_vsplat, %w_14_i16
  %add_14_8 = add <vscale x 8 x i16> %mul_14_8, %add_13_8
  %a_14_9_ptr = getelementptr i8, ptr %a_14_ptr, i32 9
  %a_14_9_i8 = load i8, ptr %a_14_9_ptr
  %a_14_9_i16 = sext i8 %a_14_9_i8 to i16
  %a_14_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_9_i16, i32 0
  %a_14_9_vsplat = shufflevector <vscale x 8 x i16> %a_14_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_9 = mul <vscale x 8 x i16> %a_14_9_vsplat, %w_14_i16
  %add_14_9 = add <vscale x 8 x i16> %mul_14_9, %add_13_9
  %a_14_10_ptr = getelementptr i8, ptr %a_14_ptr, i32 10
  %a_14_10_i8 = load i8, ptr %a_14_10_ptr
  %a_14_10_i16 = sext i8 %a_14_10_i8 to i16
  %a_14_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_10_i16, i32 0
  %a_14_10_vsplat = shufflevector <vscale x 8 x i16> %a_14_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_10 = mul <vscale x 8 x i16> %a_14_10_vsplat, %w_14_i16
  %add_14_10 = add <vscale x 8 x i16> %mul_14_10, %add_13_10
  %a_14_11_ptr = getelementptr i8, ptr %a_14_ptr, i32 11
  %a_14_11_i8 = load i8, ptr %a_14_11_ptr
  %a_14_11_i16 = sext i8 %a_14_11_i8 to i16
  %a_14_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_14_11_i16, i32 0
  %a_14_11_vsplat = shufflevector <vscale x 8 x i16> %a_14_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_14_11 = mul <vscale x 8 x i16> %a_14_11_vsplat, %w_14_i16
  %add_14_11 = add <vscale x 8 x i16> %mul_14_11, %add_13_11

  %w_15_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 15
  %w_15_i8 = load <vscale x 8 x i8>, ptr %w_15_ptr
  %w_15_i16 = sext <vscale x 8 x i8> %w_15_i8 to <vscale x 8 x i16>

  %a_15_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 15
  %a_15_0_ptr = getelementptr i8, ptr %a_15_ptr, i32 0
  %a_15_0_i8 = load i8, ptr %a_15_0_ptr
  %a_15_0_i16 = sext i8 %a_15_0_i8 to i16
  %a_15_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_0_i16, i32 0
  %a_15_0_vsplat = shufflevector <vscale x 8 x i16> %a_15_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_0 = mul <vscale x 8 x i16> %a_15_0_vsplat, %w_15_i16
  %add_15_0 = add <vscale x 8 x i16> %mul_15_0, %add_14_0
  %a_15_1_ptr = getelementptr i8, ptr %a_15_ptr, i32 1
  %a_15_1_i8 = load i8, ptr %a_15_1_ptr
  %a_15_1_i16 = sext i8 %a_15_1_i8 to i16
  %a_15_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_1_i16, i32 0
  %a_15_1_vsplat = shufflevector <vscale x 8 x i16> %a_15_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_1 = mul <vscale x 8 x i16> %a_15_1_vsplat, %w_15_i16
  %add_15_1 = add <vscale x 8 x i16> %mul_15_1, %add_14_1
  %a_15_2_ptr = getelementptr i8, ptr %a_15_ptr, i32 2
  %a_15_2_i8 = load i8, ptr %a_15_2_ptr
  %a_15_2_i16 = sext i8 %a_15_2_i8 to i16
  %a_15_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_2_i16, i32 0
  %a_15_2_vsplat = shufflevector <vscale x 8 x i16> %a_15_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_2 = mul <vscale x 8 x i16> %a_15_2_vsplat, %w_15_i16
  %add_15_2 = add <vscale x 8 x i16> %mul_15_2, %add_14_2
  %a_15_3_ptr = getelementptr i8, ptr %a_15_ptr, i32 3
  %a_15_3_i8 = load i8, ptr %a_15_3_ptr
  %a_15_3_i16 = sext i8 %a_15_3_i8 to i16
  %a_15_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_3_i16, i32 0
  %a_15_3_vsplat = shufflevector <vscale x 8 x i16> %a_15_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_3 = mul <vscale x 8 x i16> %a_15_3_vsplat, %w_15_i16
  %add_15_3 = add <vscale x 8 x i16> %mul_15_3, %add_14_3
  %a_15_4_ptr = getelementptr i8, ptr %a_15_ptr, i32 4
  %a_15_4_i8 = load i8, ptr %a_15_4_ptr
  %a_15_4_i16 = sext i8 %a_15_4_i8 to i16
  %a_15_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_4_i16, i32 0
  %a_15_4_vsplat = shufflevector <vscale x 8 x i16> %a_15_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_4 = mul <vscale x 8 x i16> %a_15_4_vsplat, %w_15_i16
  %add_15_4 = add <vscale x 8 x i16> %mul_15_4, %add_14_4
  %a_15_5_ptr = getelementptr i8, ptr %a_15_ptr, i32 5
  %a_15_5_i8 = load i8, ptr %a_15_5_ptr
  %a_15_5_i16 = sext i8 %a_15_5_i8 to i16
  %a_15_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_5_i16, i32 0
  %a_15_5_vsplat = shufflevector <vscale x 8 x i16> %a_15_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_5 = mul <vscale x 8 x i16> %a_15_5_vsplat, %w_15_i16
  %add_15_5 = add <vscale x 8 x i16> %mul_15_5, %add_14_5
  %a_15_6_ptr = getelementptr i8, ptr %a_15_ptr, i32 6
  %a_15_6_i8 = load i8, ptr %a_15_6_ptr
  %a_15_6_i16 = sext i8 %a_15_6_i8 to i16
  %a_15_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_6_i16, i32 0
  %a_15_6_vsplat = shufflevector <vscale x 8 x i16> %a_15_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_6 = mul <vscale x 8 x i16> %a_15_6_vsplat, %w_15_i16
  %add_15_6 = add <vscale x 8 x i16> %mul_15_6, %add_14_6
  %a_15_7_ptr = getelementptr i8, ptr %a_15_ptr, i32 7
  %a_15_7_i8 = load i8, ptr %a_15_7_ptr
  %a_15_7_i16 = sext i8 %a_15_7_i8 to i16
  %a_15_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_7_i16, i32 0
  %a_15_7_vsplat = shufflevector <vscale x 8 x i16> %a_15_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_7 = mul <vscale x 8 x i16> %a_15_7_vsplat, %w_15_i16
  %add_15_7 = add <vscale x 8 x i16> %mul_15_7, %add_14_7
  %a_15_8_ptr = getelementptr i8, ptr %a_15_ptr, i32 8
  %a_15_8_i8 = load i8, ptr %a_15_8_ptr
  %a_15_8_i16 = sext i8 %a_15_8_i8 to i16
  %a_15_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_8_i16, i32 0
  %a_15_8_vsplat = shufflevector <vscale x 8 x i16> %a_15_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_8 = mul <vscale x 8 x i16> %a_15_8_vsplat, %w_15_i16
  %add_15_8 = add <vscale x 8 x i16> %mul_15_8, %add_14_8
  %a_15_9_ptr = getelementptr i8, ptr %a_15_ptr, i32 9
  %a_15_9_i8 = load i8, ptr %a_15_9_ptr
  %a_15_9_i16 = sext i8 %a_15_9_i8 to i16
  %a_15_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_9_i16, i32 0
  %a_15_9_vsplat = shufflevector <vscale x 8 x i16> %a_15_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_9 = mul <vscale x 8 x i16> %a_15_9_vsplat, %w_15_i16
  %add_15_9 = add <vscale x 8 x i16> %mul_15_9, %add_14_9
  %a_15_10_ptr = getelementptr i8, ptr %a_15_ptr, i32 10
  %a_15_10_i8 = load i8, ptr %a_15_10_ptr
  %a_15_10_i16 = sext i8 %a_15_10_i8 to i16
  %a_15_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_10_i16, i32 0
  %a_15_10_vsplat = shufflevector <vscale x 8 x i16> %a_15_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_10 = mul <vscale x 8 x i16> %a_15_10_vsplat, %w_15_i16
  %add_15_10 = add <vscale x 8 x i16> %mul_15_10, %add_14_10
  %a_15_11_ptr = getelementptr i8, ptr %a_15_ptr, i32 11
  %a_15_11_i8 = load i8, ptr %a_15_11_ptr
  %a_15_11_i16 = sext i8 %a_15_11_i8 to i16
  %a_15_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_15_11_i16, i32 0
  %a_15_11_vsplat = shufflevector <vscale x 8 x i16> %a_15_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_15_11 = mul <vscale x 8 x i16> %a_15_11_vsplat, %w_15_i16
  %add_15_11 = add <vscale x 8 x i16> %mul_15_11, %add_14_11

  %w_16_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 16
  %w_16_i8 = load <vscale x 8 x i8>, ptr %w_16_ptr
  %w_16_i16 = sext <vscale x 8 x i8> %w_16_i8 to <vscale x 8 x i16>

  %a_16_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 16
  %a_16_0_ptr = getelementptr i8, ptr %a_16_ptr, i32 0
  %a_16_0_i8 = load i8, ptr %a_16_0_ptr
  %a_16_0_i16 = sext i8 %a_16_0_i8 to i16
  %a_16_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_0_i16, i32 0
  %a_16_0_vsplat = shufflevector <vscale x 8 x i16> %a_16_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_0 = mul <vscale x 8 x i16> %a_16_0_vsplat, %w_16_i16
  %add_16_0 = add <vscale x 8 x i16> %mul_16_0, %add_15_0
  %a_16_1_ptr = getelementptr i8, ptr %a_16_ptr, i32 1
  %a_16_1_i8 = load i8, ptr %a_16_1_ptr
  %a_16_1_i16 = sext i8 %a_16_1_i8 to i16
  %a_16_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_1_i16, i32 0
  %a_16_1_vsplat = shufflevector <vscale x 8 x i16> %a_16_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_1 = mul <vscale x 8 x i16> %a_16_1_vsplat, %w_16_i16
  %add_16_1 = add <vscale x 8 x i16> %mul_16_1, %add_15_1
  %a_16_2_ptr = getelementptr i8, ptr %a_16_ptr, i32 2
  %a_16_2_i8 = load i8, ptr %a_16_2_ptr
  %a_16_2_i16 = sext i8 %a_16_2_i8 to i16
  %a_16_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_2_i16, i32 0
  %a_16_2_vsplat = shufflevector <vscale x 8 x i16> %a_16_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_2 = mul <vscale x 8 x i16> %a_16_2_vsplat, %w_16_i16
  %add_16_2 = add <vscale x 8 x i16> %mul_16_2, %add_15_2
  %a_16_3_ptr = getelementptr i8, ptr %a_16_ptr, i32 3
  %a_16_3_i8 = load i8, ptr %a_16_3_ptr
  %a_16_3_i16 = sext i8 %a_16_3_i8 to i16
  %a_16_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_3_i16, i32 0
  %a_16_3_vsplat = shufflevector <vscale x 8 x i16> %a_16_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_3 = mul <vscale x 8 x i16> %a_16_3_vsplat, %w_16_i16
  %add_16_3 = add <vscale x 8 x i16> %mul_16_3, %add_15_3
  %a_16_4_ptr = getelementptr i8, ptr %a_16_ptr, i32 4
  %a_16_4_i8 = load i8, ptr %a_16_4_ptr
  %a_16_4_i16 = sext i8 %a_16_4_i8 to i16
  %a_16_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_4_i16, i32 0
  %a_16_4_vsplat = shufflevector <vscale x 8 x i16> %a_16_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_4 = mul <vscale x 8 x i16> %a_16_4_vsplat, %w_16_i16
  %add_16_4 = add <vscale x 8 x i16> %mul_16_4, %add_15_4
  %a_16_5_ptr = getelementptr i8, ptr %a_16_ptr, i32 5
  %a_16_5_i8 = load i8, ptr %a_16_5_ptr
  %a_16_5_i16 = sext i8 %a_16_5_i8 to i16
  %a_16_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_5_i16, i32 0
  %a_16_5_vsplat = shufflevector <vscale x 8 x i16> %a_16_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_5 = mul <vscale x 8 x i16> %a_16_5_vsplat, %w_16_i16
  %add_16_5 = add <vscale x 8 x i16> %mul_16_5, %add_15_5
  %a_16_6_ptr = getelementptr i8, ptr %a_16_ptr, i32 6
  %a_16_6_i8 = load i8, ptr %a_16_6_ptr
  %a_16_6_i16 = sext i8 %a_16_6_i8 to i16
  %a_16_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_6_i16, i32 0
  %a_16_6_vsplat = shufflevector <vscale x 8 x i16> %a_16_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_6 = mul <vscale x 8 x i16> %a_16_6_vsplat, %w_16_i16
  %add_16_6 = add <vscale x 8 x i16> %mul_16_6, %add_15_6
  %a_16_7_ptr = getelementptr i8, ptr %a_16_ptr, i32 7
  %a_16_7_i8 = load i8, ptr %a_16_7_ptr
  %a_16_7_i16 = sext i8 %a_16_7_i8 to i16
  %a_16_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_7_i16, i32 0
  %a_16_7_vsplat = shufflevector <vscale x 8 x i16> %a_16_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_7 = mul <vscale x 8 x i16> %a_16_7_vsplat, %w_16_i16
  %add_16_7 = add <vscale x 8 x i16> %mul_16_7, %add_15_7
  %a_16_8_ptr = getelementptr i8, ptr %a_16_ptr, i32 8
  %a_16_8_i8 = load i8, ptr %a_16_8_ptr
  %a_16_8_i16 = sext i8 %a_16_8_i8 to i16
  %a_16_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_8_i16, i32 0
  %a_16_8_vsplat = shufflevector <vscale x 8 x i16> %a_16_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_8 = mul <vscale x 8 x i16> %a_16_8_vsplat, %w_16_i16
  %add_16_8 = add <vscale x 8 x i16> %mul_16_8, %add_15_8
  %a_16_9_ptr = getelementptr i8, ptr %a_16_ptr, i32 9
  %a_16_9_i8 = load i8, ptr %a_16_9_ptr
  %a_16_9_i16 = sext i8 %a_16_9_i8 to i16
  %a_16_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_9_i16, i32 0
  %a_16_9_vsplat = shufflevector <vscale x 8 x i16> %a_16_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_9 = mul <vscale x 8 x i16> %a_16_9_vsplat, %w_16_i16
  %add_16_9 = add <vscale x 8 x i16> %mul_16_9, %add_15_9
  %a_16_10_ptr = getelementptr i8, ptr %a_16_ptr, i32 10
  %a_16_10_i8 = load i8, ptr %a_16_10_ptr
  %a_16_10_i16 = sext i8 %a_16_10_i8 to i16
  %a_16_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_10_i16, i32 0
  %a_16_10_vsplat = shufflevector <vscale x 8 x i16> %a_16_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_10 = mul <vscale x 8 x i16> %a_16_10_vsplat, %w_16_i16
  %add_16_10 = add <vscale x 8 x i16> %mul_16_10, %add_15_10
  %a_16_11_ptr = getelementptr i8, ptr %a_16_ptr, i32 11
  %a_16_11_i8 = load i8, ptr %a_16_11_ptr
  %a_16_11_i16 = sext i8 %a_16_11_i8 to i16
  %a_16_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_16_11_i16, i32 0
  %a_16_11_vsplat = shufflevector <vscale x 8 x i16> %a_16_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_16_11 = mul <vscale x 8 x i16> %a_16_11_vsplat, %w_16_i16
  %add_16_11 = add <vscale x 8 x i16> %mul_16_11, %add_15_11

  %w_17_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 17
  %w_17_i8 = load <vscale x 8 x i8>, ptr %w_17_ptr
  %w_17_i16 = sext <vscale x 8 x i8> %w_17_i8 to <vscale x 8 x i16>

  %a_17_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 17
  %a_17_0_ptr = getelementptr i8, ptr %a_17_ptr, i32 0
  %a_17_0_i8 = load i8, ptr %a_17_0_ptr
  %a_17_0_i16 = sext i8 %a_17_0_i8 to i16
  %a_17_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_0_i16, i32 0
  %a_17_0_vsplat = shufflevector <vscale x 8 x i16> %a_17_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_0 = mul <vscale x 8 x i16> %a_17_0_vsplat, %w_17_i16
  %add_17_0 = add <vscale x 8 x i16> %mul_17_0, %add_16_0
  %a_17_1_ptr = getelementptr i8, ptr %a_17_ptr, i32 1
  %a_17_1_i8 = load i8, ptr %a_17_1_ptr
  %a_17_1_i16 = sext i8 %a_17_1_i8 to i16
  %a_17_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_1_i16, i32 0
  %a_17_1_vsplat = shufflevector <vscale x 8 x i16> %a_17_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_1 = mul <vscale x 8 x i16> %a_17_1_vsplat, %w_17_i16
  %add_17_1 = add <vscale x 8 x i16> %mul_17_1, %add_16_1
  %a_17_2_ptr = getelementptr i8, ptr %a_17_ptr, i32 2
  %a_17_2_i8 = load i8, ptr %a_17_2_ptr
  %a_17_2_i16 = sext i8 %a_17_2_i8 to i16
  %a_17_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_2_i16, i32 0
  %a_17_2_vsplat = shufflevector <vscale x 8 x i16> %a_17_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_2 = mul <vscale x 8 x i16> %a_17_2_vsplat, %w_17_i16
  %add_17_2 = add <vscale x 8 x i16> %mul_17_2, %add_16_2
  %a_17_3_ptr = getelementptr i8, ptr %a_17_ptr, i32 3
  %a_17_3_i8 = load i8, ptr %a_17_3_ptr
  %a_17_3_i16 = sext i8 %a_17_3_i8 to i16
  %a_17_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_3_i16, i32 0
  %a_17_3_vsplat = shufflevector <vscale x 8 x i16> %a_17_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_3 = mul <vscale x 8 x i16> %a_17_3_vsplat, %w_17_i16
  %add_17_3 = add <vscale x 8 x i16> %mul_17_3, %add_16_3
  %a_17_4_ptr = getelementptr i8, ptr %a_17_ptr, i32 4
  %a_17_4_i8 = load i8, ptr %a_17_4_ptr
  %a_17_4_i16 = sext i8 %a_17_4_i8 to i16
  %a_17_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_4_i16, i32 0
  %a_17_4_vsplat = shufflevector <vscale x 8 x i16> %a_17_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_4 = mul <vscale x 8 x i16> %a_17_4_vsplat, %w_17_i16
  %add_17_4 = add <vscale x 8 x i16> %mul_17_4, %add_16_4
  %a_17_5_ptr = getelementptr i8, ptr %a_17_ptr, i32 5
  %a_17_5_i8 = load i8, ptr %a_17_5_ptr
  %a_17_5_i16 = sext i8 %a_17_5_i8 to i16
  %a_17_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_5_i16, i32 0
  %a_17_5_vsplat = shufflevector <vscale x 8 x i16> %a_17_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_5 = mul <vscale x 8 x i16> %a_17_5_vsplat, %w_17_i16
  %add_17_5 = add <vscale x 8 x i16> %mul_17_5, %add_16_5
  %a_17_6_ptr = getelementptr i8, ptr %a_17_ptr, i32 6
  %a_17_6_i8 = load i8, ptr %a_17_6_ptr
  %a_17_6_i16 = sext i8 %a_17_6_i8 to i16
  %a_17_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_6_i16, i32 0
  %a_17_6_vsplat = shufflevector <vscale x 8 x i16> %a_17_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_6 = mul <vscale x 8 x i16> %a_17_6_vsplat, %w_17_i16
  %add_17_6 = add <vscale x 8 x i16> %mul_17_6, %add_16_6
  %a_17_7_ptr = getelementptr i8, ptr %a_17_ptr, i32 7
  %a_17_7_i8 = load i8, ptr %a_17_7_ptr
  %a_17_7_i16 = sext i8 %a_17_7_i8 to i16
  %a_17_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_7_i16, i32 0
  %a_17_7_vsplat = shufflevector <vscale x 8 x i16> %a_17_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_7 = mul <vscale x 8 x i16> %a_17_7_vsplat, %w_17_i16
  %add_17_7 = add <vscale x 8 x i16> %mul_17_7, %add_16_7
  %a_17_8_ptr = getelementptr i8, ptr %a_17_ptr, i32 8
  %a_17_8_i8 = load i8, ptr %a_17_8_ptr
  %a_17_8_i16 = sext i8 %a_17_8_i8 to i16
  %a_17_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_8_i16, i32 0
  %a_17_8_vsplat = shufflevector <vscale x 8 x i16> %a_17_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_8 = mul <vscale x 8 x i16> %a_17_8_vsplat, %w_17_i16
  %add_17_8 = add <vscale x 8 x i16> %mul_17_8, %add_16_8
  %a_17_9_ptr = getelementptr i8, ptr %a_17_ptr, i32 9
  %a_17_9_i8 = load i8, ptr %a_17_9_ptr
  %a_17_9_i16 = sext i8 %a_17_9_i8 to i16
  %a_17_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_9_i16, i32 0
  %a_17_9_vsplat = shufflevector <vscale x 8 x i16> %a_17_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_9 = mul <vscale x 8 x i16> %a_17_9_vsplat, %w_17_i16
  %add_17_9 = add <vscale x 8 x i16> %mul_17_9, %add_16_9
  %a_17_10_ptr = getelementptr i8, ptr %a_17_ptr, i32 10
  %a_17_10_i8 = load i8, ptr %a_17_10_ptr
  %a_17_10_i16 = sext i8 %a_17_10_i8 to i16
  %a_17_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_10_i16, i32 0
  %a_17_10_vsplat = shufflevector <vscale x 8 x i16> %a_17_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_10 = mul <vscale x 8 x i16> %a_17_10_vsplat, %w_17_i16
  %add_17_10 = add <vscale x 8 x i16> %mul_17_10, %add_16_10
  %a_17_11_ptr = getelementptr i8, ptr %a_17_ptr, i32 11
  %a_17_11_i8 = load i8, ptr %a_17_11_ptr
  %a_17_11_i16 = sext i8 %a_17_11_i8 to i16
  %a_17_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_17_11_i16, i32 0
  %a_17_11_vsplat = shufflevector <vscale x 8 x i16> %a_17_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_17_11 = mul <vscale x 8 x i16> %a_17_11_vsplat, %w_17_i16
  %add_17_11 = add <vscale x 8 x i16> %mul_17_11, %add_16_11

  %w_18_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 18
  %w_18_i8 = load <vscale x 8 x i8>, ptr %w_18_ptr
  %w_18_i16 = sext <vscale x 8 x i8> %w_18_i8 to <vscale x 8 x i16>

  %a_18_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 18
  %a_18_0_ptr = getelementptr i8, ptr %a_18_ptr, i32 0
  %a_18_0_i8 = load i8, ptr %a_18_0_ptr
  %a_18_0_i16 = sext i8 %a_18_0_i8 to i16
  %a_18_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_0_i16, i32 0
  %a_18_0_vsplat = shufflevector <vscale x 8 x i16> %a_18_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_0 = mul <vscale x 8 x i16> %a_18_0_vsplat, %w_18_i16
  %add_18_0 = add <vscale x 8 x i16> %mul_18_0, %add_17_0
  %a_18_1_ptr = getelementptr i8, ptr %a_18_ptr, i32 1
  %a_18_1_i8 = load i8, ptr %a_18_1_ptr
  %a_18_1_i16 = sext i8 %a_18_1_i8 to i16
  %a_18_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_1_i16, i32 0
  %a_18_1_vsplat = shufflevector <vscale x 8 x i16> %a_18_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_1 = mul <vscale x 8 x i16> %a_18_1_vsplat, %w_18_i16
  %add_18_1 = add <vscale x 8 x i16> %mul_18_1, %add_17_1
  %a_18_2_ptr = getelementptr i8, ptr %a_18_ptr, i32 2
  %a_18_2_i8 = load i8, ptr %a_18_2_ptr
  %a_18_2_i16 = sext i8 %a_18_2_i8 to i16
  %a_18_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_2_i16, i32 0
  %a_18_2_vsplat = shufflevector <vscale x 8 x i16> %a_18_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_2 = mul <vscale x 8 x i16> %a_18_2_vsplat, %w_18_i16
  %add_18_2 = add <vscale x 8 x i16> %mul_18_2, %add_17_2
  %a_18_3_ptr = getelementptr i8, ptr %a_18_ptr, i32 3
  %a_18_3_i8 = load i8, ptr %a_18_3_ptr
  %a_18_3_i16 = sext i8 %a_18_3_i8 to i16
  %a_18_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_3_i16, i32 0
  %a_18_3_vsplat = shufflevector <vscale x 8 x i16> %a_18_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_3 = mul <vscale x 8 x i16> %a_18_3_vsplat, %w_18_i16
  %add_18_3 = add <vscale x 8 x i16> %mul_18_3, %add_17_3
  %a_18_4_ptr = getelementptr i8, ptr %a_18_ptr, i32 4
  %a_18_4_i8 = load i8, ptr %a_18_4_ptr
  %a_18_4_i16 = sext i8 %a_18_4_i8 to i16
  %a_18_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_4_i16, i32 0
  %a_18_4_vsplat = shufflevector <vscale x 8 x i16> %a_18_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_4 = mul <vscale x 8 x i16> %a_18_4_vsplat, %w_18_i16
  %add_18_4 = add <vscale x 8 x i16> %mul_18_4, %add_17_4
  %a_18_5_ptr = getelementptr i8, ptr %a_18_ptr, i32 5
  %a_18_5_i8 = load i8, ptr %a_18_5_ptr
  %a_18_5_i16 = sext i8 %a_18_5_i8 to i16
  %a_18_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_5_i16, i32 0
  %a_18_5_vsplat = shufflevector <vscale x 8 x i16> %a_18_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_5 = mul <vscale x 8 x i16> %a_18_5_vsplat, %w_18_i16
  %add_18_5 = add <vscale x 8 x i16> %mul_18_5, %add_17_5
  %a_18_6_ptr = getelementptr i8, ptr %a_18_ptr, i32 6
  %a_18_6_i8 = load i8, ptr %a_18_6_ptr
  %a_18_6_i16 = sext i8 %a_18_6_i8 to i16
  %a_18_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_6_i16, i32 0
  %a_18_6_vsplat = shufflevector <vscale x 8 x i16> %a_18_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_6 = mul <vscale x 8 x i16> %a_18_6_vsplat, %w_18_i16
  %add_18_6 = add <vscale x 8 x i16> %mul_18_6, %add_17_6
  %a_18_7_ptr = getelementptr i8, ptr %a_18_ptr, i32 7
  %a_18_7_i8 = load i8, ptr %a_18_7_ptr
  %a_18_7_i16 = sext i8 %a_18_7_i8 to i16
  %a_18_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_7_i16, i32 0
  %a_18_7_vsplat = shufflevector <vscale x 8 x i16> %a_18_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_7 = mul <vscale x 8 x i16> %a_18_7_vsplat, %w_18_i16
  %add_18_7 = add <vscale x 8 x i16> %mul_18_7, %add_17_7
  %a_18_8_ptr = getelementptr i8, ptr %a_18_ptr, i32 8
  %a_18_8_i8 = load i8, ptr %a_18_8_ptr
  %a_18_8_i16 = sext i8 %a_18_8_i8 to i16
  %a_18_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_8_i16, i32 0
  %a_18_8_vsplat = shufflevector <vscale x 8 x i16> %a_18_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_8 = mul <vscale x 8 x i16> %a_18_8_vsplat, %w_18_i16
  %add_18_8 = add <vscale x 8 x i16> %mul_18_8, %add_17_8
  %a_18_9_ptr = getelementptr i8, ptr %a_18_ptr, i32 9
  %a_18_9_i8 = load i8, ptr %a_18_9_ptr
  %a_18_9_i16 = sext i8 %a_18_9_i8 to i16
  %a_18_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_9_i16, i32 0
  %a_18_9_vsplat = shufflevector <vscale x 8 x i16> %a_18_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_9 = mul <vscale x 8 x i16> %a_18_9_vsplat, %w_18_i16
  %add_18_9 = add <vscale x 8 x i16> %mul_18_9, %add_17_9
  %a_18_10_ptr = getelementptr i8, ptr %a_18_ptr, i32 10
  %a_18_10_i8 = load i8, ptr %a_18_10_ptr
  %a_18_10_i16 = sext i8 %a_18_10_i8 to i16
  %a_18_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_10_i16, i32 0
  %a_18_10_vsplat = shufflevector <vscale x 8 x i16> %a_18_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_10 = mul <vscale x 8 x i16> %a_18_10_vsplat, %w_18_i16
  %add_18_10 = add <vscale x 8 x i16> %mul_18_10, %add_17_10
  %a_18_11_ptr = getelementptr i8, ptr %a_18_ptr, i32 11
  %a_18_11_i8 = load i8, ptr %a_18_11_ptr
  %a_18_11_i16 = sext i8 %a_18_11_i8 to i16
  %a_18_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_18_11_i16, i32 0
  %a_18_11_vsplat = shufflevector <vscale x 8 x i16> %a_18_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_18_11 = mul <vscale x 8 x i16> %a_18_11_vsplat, %w_18_i16
  %add_18_11 = add <vscale x 8 x i16> %mul_18_11, %add_17_11

  %w_19_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 19
  %w_19_i8 = load <vscale x 8 x i8>, ptr %w_19_ptr
  %w_19_i16 = sext <vscale x 8 x i8> %w_19_i8 to <vscale x 8 x i16>

  %a_19_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 19
  %a_19_0_ptr = getelementptr i8, ptr %a_19_ptr, i32 0
  %a_19_0_i8 = load i8, ptr %a_19_0_ptr
  %a_19_0_i16 = sext i8 %a_19_0_i8 to i16
  %a_19_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_0_i16, i32 0
  %a_19_0_vsplat = shufflevector <vscale x 8 x i16> %a_19_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_0 = mul <vscale x 8 x i16> %a_19_0_vsplat, %w_19_i16
  %add_19_0 = add <vscale x 8 x i16> %mul_19_0, %add_18_0
  %a_19_1_ptr = getelementptr i8, ptr %a_19_ptr, i32 1
  %a_19_1_i8 = load i8, ptr %a_19_1_ptr
  %a_19_1_i16 = sext i8 %a_19_1_i8 to i16
  %a_19_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_1_i16, i32 0
  %a_19_1_vsplat = shufflevector <vscale x 8 x i16> %a_19_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_1 = mul <vscale x 8 x i16> %a_19_1_vsplat, %w_19_i16
  %add_19_1 = add <vscale x 8 x i16> %mul_19_1, %add_18_1
  %a_19_2_ptr = getelementptr i8, ptr %a_19_ptr, i32 2
  %a_19_2_i8 = load i8, ptr %a_19_2_ptr
  %a_19_2_i16 = sext i8 %a_19_2_i8 to i16
  %a_19_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_2_i16, i32 0
  %a_19_2_vsplat = shufflevector <vscale x 8 x i16> %a_19_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_2 = mul <vscale x 8 x i16> %a_19_2_vsplat, %w_19_i16
  %add_19_2 = add <vscale x 8 x i16> %mul_19_2, %add_18_2
  %a_19_3_ptr = getelementptr i8, ptr %a_19_ptr, i32 3
  %a_19_3_i8 = load i8, ptr %a_19_3_ptr
  %a_19_3_i16 = sext i8 %a_19_3_i8 to i16
  %a_19_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_3_i16, i32 0
  %a_19_3_vsplat = shufflevector <vscale x 8 x i16> %a_19_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_3 = mul <vscale x 8 x i16> %a_19_3_vsplat, %w_19_i16
  %add_19_3 = add <vscale x 8 x i16> %mul_19_3, %add_18_3
  %a_19_4_ptr = getelementptr i8, ptr %a_19_ptr, i32 4
  %a_19_4_i8 = load i8, ptr %a_19_4_ptr
  %a_19_4_i16 = sext i8 %a_19_4_i8 to i16
  %a_19_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_4_i16, i32 0
  %a_19_4_vsplat = shufflevector <vscale x 8 x i16> %a_19_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_4 = mul <vscale x 8 x i16> %a_19_4_vsplat, %w_19_i16
  %add_19_4 = add <vscale x 8 x i16> %mul_19_4, %add_18_4
  %a_19_5_ptr = getelementptr i8, ptr %a_19_ptr, i32 5
  %a_19_5_i8 = load i8, ptr %a_19_5_ptr
  %a_19_5_i16 = sext i8 %a_19_5_i8 to i16
  %a_19_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_5_i16, i32 0
  %a_19_5_vsplat = shufflevector <vscale x 8 x i16> %a_19_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_5 = mul <vscale x 8 x i16> %a_19_5_vsplat, %w_19_i16
  %add_19_5 = add <vscale x 8 x i16> %mul_19_5, %add_18_5
  %a_19_6_ptr = getelementptr i8, ptr %a_19_ptr, i32 6
  %a_19_6_i8 = load i8, ptr %a_19_6_ptr
  %a_19_6_i16 = sext i8 %a_19_6_i8 to i16
  %a_19_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_6_i16, i32 0
  %a_19_6_vsplat = shufflevector <vscale x 8 x i16> %a_19_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_6 = mul <vscale x 8 x i16> %a_19_6_vsplat, %w_19_i16
  %add_19_6 = add <vscale x 8 x i16> %mul_19_6, %add_18_6
  %a_19_7_ptr = getelementptr i8, ptr %a_19_ptr, i32 7
  %a_19_7_i8 = load i8, ptr %a_19_7_ptr
  %a_19_7_i16 = sext i8 %a_19_7_i8 to i16
  %a_19_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_7_i16, i32 0
  %a_19_7_vsplat = shufflevector <vscale x 8 x i16> %a_19_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_7 = mul <vscale x 8 x i16> %a_19_7_vsplat, %w_19_i16
  %add_19_7 = add <vscale x 8 x i16> %mul_19_7, %add_18_7
  %a_19_8_ptr = getelementptr i8, ptr %a_19_ptr, i32 8
  %a_19_8_i8 = load i8, ptr %a_19_8_ptr
  %a_19_8_i16 = sext i8 %a_19_8_i8 to i16
  %a_19_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_8_i16, i32 0
  %a_19_8_vsplat = shufflevector <vscale x 8 x i16> %a_19_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_8 = mul <vscale x 8 x i16> %a_19_8_vsplat, %w_19_i16
  %add_19_8 = add <vscale x 8 x i16> %mul_19_8, %add_18_8
  %a_19_9_ptr = getelementptr i8, ptr %a_19_ptr, i32 9
  %a_19_9_i8 = load i8, ptr %a_19_9_ptr
  %a_19_9_i16 = sext i8 %a_19_9_i8 to i16
  %a_19_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_9_i16, i32 0
  %a_19_9_vsplat = shufflevector <vscale x 8 x i16> %a_19_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_9 = mul <vscale x 8 x i16> %a_19_9_vsplat, %w_19_i16
  %add_19_9 = add <vscale x 8 x i16> %mul_19_9, %add_18_9
  %a_19_10_ptr = getelementptr i8, ptr %a_19_ptr, i32 10
  %a_19_10_i8 = load i8, ptr %a_19_10_ptr
  %a_19_10_i16 = sext i8 %a_19_10_i8 to i16
  %a_19_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_10_i16, i32 0
  %a_19_10_vsplat = shufflevector <vscale x 8 x i16> %a_19_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_10 = mul <vscale x 8 x i16> %a_19_10_vsplat, %w_19_i16
  %add_19_10 = add <vscale x 8 x i16> %mul_19_10, %add_18_10
  %a_19_11_ptr = getelementptr i8, ptr %a_19_ptr, i32 11
  %a_19_11_i8 = load i8, ptr %a_19_11_ptr
  %a_19_11_i16 = sext i8 %a_19_11_i8 to i16
  %a_19_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_19_11_i16, i32 0
  %a_19_11_vsplat = shufflevector <vscale x 8 x i16> %a_19_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_19_11 = mul <vscale x 8 x i16> %a_19_11_vsplat, %w_19_i16
  %add_19_11 = add <vscale x 8 x i16> %mul_19_11, %add_18_11

  %w_20_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 20
  %w_20_i8 = load <vscale x 8 x i8>, ptr %w_20_ptr
  %w_20_i16 = sext <vscale x 8 x i8> %w_20_i8 to <vscale x 8 x i16>

  %a_20_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 20
  %a_20_0_ptr = getelementptr i8, ptr %a_20_ptr, i32 0
  %a_20_0_i8 = load i8, ptr %a_20_0_ptr
  %a_20_0_i16 = sext i8 %a_20_0_i8 to i16
  %a_20_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_0_i16, i32 0
  %a_20_0_vsplat = shufflevector <vscale x 8 x i16> %a_20_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_0 = mul <vscale x 8 x i16> %a_20_0_vsplat, %w_20_i16
  %add_20_0 = add <vscale x 8 x i16> %mul_20_0, %add_19_0
  %a_20_1_ptr = getelementptr i8, ptr %a_20_ptr, i32 1
  %a_20_1_i8 = load i8, ptr %a_20_1_ptr
  %a_20_1_i16 = sext i8 %a_20_1_i8 to i16
  %a_20_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_1_i16, i32 0
  %a_20_1_vsplat = shufflevector <vscale x 8 x i16> %a_20_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_1 = mul <vscale x 8 x i16> %a_20_1_vsplat, %w_20_i16
  %add_20_1 = add <vscale x 8 x i16> %mul_20_1, %add_19_1
  %a_20_2_ptr = getelementptr i8, ptr %a_20_ptr, i32 2
  %a_20_2_i8 = load i8, ptr %a_20_2_ptr
  %a_20_2_i16 = sext i8 %a_20_2_i8 to i16
  %a_20_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_2_i16, i32 0
  %a_20_2_vsplat = shufflevector <vscale x 8 x i16> %a_20_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_2 = mul <vscale x 8 x i16> %a_20_2_vsplat, %w_20_i16
  %add_20_2 = add <vscale x 8 x i16> %mul_20_2, %add_19_2
  %a_20_3_ptr = getelementptr i8, ptr %a_20_ptr, i32 3
  %a_20_3_i8 = load i8, ptr %a_20_3_ptr
  %a_20_3_i16 = sext i8 %a_20_3_i8 to i16
  %a_20_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_3_i16, i32 0
  %a_20_3_vsplat = shufflevector <vscale x 8 x i16> %a_20_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_3 = mul <vscale x 8 x i16> %a_20_3_vsplat, %w_20_i16
  %add_20_3 = add <vscale x 8 x i16> %mul_20_3, %add_19_3
  %a_20_4_ptr = getelementptr i8, ptr %a_20_ptr, i32 4
  %a_20_4_i8 = load i8, ptr %a_20_4_ptr
  %a_20_4_i16 = sext i8 %a_20_4_i8 to i16
  %a_20_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_4_i16, i32 0
  %a_20_4_vsplat = shufflevector <vscale x 8 x i16> %a_20_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_4 = mul <vscale x 8 x i16> %a_20_4_vsplat, %w_20_i16
  %add_20_4 = add <vscale x 8 x i16> %mul_20_4, %add_19_4
  %a_20_5_ptr = getelementptr i8, ptr %a_20_ptr, i32 5
  %a_20_5_i8 = load i8, ptr %a_20_5_ptr
  %a_20_5_i16 = sext i8 %a_20_5_i8 to i16
  %a_20_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_5_i16, i32 0
  %a_20_5_vsplat = shufflevector <vscale x 8 x i16> %a_20_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_5 = mul <vscale x 8 x i16> %a_20_5_vsplat, %w_20_i16
  %add_20_5 = add <vscale x 8 x i16> %mul_20_5, %add_19_5
  %a_20_6_ptr = getelementptr i8, ptr %a_20_ptr, i32 6
  %a_20_6_i8 = load i8, ptr %a_20_6_ptr
  %a_20_6_i16 = sext i8 %a_20_6_i8 to i16
  %a_20_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_6_i16, i32 0
  %a_20_6_vsplat = shufflevector <vscale x 8 x i16> %a_20_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_6 = mul <vscale x 8 x i16> %a_20_6_vsplat, %w_20_i16
  %add_20_6 = add <vscale x 8 x i16> %mul_20_6, %add_19_6
  %a_20_7_ptr = getelementptr i8, ptr %a_20_ptr, i32 7
  %a_20_7_i8 = load i8, ptr %a_20_7_ptr
  %a_20_7_i16 = sext i8 %a_20_7_i8 to i16
  %a_20_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_7_i16, i32 0
  %a_20_7_vsplat = shufflevector <vscale x 8 x i16> %a_20_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_7 = mul <vscale x 8 x i16> %a_20_7_vsplat, %w_20_i16
  %add_20_7 = add <vscale x 8 x i16> %mul_20_7, %add_19_7
  %a_20_8_ptr = getelementptr i8, ptr %a_20_ptr, i32 8
  %a_20_8_i8 = load i8, ptr %a_20_8_ptr
  %a_20_8_i16 = sext i8 %a_20_8_i8 to i16
  %a_20_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_8_i16, i32 0
  %a_20_8_vsplat = shufflevector <vscale x 8 x i16> %a_20_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_8 = mul <vscale x 8 x i16> %a_20_8_vsplat, %w_20_i16
  %add_20_8 = add <vscale x 8 x i16> %mul_20_8, %add_19_8
  %a_20_9_ptr = getelementptr i8, ptr %a_20_ptr, i32 9
  %a_20_9_i8 = load i8, ptr %a_20_9_ptr
  %a_20_9_i16 = sext i8 %a_20_9_i8 to i16
  %a_20_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_9_i16, i32 0
  %a_20_9_vsplat = shufflevector <vscale x 8 x i16> %a_20_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_9 = mul <vscale x 8 x i16> %a_20_9_vsplat, %w_20_i16
  %add_20_9 = add <vscale x 8 x i16> %mul_20_9, %add_19_9
  %a_20_10_ptr = getelementptr i8, ptr %a_20_ptr, i32 10
  %a_20_10_i8 = load i8, ptr %a_20_10_ptr
  %a_20_10_i16 = sext i8 %a_20_10_i8 to i16
  %a_20_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_10_i16, i32 0
  %a_20_10_vsplat = shufflevector <vscale x 8 x i16> %a_20_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_10 = mul <vscale x 8 x i16> %a_20_10_vsplat, %w_20_i16
  %add_20_10 = add <vscale x 8 x i16> %mul_20_10, %add_19_10
  %a_20_11_ptr = getelementptr i8, ptr %a_20_ptr, i32 11
  %a_20_11_i8 = load i8, ptr %a_20_11_ptr
  %a_20_11_i16 = sext i8 %a_20_11_i8 to i16
  %a_20_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_20_11_i16, i32 0
  %a_20_11_vsplat = shufflevector <vscale x 8 x i16> %a_20_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_20_11 = mul <vscale x 8 x i16> %a_20_11_vsplat, %w_20_i16
  %add_20_11 = add <vscale x 8 x i16> %mul_20_11, %add_19_11

  %w_21_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 21
  %w_21_i8 = load <vscale x 8 x i8>, ptr %w_21_ptr
  %w_21_i16 = sext <vscale x 8 x i8> %w_21_i8 to <vscale x 8 x i16>

  %a_21_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 21
  %a_21_0_ptr = getelementptr i8, ptr %a_21_ptr, i32 0
  %a_21_0_i8 = load i8, ptr %a_21_0_ptr
  %a_21_0_i16 = sext i8 %a_21_0_i8 to i16
  %a_21_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_0_i16, i32 0
  %a_21_0_vsplat = shufflevector <vscale x 8 x i16> %a_21_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_0 = mul <vscale x 8 x i16> %a_21_0_vsplat, %w_21_i16
  %add_21_0 = add <vscale x 8 x i16> %mul_21_0, %add_20_0
  %a_21_1_ptr = getelementptr i8, ptr %a_21_ptr, i32 1
  %a_21_1_i8 = load i8, ptr %a_21_1_ptr
  %a_21_1_i16 = sext i8 %a_21_1_i8 to i16
  %a_21_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_1_i16, i32 0
  %a_21_1_vsplat = shufflevector <vscale x 8 x i16> %a_21_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_1 = mul <vscale x 8 x i16> %a_21_1_vsplat, %w_21_i16
  %add_21_1 = add <vscale x 8 x i16> %mul_21_1, %add_20_1
  %a_21_2_ptr = getelementptr i8, ptr %a_21_ptr, i32 2
  %a_21_2_i8 = load i8, ptr %a_21_2_ptr
  %a_21_2_i16 = sext i8 %a_21_2_i8 to i16
  %a_21_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_2_i16, i32 0
  %a_21_2_vsplat = shufflevector <vscale x 8 x i16> %a_21_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_2 = mul <vscale x 8 x i16> %a_21_2_vsplat, %w_21_i16
  %add_21_2 = add <vscale x 8 x i16> %mul_21_2, %add_20_2
  %a_21_3_ptr = getelementptr i8, ptr %a_21_ptr, i32 3
  %a_21_3_i8 = load i8, ptr %a_21_3_ptr
  %a_21_3_i16 = sext i8 %a_21_3_i8 to i16
  %a_21_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_3_i16, i32 0
  %a_21_3_vsplat = shufflevector <vscale x 8 x i16> %a_21_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_3 = mul <vscale x 8 x i16> %a_21_3_vsplat, %w_21_i16
  %add_21_3 = add <vscale x 8 x i16> %mul_21_3, %add_20_3
  %a_21_4_ptr = getelementptr i8, ptr %a_21_ptr, i32 4
  %a_21_4_i8 = load i8, ptr %a_21_4_ptr
  %a_21_4_i16 = sext i8 %a_21_4_i8 to i16
  %a_21_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_4_i16, i32 0
  %a_21_4_vsplat = shufflevector <vscale x 8 x i16> %a_21_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_4 = mul <vscale x 8 x i16> %a_21_4_vsplat, %w_21_i16
  %add_21_4 = add <vscale x 8 x i16> %mul_21_4, %add_20_4
  %a_21_5_ptr = getelementptr i8, ptr %a_21_ptr, i32 5
  %a_21_5_i8 = load i8, ptr %a_21_5_ptr
  %a_21_5_i16 = sext i8 %a_21_5_i8 to i16
  %a_21_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_5_i16, i32 0
  %a_21_5_vsplat = shufflevector <vscale x 8 x i16> %a_21_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_5 = mul <vscale x 8 x i16> %a_21_5_vsplat, %w_21_i16
  %add_21_5 = add <vscale x 8 x i16> %mul_21_5, %add_20_5
  %a_21_6_ptr = getelementptr i8, ptr %a_21_ptr, i32 6
  %a_21_6_i8 = load i8, ptr %a_21_6_ptr
  %a_21_6_i16 = sext i8 %a_21_6_i8 to i16
  %a_21_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_6_i16, i32 0
  %a_21_6_vsplat = shufflevector <vscale x 8 x i16> %a_21_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_6 = mul <vscale x 8 x i16> %a_21_6_vsplat, %w_21_i16
  %add_21_6 = add <vscale x 8 x i16> %mul_21_6, %add_20_6
  %a_21_7_ptr = getelementptr i8, ptr %a_21_ptr, i32 7
  %a_21_7_i8 = load i8, ptr %a_21_7_ptr
  %a_21_7_i16 = sext i8 %a_21_7_i8 to i16
  %a_21_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_7_i16, i32 0
  %a_21_7_vsplat = shufflevector <vscale x 8 x i16> %a_21_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_7 = mul <vscale x 8 x i16> %a_21_7_vsplat, %w_21_i16
  %add_21_7 = add <vscale x 8 x i16> %mul_21_7, %add_20_7
  %a_21_8_ptr = getelementptr i8, ptr %a_21_ptr, i32 8
  %a_21_8_i8 = load i8, ptr %a_21_8_ptr
  %a_21_8_i16 = sext i8 %a_21_8_i8 to i16
  %a_21_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_8_i16, i32 0
  %a_21_8_vsplat = shufflevector <vscale x 8 x i16> %a_21_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_8 = mul <vscale x 8 x i16> %a_21_8_vsplat, %w_21_i16
  %add_21_8 = add <vscale x 8 x i16> %mul_21_8, %add_20_8
  %a_21_9_ptr = getelementptr i8, ptr %a_21_ptr, i32 9
  %a_21_9_i8 = load i8, ptr %a_21_9_ptr
  %a_21_9_i16 = sext i8 %a_21_9_i8 to i16
  %a_21_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_9_i16, i32 0
  %a_21_9_vsplat = shufflevector <vscale x 8 x i16> %a_21_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_9 = mul <vscale x 8 x i16> %a_21_9_vsplat, %w_21_i16
  %add_21_9 = add <vscale x 8 x i16> %mul_21_9, %add_20_9
  %a_21_10_ptr = getelementptr i8, ptr %a_21_ptr, i32 10
  %a_21_10_i8 = load i8, ptr %a_21_10_ptr
  %a_21_10_i16 = sext i8 %a_21_10_i8 to i16
  %a_21_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_10_i16, i32 0
  %a_21_10_vsplat = shufflevector <vscale x 8 x i16> %a_21_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_10 = mul <vscale x 8 x i16> %a_21_10_vsplat, %w_21_i16
  %add_21_10 = add <vscale x 8 x i16> %mul_21_10, %add_20_10
  %a_21_11_ptr = getelementptr i8, ptr %a_21_ptr, i32 11
  %a_21_11_i8 = load i8, ptr %a_21_11_ptr
  %a_21_11_i16 = sext i8 %a_21_11_i8 to i16
  %a_21_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_21_11_i16, i32 0
  %a_21_11_vsplat = shufflevector <vscale x 8 x i16> %a_21_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_21_11 = mul <vscale x 8 x i16> %a_21_11_vsplat, %w_21_i16
  %add_21_11 = add <vscale x 8 x i16> %mul_21_11, %add_20_11

  %w_22_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 22
  %w_22_i8 = load <vscale x 8 x i8>, ptr %w_22_ptr
  %w_22_i16 = sext <vscale x 8 x i8> %w_22_i8 to <vscale x 8 x i16>

  %a_22_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 22
  %a_22_0_ptr = getelementptr i8, ptr %a_22_ptr, i32 0
  %a_22_0_i8 = load i8, ptr %a_22_0_ptr
  %a_22_0_i16 = sext i8 %a_22_0_i8 to i16
  %a_22_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_0_i16, i32 0
  %a_22_0_vsplat = shufflevector <vscale x 8 x i16> %a_22_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_0 = mul <vscale x 8 x i16> %a_22_0_vsplat, %w_22_i16
  %add_22_0 = add <vscale x 8 x i16> %mul_22_0, %add_21_0
  %a_22_1_ptr = getelementptr i8, ptr %a_22_ptr, i32 1
  %a_22_1_i8 = load i8, ptr %a_22_1_ptr
  %a_22_1_i16 = sext i8 %a_22_1_i8 to i16
  %a_22_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_1_i16, i32 0
  %a_22_1_vsplat = shufflevector <vscale x 8 x i16> %a_22_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_1 = mul <vscale x 8 x i16> %a_22_1_vsplat, %w_22_i16
  %add_22_1 = add <vscale x 8 x i16> %mul_22_1, %add_21_1
  %a_22_2_ptr = getelementptr i8, ptr %a_22_ptr, i32 2
  %a_22_2_i8 = load i8, ptr %a_22_2_ptr
  %a_22_2_i16 = sext i8 %a_22_2_i8 to i16
  %a_22_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_2_i16, i32 0
  %a_22_2_vsplat = shufflevector <vscale x 8 x i16> %a_22_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_2 = mul <vscale x 8 x i16> %a_22_2_vsplat, %w_22_i16
  %add_22_2 = add <vscale x 8 x i16> %mul_22_2, %add_21_2
  %a_22_3_ptr = getelementptr i8, ptr %a_22_ptr, i32 3
  %a_22_3_i8 = load i8, ptr %a_22_3_ptr
  %a_22_3_i16 = sext i8 %a_22_3_i8 to i16
  %a_22_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_3_i16, i32 0
  %a_22_3_vsplat = shufflevector <vscale x 8 x i16> %a_22_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_3 = mul <vscale x 8 x i16> %a_22_3_vsplat, %w_22_i16
  %add_22_3 = add <vscale x 8 x i16> %mul_22_3, %add_21_3
  %a_22_4_ptr = getelementptr i8, ptr %a_22_ptr, i32 4
  %a_22_4_i8 = load i8, ptr %a_22_4_ptr
  %a_22_4_i16 = sext i8 %a_22_4_i8 to i16
  %a_22_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_4_i16, i32 0
  %a_22_4_vsplat = shufflevector <vscale x 8 x i16> %a_22_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_4 = mul <vscale x 8 x i16> %a_22_4_vsplat, %w_22_i16
  %add_22_4 = add <vscale x 8 x i16> %mul_22_4, %add_21_4
  %a_22_5_ptr = getelementptr i8, ptr %a_22_ptr, i32 5
  %a_22_5_i8 = load i8, ptr %a_22_5_ptr
  %a_22_5_i16 = sext i8 %a_22_5_i8 to i16
  %a_22_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_5_i16, i32 0
  %a_22_5_vsplat = shufflevector <vscale x 8 x i16> %a_22_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_5 = mul <vscale x 8 x i16> %a_22_5_vsplat, %w_22_i16
  %add_22_5 = add <vscale x 8 x i16> %mul_22_5, %add_21_5
  %a_22_6_ptr = getelementptr i8, ptr %a_22_ptr, i32 6
  %a_22_6_i8 = load i8, ptr %a_22_6_ptr
  %a_22_6_i16 = sext i8 %a_22_6_i8 to i16
  %a_22_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_6_i16, i32 0
  %a_22_6_vsplat = shufflevector <vscale x 8 x i16> %a_22_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_6 = mul <vscale x 8 x i16> %a_22_6_vsplat, %w_22_i16
  %add_22_6 = add <vscale x 8 x i16> %mul_22_6, %add_21_6
  %a_22_7_ptr = getelementptr i8, ptr %a_22_ptr, i32 7
  %a_22_7_i8 = load i8, ptr %a_22_7_ptr
  %a_22_7_i16 = sext i8 %a_22_7_i8 to i16
  %a_22_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_7_i16, i32 0
  %a_22_7_vsplat = shufflevector <vscale x 8 x i16> %a_22_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_7 = mul <vscale x 8 x i16> %a_22_7_vsplat, %w_22_i16
  %add_22_7 = add <vscale x 8 x i16> %mul_22_7, %add_21_7
  %a_22_8_ptr = getelementptr i8, ptr %a_22_ptr, i32 8
  %a_22_8_i8 = load i8, ptr %a_22_8_ptr
  %a_22_8_i16 = sext i8 %a_22_8_i8 to i16
  %a_22_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_8_i16, i32 0
  %a_22_8_vsplat = shufflevector <vscale x 8 x i16> %a_22_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_8 = mul <vscale x 8 x i16> %a_22_8_vsplat, %w_22_i16
  %add_22_8 = add <vscale x 8 x i16> %mul_22_8, %add_21_8
  %a_22_9_ptr = getelementptr i8, ptr %a_22_ptr, i32 9
  %a_22_9_i8 = load i8, ptr %a_22_9_ptr
  %a_22_9_i16 = sext i8 %a_22_9_i8 to i16
  %a_22_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_9_i16, i32 0
  %a_22_9_vsplat = shufflevector <vscale x 8 x i16> %a_22_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_9 = mul <vscale x 8 x i16> %a_22_9_vsplat, %w_22_i16
  %add_22_9 = add <vscale x 8 x i16> %mul_22_9, %add_21_9
  %a_22_10_ptr = getelementptr i8, ptr %a_22_ptr, i32 10
  %a_22_10_i8 = load i8, ptr %a_22_10_ptr
  %a_22_10_i16 = sext i8 %a_22_10_i8 to i16
  %a_22_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_10_i16, i32 0
  %a_22_10_vsplat = shufflevector <vscale x 8 x i16> %a_22_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_10 = mul <vscale x 8 x i16> %a_22_10_vsplat, %w_22_i16
  %add_22_10 = add <vscale x 8 x i16> %mul_22_10, %add_21_10
  %a_22_11_ptr = getelementptr i8, ptr %a_22_ptr, i32 11
  %a_22_11_i8 = load i8, ptr %a_22_11_ptr
  %a_22_11_i16 = sext i8 %a_22_11_i8 to i16
  %a_22_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_22_11_i16, i32 0
  %a_22_11_vsplat = shufflevector <vscale x 8 x i16> %a_22_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_22_11 = mul <vscale x 8 x i16> %a_22_11_vsplat, %w_22_i16
  %add_22_11 = add <vscale x 8 x i16> %mul_22_11, %add_21_11

  %w_23_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 23
  %w_23_i8 = load <vscale x 8 x i8>, ptr %w_23_ptr
  %w_23_i16 = sext <vscale x 8 x i8> %w_23_i8 to <vscale x 8 x i16>

  %a_23_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 23
  %a_23_0_ptr = getelementptr i8, ptr %a_23_ptr, i32 0
  %a_23_0_i8 = load i8, ptr %a_23_0_ptr
  %a_23_0_i16 = sext i8 %a_23_0_i8 to i16
  %a_23_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_0_i16, i32 0
  %a_23_0_vsplat = shufflevector <vscale x 8 x i16> %a_23_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_0 = mul <vscale x 8 x i16> %a_23_0_vsplat, %w_23_i16
  %add_23_0 = add <vscale x 8 x i16> %mul_23_0, %add_22_0
  %a_23_1_ptr = getelementptr i8, ptr %a_23_ptr, i32 1
  %a_23_1_i8 = load i8, ptr %a_23_1_ptr
  %a_23_1_i16 = sext i8 %a_23_1_i8 to i16
  %a_23_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_1_i16, i32 0
  %a_23_1_vsplat = shufflevector <vscale x 8 x i16> %a_23_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_1 = mul <vscale x 8 x i16> %a_23_1_vsplat, %w_23_i16
  %add_23_1 = add <vscale x 8 x i16> %mul_23_1, %add_22_1
  %a_23_2_ptr = getelementptr i8, ptr %a_23_ptr, i32 2
  %a_23_2_i8 = load i8, ptr %a_23_2_ptr
  %a_23_2_i16 = sext i8 %a_23_2_i8 to i16
  %a_23_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_2_i16, i32 0
  %a_23_2_vsplat = shufflevector <vscale x 8 x i16> %a_23_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_2 = mul <vscale x 8 x i16> %a_23_2_vsplat, %w_23_i16
  %add_23_2 = add <vscale x 8 x i16> %mul_23_2, %add_22_2
  %a_23_3_ptr = getelementptr i8, ptr %a_23_ptr, i32 3
  %a_23_3_i8 = load i8, ptr %a_23_3_ptr
  %a_23_3_i16 = sext i8 %a_23_3_i8 to i16
  %a_23_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_3_i16, i32 0
  %a_23_3_vsplat = shufflevector <vscale x 8 x i16> %a_23_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_3 = mul <vscale x 8 x i16> %a_23_3_vsplat, %w_23_i16
  %add_23_3 = add <vscale x 8 x i16> %mul_23_3, %add_22_3
  %a_23_4_ptr = getelementptr i8, ptr %a_23_ptr, i32 4
  %a_23_4_i8 = load i8, ptr %a_23_4_ptr
  %a_23_4_i16 = sext i8 %a_23_4_i8 to i16
  %a_23_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_4_i16, i32 0
  %a_23_4_vsplat = shufflevector <vscale x 8 x i16> %a_23_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_4 = mul <vscale x 8 x i16> %a_23_4_vsplat, %w_23_i16
  %add_23_4 = add <vscale x 8 x i16> %mul_23_4, %add_22_4
  %a_23_5_ptr = getelementptr i8, ptr %a_23_ptr, i32 5
  %a_23_5_i8 = load i8, ptr %a_23_5_ptr
  %a_23_5_i16 = sext i8 %a_23_5_i8 to i16
  %a_23_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_5_i16, i32 0
  %a_23_5_vsplat = shufflevector <vscale x 8 x i16> %a_23_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_5 = mul <vscale x 8 x i16> %a_23_5_vsplat, %w_23_i16
  %add_23_5 = add <vscale x 8 x i16> %mul_23_5, %add_22_5
  %a_23_6_ptr = getelementptr i8, ptr %a_23_ptr, i32 6
  %a_23_6_i8 = load i8, ptr %a_23_6_ptr
  %a_23_6_i16 = sext i8 %a_23_6_i8 to i16
  %a_23_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_6_i16, i32 0
  %a_23_6_vsplat = shufflevector <vscale x 8 x i16> %a_23_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_6 = mul <vscale x 8 x i16> %a_23_6_vsplat, %w_23_i16
  %add_23_6 = add <vscale x 8 x i16> %mul_23_6, %add_22_6
  %a_23_7_ptr = getelementptr i8, ptr %a_23_ptr, i32 7
  %a_23_7_i8 = load i8, ptr %a_23_7_ptr
  %a_23_7_i16 = sext i8 %a_23_7_i8 to i16
  %a_23_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_7_i16, i32 0
  %a_23_7_vsplat = shufflevector <vscale x 8 x i16> %a_23_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_7 = mul <vscale x 8 x i16> %a_23_7_vsplat, %w_23_i16
  %add_23_7 = add <vscale x 8 x i16> %mul_23_7, %add_22_7
  %a_23_8_ptr = getelementptr i8, ptr %a_23_ptr, i32 8
  %a_23_8_i8 = load i8, ptr %a_23_8_ptr
  %a_23_8_i16 = sext i8 %a_23_8_i8 to i16
  %a_23_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_8_i16, i32 0
  %a_23_8_vsplat = shufflevector <vscale x 8 x i16> %a_23_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_8 = mul <vscale x 8 x i16> %a_23_8_vsplat, %w_23_i16
  %add_23_8 = add <vscale x 8 x i16> %mul_23_8, %add_22_8
  %a_23_9_ptr = getelementptr i8, ptr %a_23_ptr, i32 9
  %a_23_9_i8 = load i8, ptr %a_23_9_ptr
  %a_23_9_i16 = sext i8 %a_23_9_i8 to i16
  %a_23_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_9_i16, i32 0
  %a_23_9_vsplat = shufflevector <vscale x 8 x i16> %a_23_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_9 = mul <vscale x 8 x i16> %a_23_9_vsplat, %w_23_i16
  %add_23_9 = add <vscale x 8 x i16> %mul_23_9, %add_22_9
  %a_23_10_ptr = getelementptr i8, ptr %a_23_ptr, i32 10
  %a_23_10_i8 = load i8, ptr %a_23_10_ptr
  %a_23_10_i16 = sext i8 %a_23_10_i8 to i16
  %a_23_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_10_i16, i32 0
  %a_23_10_vsplat = shufflevector <vscale x 8 x i16> %a_23_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_10 = mul <vscale x 8 x i16> %a_23_10_vsplat, %w_23_i16
  %add_23_10 = add <vscale x 8 x i16> %mul_23_10, %add_22_10
  %a_23_11_ptr = getelementptr i8, ptr %a_23_ptr, i32 11
  %a_23_11_i8 = load i8, ptr %a_23_11_ptr
  %a_23_11_i16 = sext i8 %a_23_11_i8 to i16
  %a_23_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_23_11_i16, i32 0
  %a_23_11_vsplat = shufflevector <vscale x 8 x i16> %a_23_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_23_11 = mul <vscale x 8 x i16> %a_23_11_vsplat, %w_23_i16
  %add_23_11 = add <vscale x 8 x i16> %mul_23_11, %add_22_11

  %w_24_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 24
  %w_24_i8 = load <vscale x 8 x i8>, ptr %w_24_ptr
  %w_24_i16 = sext <vscale x 8 x i8> %w_24_i8 to <vscale x 8 x i16>

  %a_24_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 24
  %a_24_0_ptr = getelementptr i8, ptr %a_24_ptr, i32 0
  %a_24_0_i8 = load i8, ptr %a_24_0_ptr
  %a_24_0_i16 = sext i8 %a_24_0_i8 to i16
  %a_24_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_0_i16, i32 0
  %a_24_0_vsplat = shufflevector <vscale x 8 x i16> %a_24_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_0 = mul <vscale x 8 x i16> %a_24_0_vsplat, %w_24_i16
  %add_24_0 = add <vscale x 8 x i16> %mul_24_0, %add_23_0
  %a_24_1_ptr = getelementptr i8, ptr %a_24_ptr, i32 1
  %a_24_1_i8 = load i8, ptr %a_24_1_ptr
  %a_24_1_i16 = sext i8 %a_24_1_i8 to i16
  %a_24_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_1_i16, i32 0
  %a_24_1_vsplat = shufflevector <vscale x 8 x i16> %a_24_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_1 = mul <vscale x 8 x i16> %a_24_1_vsplat, %w_24_i16
  %add_24_1 = add <vscale x 8 x i16> %mul_24_1, %add_23_1
  %a_24_2_ptr = getelementptr i8, ptr %a_24_ptr, i32 2
  %a_24_2_i8 = load i8, ptr %a_24_2_ptr
  %a_24_2_i16 = sext i8 %a_24_2_i8 to i16
  %a_24_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_2_i16, i32 0
  %a_24_2_vsplat = shufflevector <vscale x 8 x i16> %a_24_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_2 = mul <vscale x 8 x i16> %a_24_2_vsplat, %w_24_i16
  %add_24_2 = add <vscale x 8 x i16> %mul_24_2, %add_23_2
  %a_24_3_ptr = getelementptr i8, ptr %a_24_ptr, i32 3
  %a_24_3_i8 = load i8, ptr %a_24_3_ptr
  %a_24_3_i16 = sext i8 %a_24_3_i8 to i16
  %a_24_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_3_i16, i32 0
  %a_24_3_vsplat = shufflevector <vscale x 8 x i16> %a_24_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_3 = mul <vscale x 8 x i16> %a_24_3_vsplat, %w_24_i16
  %add_24_3 = add <vscale x 8 x i16> %mul_24_3, %add_23_3
  %a_24_4_ptr = getelementptr i8, ptr %a_24_ptr, i32 4
  %a_24_4_i8 = load i8, ptr %a_24_4_ptr
  %a_24_4_i16 = sext i8 %a_24_4_i8 to i16
  %a_24_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_4_i16, i32 0
  %a_24_4_vsplat = shufflevector <vscale x 8 x i16> %a_24_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_4 = mul <vscale x 8 x i16> %a_24_4_vsplat, %w_24_i16
  %add_24_4 = add <vscale x 8 x i16> %mul_24_4, %add_23_4
  %a_24_5_ptr = getelementptr i8, ptr %a_24_ptr, i32 5
  %a_24_5_i8 = load i8, ptr %a_24_5_ptr
  %a_24_5_i16 = sext i8 %a_24_5_i8 to i16
  %a_24_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_5_i16, i32 0
  %a_24_5_vsplat = shufflevector <vscale x 8 x i16> %a_24_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_5 = mul <vscale x 8 x i16> %a_24_5_vsplat, %w_24_i16
  %add_24_5 = add <vscale x 8 x i16> %mul_24_5, %add_23_5
  %a_24_6_ptr = getelementptr i8, ptr %a_24_ptr, i32 6
  %a_24_6_i8 = load i8, ptr %a_24_6_ptr
  %a_24_6_i16 = sext i8 %a_24_6_i8 to i16
  %a_24_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_6_i16, i32 0
  %a_24_6_vsplat = shufflevector <vscale x 8 x i16> %a_24_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_6 = mul <vscale x 8 x i16> %a_24_6_vsplat, %w_24_i16
  %add_24_6 = add <vscale x 8 x i16> %mul_24_6, %add_23_6
  %a_24_7_ptr = getelementptr i8, ptr %a_24_ptr, i32 7
  %a_24_7_i8 = load i8, ptr %a_24_7_ptr
  %a_24_7_i16 = sext i8 %a_24_7_i8 to i16
  %a_24_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_7_i16, i32 0
  %a_24_7_vsplat = shufflevector <vscale x 8 x i16> %a_24_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_7 = mul <vscale x 8 x i16> %a_24_7_vsplat, %w_24_i16
  %add_24_7 = add <vscale x 8 x i16> %mul_24_7, %add_23_7
  %a_24_8_ptr = getelementptr i8, ptr %a_24_ptr, i32 8
  %a_24_8_i8 = load i8, ptr %a_24_8_ptr
  %a_24_8_i16 = sext i8 %a_24_8_i8 to i16
  %a_24_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_8_i16, i32 0
  %a_24_8_vsplat = shufflevector <vscale x 8 x i16> %a_24_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_8 = mul <vscale x 8 x i16> %a_24_8_vsplat, %w_24_i16
  %add_24_8 = add <vscale x 8 x i16> %mul_24_8, %add_23_8
  %a_24_9_ptr = getelementptr i8, ptr %a_24_ptr, i32 9
  %a_24_9_i8 = load i8, ptr %a_24_9_ptr
  %a_24_9_i16 = sext i8 %a_24_9_i8 to i16
  %a_24_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_9_i16, i32 0
  %a_24_9_vsplat = shufflevector <vscale x 8 x i16> %a_24_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_9 = mul <vscale x 8 x i16> %a_24_9_vsplat, %w_24_i16
  %add_24_9 = add <vscale x 8 x i16> %mul_24_9, %add_23_9
  %a_24_10_ptr = getelementptr i8, ptr %a_24_ptr, i32 10
  %a_24_10_i8 = load i8, ptr %a_24_10_ptr
  %a_24_10_i16 = sext i8 %a_24_10_i8 to i16
  %a_24_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_10_i16, i32 0
  %a_24_10_vsplat = shufflevector <vscale x 8 x i16> %a_24_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_10 = mul <vscale x 8 x i16> %a_24_10_vsplat, %w_24_i16
  %add_24_10 = add <vscale x 8 x i16> %mul_24_10, %add_23_10
  %a_24_11_ptr = getelementptr i8, ptr %a_24_ptr, i32 11
  %a_24_11_i8 = load i8, ptr %a_24_11_ptr
  %a_24_11_i16 = sext i8 %a_24_11_i8 to i16
  %a_24_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_24_11_i16, i32 0
  %a_24_11_vsplat = shufflevector <vscale x 8 x i16> %a_24_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_24_11 = mul <vscale x 8 x i16> %a_24_11_vsplat, %w_24_i16
  %add_24_11 = add <vscale x 8 x i16> %mul_24_11, %add_23_11

  %w_25_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 25
  %w_25_i8 = load <vscale x 8 x i8>, ptr %w_25_ptr
  %w_25_i16 = sext <vscale x 8 x i8> %w_25_i8 to <vscale x 8 x i16>

  %a_25_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 25
  %a_25_0_ptr = getelementptr i8, ptr %a_25_ptr, i32 0
  %a_25_0_i8 = load i8, ptr %a_25_0_ptr
  %a_25_0_i16 = sext i8 %a_25_0_i8 to i16
  %a_25_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_0_i16, i32 0
  %a_25_0_vsplat = shufflevector <vscale x 8 x i16> %a_25_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_0 = mul <vscale x 8 x i16> %a_25_0_vsplat, %w_25_i16
  %add_25_0 = add <vscale x 8 x i16> %mul_25_0, %add_24_0
  %a_25_1_ptr = getelementptr i8, ptr %a_25_ptr, i32 1
  %a_25_1_i8 = load i8, ptr %a_25_1_ptr
  %a_25_1_i16 = sext i8 %a_25_1_i8 to i16
  %a_25_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_1_i16, i32 0
  %a_25_1_vsplat = shufflevector <vscale x 8 x i16> %a_25_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_1 = mul <vscale x 8 x i16> %a_25_1_vsplat, %w_25_i16
  %add_25_1 = add <vscale x 8 x i16> %mul_25_1, %add_24_1
  %a_25_2_ptr = getelementptr i8, ptr %a_25_ptr, i32 2
  %a_25_2_i8 = load i8, ptr %a_25_2_ptr
  %a_25_2_i16 = sext i8 %a_25_2_i8 to i16
  %a_25_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_2_i16, i32 0
  %a_25_2_vsplat = shufflevector <vscale x 8 x i16> %a_25_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_2 = mul <vscale x 8 x i16> %a_25_2_vsplat, %w_25_i16
  %add_25_2 = add <vscale x 8 x i16> %mul_25_2, %add_24_2
  %a_25_3_ptr = getelementptr i8, ptr %a_25_ptr, i32 3
  %a_25_3_i8 = load i8, ptr %a_25_3_ptr
  %a_25_3_i16 = sext i8 %a_25_3_i8 to i16
  %a_25_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_3_i16, i32 0
  %a_25_3_vsplat = shufflevector <vscale x 8 x i16> %a_25_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_3 = mul <vscale x 8 x i16> %a_25_3_vsplat, %w_25_i16
  %add_25_3 = add <vscale x 8 x i16> %mul_25_3, %add_24_3
  %a_25_4_ptr = getelementptr i8, ptr %a_25_ptr, i32 4
  %a_25_4_i8 = load i8, ptr %a_25_4_ptr
  %a_25_4_i16 = sext i8 %a_25_4_i8 to i16
  %a_25_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_4_i16, i32 0
  %a_25_4_vsplat = shufflevector <vscale x 8 x i16> %a_25_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_4 = mul <vscale x 8 x i16> %a_25_4_vsplat, %w_25_i16
  %add_25_4 = add <vscale x 8 x i16> %mul_25_4, %add_24_4
  %a_25_5_ptr = getelementptr i8, ptr %a_25_ptr, i32 5
  %a_25_5_i8 = load i8, ptr %a_25_5_ptr
  %a_25_5_i16 = sext i8 %a_25_5_i8 to i16
  %a_25_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_5_i16, i32 0
  %a_25_5_vsplat = shufflevector <vscale x 8 x i16> %a_25_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_5 = mul <vscale x 8 x i16> %a_25_5_vsplat, %w_25_i16
  %add_25_5 = add <vscale x 8 x i16> %mul_25_5, %add_24_5
  %a_25_6_ptr = getelementptr i8, ptr %a_25_ptr, i32 6
  %a_25_6_i8 = load i8, ptr %a_25_6_ptr
  %a_25_6_i16 = sext i8 %a_25_6_i8 to i16
  %a_25_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_6_i16, i32 0
  %a_25_6_vsplat = shufflevector <vscale x 8 x i16> %a_25_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_6 = mul <vscale x 8 x i16> %a_25_6_vsplat, %w_25_i16
  %add_25_6 = add <vscale x 8 x i16> %mul_25_6, %add_24_6
  %a_25_7_ptr = getelementptr i8, ptr %a_25_ptr, i32 7
  %a_25_7_i8 = load i8, ptr %a_25_7_ptr
  %a_25_7_i16 = sext i8 %a_25_7_i8 to i16
  %a_25_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_7_i16, i32 0
  %a_25_7_vsplat = shufflevector <vscale x 8 x i16> %a_25_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_7 = mul <vscale x 8 x i16> %a_25_7_vsplat, %w_25_i16
  %add_25_7 = add <vscale x 8 x i16> %mul_25_7, %add_24_7
  %a_25_8_ptr = getelementptr i8, ptr %a_25_ptr, i32 8
  %a_25_8_i8 = load i8, ptr %a_25_8_ptr
  %a_25_8_i16 = sext i8 %a_25_8_i8 to i16
  %a_25_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_8_i16, i32 0
  %a_25_8_vsplat = shufflevector <vscale x 8 x i16> %a_25_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_8 = mul <vscale x 8 x i16> %a_25_8_vsplat, %w_25_i16
  %add_25_8 = add <vscale x 8 x i16> %mul_25_8, %add_24_8
  %a_25_9_ptr = getelementptr i8, ptr %a_25_ptr, i32 9
  %a_25_9_i8 = load i8, ptr %a_25_9_ptr
  %a_25_9_i16 = sext i8 %a_25_9_i8 to i16
  %a_25_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_9_i16, i32 0
  %a_25_9_vsplat = shufflevector <vscale x 8 x i16> %a_25_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_9 = mul <vscale x 8 x i16> %a_25_9_vsplat, %w_25_i16
  %add_25_9 = add <vscale x 8 x i16> %mul_25_9, %add_24_9
  %a_25_10_ptr = getelementptr i8, ptr %a_25_ptr, i32 10
  %a_25_10_i8 = load i8, ptr %a_25_10_ptr
  %a_25_10_i16 = sext i8 %a_25_10_i8 to i16
  %a_25_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_10_i16, i32 0
  %a_25_10_vsplat = shufflevector <vscale x 8 x i16> %a_25_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_10 = mul <vscale x 8 x i16> %a_25_10_vsplat, %w_25_i16
  %add_25_10 = add <vscale x 8 x i16> %mul_25_10, %add_24_10
  %a_25_11_ptr = getelementptr i8, ptr %a_25_ptr, i32 11
  %a_25_11_i8 = load i8, ptr %a_25_11_ptr
  %a_25_11_i16 = sext i8 %a_25_11_i8 to i16
  %a_25_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_25_11_i16, i32 0
  %a_25_11_vsplat = shufflevector <vscale x 8 x i16> %a_25_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_25_11 = mul <vscale x 8 x i16> %a_25_11_vsplat, %w_25_i16
  %add_25_11 = add <vscale x 8 x i16> %mul_25_11, %add_24_11

  %w_26_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 26
  %w_26_i8 = load <vscale x 8 x i8>, ptr %w_26_ptr
  %w_26_i16 = sext <vscale x 8 x i8> %w_26_i8 to <vscale x 8 x i16>

  %a_26_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 26
  %a_26_0_ptr = getelementptr i8, ptr %a_26_ptr, i32 0
  %a_26_0_i8 = load i8, ptr %a_26_0_ptr
  %a_26_0_i16 = sext i8 %a_26_0_i8 to i16
  %a_26_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_0_i16, i32 0
  %a_26_0_vsplat = shufflevector <vscale x 8 x i16> %a_26_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_0 = mul <vscale x 8 x i16> %a_26_0_vsplat, %w_26_i16
  %add_26_0 = add <vscale x 8 x i16> %mul_26_0, %add_25_0
  %a_26_1_ptr = getelementptr i8, ptr %a_26_ptr, i32 1
  %a_26_1_i8 = load i8, ptr %a_26_1_ptr
  %a_26_1_i16 = sext i8 %a_26_1_i8 to i16
  %a_26_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_1_i16, i32 0
  %a_26_1_vsplat = shufflevector <vscale x 8 x i16> %a_26_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_1 = mul <vscale x 8 x i16> %a_26_1_vsplat, %w_26_i16
  %add_26_1 = add <vscale x 8 x i16> %mul_26_1, %add_25_1
  %a_26_2_ptr = getelementptr i8, ptr %a_26_ptr, i32 2
  %a_26_2_i8 = load i8, ptr %a_26_2_ptr
  %a_26_2_i16 = sext i8 %a_26_2_i8 to i16
  %a_26_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_2_i16, i32 0
  %a_26_2_vsplat = shufflevector <vscale x 8 x i16> %a_26_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_2 = mul <vscale x 8 x i16> %a_26_2_vsplat, %w_26_i16
  %add_26_2 = add <vscale x 8 x i16> %mul_26_2, %add_25_2
  %a_26_3_ptr = getelementptr i8, ptr %a_26_ptr, i32 3
  %a_26_3_i8 = load i8, ptr %a_26_3_ptr
  %a_26_3_i16 = sext i8 %a_26_3_i8 to i16
  %a_26_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_3_i16, i32 0
  %a_26_3_vsplat = shufflevector <vscale x 8 x i16> %a_26_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_3 = mul <vscale x 8 x i16> %a_26_3_vsplat, %w_26_i16
  %add_26_3 = add <vscale x 8 x i16> %mul_26_3, %add_25_3
  %a_26_4_ptr = getelementptr i8, ptr %a_26_ptr, i32 4
  %a_26_4_i8 = load i8, ptr %a_26_4_ptr
  %a_26_4_i16 = sext i8 %a_26_4_i8 to i16
  %a_26_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_4_i16, i32 0
  %a_26_4_vsplat = shufflevector <vscale x 8 x i16> %a_26_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_4 = mul <vscale x 8 x i16> %a_26_4_vsplat, %w_26_i16
  %add_26_4 = add <vscale x 8 x i16> %mul_26_4, %add_25_4
  %a_26_5_ptr = getelementptr i8, ptr %a_26_ptr, i32 5
  %a_26_5_i8 = load i8, ptr %a_26_5_ptr
  %a_26_5_i16 = sext i8 %a_26_5_i8 to i16
  %a_26_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_5_i16, i32 0
  %a_26_5_vsplat = shufflevector <vscale x 8 x i16> %a_26_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_5 = mul <vscale x 8 x i16> %a_26_5_vsplat, %w_26_i16
  %add_26_5 = add <vscale x 8 x i16> %mul_26_5, %add_25_5
  %a_26_6_ptr = getelementptr i8, ptr %a_26_ptr, i32 6
  %a_26_6_i8 = load i8, ptr %a_26_6_ptr
  %a_26_6_i16 = sext i8 %a_26_6_i8 to i16
  %a_26_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_6_i16, i32 0
  %a_26_6_vsplat = shufflevector <vscale x 8 x i16> %a_26_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_6 = mul <vscale x 8 x i16> %a_26_6_vsplat, %w_26_i16
  %add_26_6 = add <vscale x 8 x i16> %mul_26_6, %add_25_6
  %a_26_7_ptr = getelementptr i8, ptr %a_26_ptr, i32 7
  %a_26_7_i8 = load i8, ptr %a_26_7_ptr
  %a_26_7_i16 = sext i8 %a_26_7_i8 to i16
  %a_26_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_7_i16, i32 0
  %a_26_7_vsplat = shufflevector <vscale x 8 x i16> %a_26_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_7 = mul <vscale x 8 x i16> %a_26_7_vsplat, %w_26_i16
  %add_26_7 = add <vscale x 8 x i16> %mul_26_7, %add_25_7
  %a_26_8_ptr = getelementptr i8, ptr %a_26_ptr, i32 8
  %a_26_8_i8 = load i8, ptr %a_26_8_ptr
  %a_26_8_i16 = sext i8 %a_26_8_i8 to i16
  %a_26_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_8_i16, i32 0
  %a_26_8_vsplat = shufflevector <vscale x 8 x i16> %a_26_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_8 = mul <vscale x 8 x i16> %a_26_8_vsplat, %w_26_i16
  %add_26_8 = add <vscale x 8 x i16> %mul_26_8, %add_25_8
  %a_26_9_ptr = getelementptr i8, ptr %a_26_ptr, i32 9
  %a_26_9_i8 = load i8, ptr %a_26_9_ptr
  %a_26_9_i16 = sext i8 %a_26_9_i8 to i16
  %a_26_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_9_i16, i32 0
  %a_26_9_vsplat = shufflevector <vscale x 8 x i16> %a_26_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_9 = mul <vscale x 8 x i16> %a_26_9_vsplat, %w_26_i16
  %add_26_9 = add <vscale x 8 x i16> %mul_26_9, %add_25_9
  %a_26_10_ptr = getelementptr i8, ptr %a_26_ptr, i32 10
  %a_26_10_i8 = load i8, ptr %a_26_10_ptr
  %a_26_10_i16 = sext i8 %a_26_10_i8 to i16
  %a_26_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_10_i16, i32 0
  %a_26_10_vsplat = shufflevector <vscale x 8 x i16> %a_26_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_10 = mul <vscale x 8 x i16> %a_26_10_vsplat, %w_26_i16
  %add_26_10 = add <vscale x 8 x i16> %mul_26_10, %add_25_10
  %a_26_11_ptr = getelementptr i8, ptr %a_26_ptr, i32 11
  %a_26_11_i8 = load i8, ptr %a_26_11_ptr
  %a_26_11_i16 = sext i8 %a_26_11_i8 to i16
  %a_26_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_26_11_i16, i32 0
  %a_26_11_vsplat = shufflevector <vscale x 8 x i16> %a_26_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_26_11 = mul <vscale x 8 x i16> %a_26_11_vsplat, %w_26_i16
  %add_26_11 = add <vscale x 8 x i16> %mul_26_11, %add_25_11

  %w_27_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 27
  %w_27_i8 = load <vscale x 8 x i8>, ptr %w_27_ptr
  %w_27_i16 = sext <vscale x 8 x i8> %w_27_i8 to <vscale x 8 x i16>

  %a_27_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 27
  %a_27_0_ptr = getelementptr i8, ptr %a_27_ptr, i32 0
  %a_27_0_i8 = load i8, ptr %a_27_0_ptr
  %a_27_0_i16 = sext i8 %a_27_0_i8 to i16
  %a_27_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_0_i16, i32 0
  %a_27_0_vsplat = shufflevector <vscale x 8 x i16> %a_27_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_0 = mul <vscale x 8 x i16> %a_27_0_vsplat, %w_27_i16
  %add_27_0 = add <vscale x 8 x i16> %mul_27_0, %add_26_0
  %a_27_1_ptr = getelementptr i8, ptr %a_27_ptr, i32 1
  %a_27_1_i8 = load i8, ptr %a_27_1_ptr
  %a_27_1_i16 = sext i8 %a_27_1_i8 to i16
  %a_27_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_1_i16, i32 0
  %a_27_1_vsplat = shufflevector <vscale x 8 x i16> %a_27_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_1 = mul <vscale x 8 x i16> %a_27_1_vsplat, %w_27_i16
  %add_27_1 = add <vscale x 8 x i16> %mul_27_1, %add_26_1
  %a_27_2_ptr = getelementptr i8, ptr %a_27_ptr, i32 2
  %a_27_2_i8 = load i8, ptr %a_27_2_ptr
  %a_27_2_i16 = sext i8 %a_27_2_i8 to i16
  %a_27_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_2_i16, i32 0
  %a_27_2_vsplat = shufflevector <vscale x 8 x i16> %a_27_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_2 = mul <vscale x 8 x i16> %a_27_2_vsplat, %w_27_i16
  %add_27_2 = add <vscale x 8 x i16> %mul_27_2, %add_26_2
  %a_27_3_ptr = getelementptr i8, ptr %a_27_ptr, i32 3
  %a_27_3_i8 = load i8, ptr %a_27_3_ptr
  %a_27_3_i16 = sext i8 %a_27_3_i8 to i16
  %a_27_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_3_i16, i32 0
  %a_27_3_vsplat = shufflevector <vscale x 8 x i16> %a_27_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_3 = mul <vscale x 8 x i16> %a_27_3_vsplat, %w_27_i16
  %add_27_3 = add <vscale x 8 x i16> %mul_27_3, %add_26_3
  %a_27_4_ptr = getelementptr i8, ptr %a_27_ptr, i32 4
  %a_27_4_i8 = load i8, ptr %a_27_4_ptr
  %a_27_4_i16 = sext i8 %a_27_4_i8 to i16
  %a_27_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_4_i16, i32 0
  %a_27_4_vsplat = shufflevector <vscale x 8 x i16> %a_27_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_4 = mul <vscale x 8 x i16> %a_27_4_vsplat, %w_27_i16
  %add_27_4 = add <vscale x 8 x i16> %mul_27_4, %add_26_4
  %a_27_5_ptr = getelementptr i8, ptr %a_27_ptr, i32 5
  %a_27_5_i8 = load i8, ptr %a_27_5_ptr
  %a_27_5_i16 = sext i8 %a_27_5_i8 to i16
  %a_27_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_5_i16, i32 0
  %a_27_5_vsplat = shufflevector <vscale x 8 x i16> %a_27_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_5 = mul <vscale x 8 x i16> %a_27_5_vsplat, %w_27_i16
  %add_27_5 = add <vscale x 8 x i16> %mul_27_5, %add_26_5
  %a_27_6_ptr = getelementptr i8, ptr %a_27_ptr, i32 6
  %a_27_6_i8 = load i8, ptr %a_27_6_ptr
  %a_27_6_i16 = sext i8 %a_27_6_i8 to i16
  %a_27_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_6_i16, i32 0
  %a_27_6_vsplat = shufflevector <vscale x 8 x i16> %a_27_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_6 = mul <vscale x 8 x i16> %a_27_6_vsplat, %w_27_i16
  %add_27_6 = add <vscale x 8 x i16> %mul_27_6, %add_26_6
  %a_27_7_ptr = getelementptr i8, ptr %a_27_ptr, i32 7
  %a_27_7_i8 = load i8, ptr %a_27_7_ptr
  %a_27_7_i16 = sext i8 %a_27_7_i8 to i16
  %a_27_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_7_i16, i32 0
  %a_27_7_vsplat = shufflevector <vscale x 8 x i16> %a_27_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_7 = mul <vscale x 8 x i16> %a_27_7_vsplat, %w_27_i16
  %add_27_7 = add <vscale x 8 x i16> %mul_27_7, %add_26_7
  %a_27_8_ptr = getelementptr i8, ptr %a_27_ptr, i32 8
  %a_27_8_i8 = load i8, ptr %a_27_8_ptr
  %a_27_8_i16 = sext i8 %a_27_8_i8 to i16
  %a_27_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_8_i16, i32 0
  %a_27_8_vsplat = shufflevector <vscale x 8 x i16> %a_27_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_8 = mul <vscale x 8 x i16> %a_27_8_vsplat, %w_27_i16
  %add_27_8 = add <vscale x 8 x i16> %mul_27_8, %add_26_8
  %a_27_9_ptr = getelementptr i8, ptr %a_27_ptr, i32 9
  %a_27_9_i8 = load i8, ptr %a_27_9_ptr
  %a_27_9_i16 = sext i8 %a_27_9_i8 to i16
  %a_27_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_9_i16, i32 0
  %a_27_9_vsplat = shufflevector <vscale x 8 x i16> %a_27_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_9 = mul <vscale x 8 x i16> %a_27_9_vsplat, %w_27_i16
  %add_27_9 = add <vscale x 8 x i16> %mul_27_9, %add_26_9
  %a_27_10_ptr = getelementptr i8, ptr %a_27_ptr, i32 10
  %a_27_10_i8 = load i8, ptr %a_27_10_ptr
  %a_27_10_i16 = sext i8 %a_27_10_i8 to i16
  %a_27_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_10_i16, i32 0
  %a_27_10_vsplat = shufflevector <vscale x 8 x i16> %a_27_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_10 = mul <vscale x 8 x i16> %a_27_10_vsplat, %w_27_i16
  %add_27_10 = add <vscale x 8 x i16> %mul_27_10, %add_26_10
  %a_27_11_ptr = getelementptr i8, ptr %a_27_ptr, i32 11
  %a_27_11_i8 = load i8, ptr %a_27_11_ptr
  %a_27_11_i16 = sext i8 %a_27_11_i8 to i16
  %a_27_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_27_11_i16, i32 0
  %a_27_11_vsplat = shufflevector <vscale x 8 x i16> %a_27_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_27_11 = mul <vscale x 8 x i16> %a_27_11_vsplat, %w_27_i16
  %add_27_11 = add <vscale x 8 x i16> %mul_27_11, %add_26_11

  %w_28_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 28
  %w_28_i8 = load <vscale x 8 x i8>, ptr %w_28_ptr
  %w_28_i16 = sext <vscale x 8 x i8> %w_28_i8 to <vscale x 8 x i16>

  %a_28_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 28
  %a_28_0_ptr = getelementptr i8, ptr %a_28_ptr, i32 0
  %a_28_0_i8 = load i8, ptr %a_28_0_ptr
  %a_28_0_i16 = sext i8 %a_28_0_i8 to i16
  %a_28_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_0_i16, i32 0
  %a_28_0_vsplat = shufflevector <vscale x 8 x i16> %a_28_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_0 = mul <vscale x 8 x i16> %a_28_0_vsplat, %w_28_i16
  %add_28_0 = add <vscale x 8 x i16> %mul_28_0, %add_27_0
  %a_28_1_ptr = getelementptr i8, ptr %a_28_ptr, i32 1
  %a_28_1_i8 = load i8, ptr %a_28_1_ptr
  %a_28_1_i16 = sext i8 %a_28_1_i8 to i16
  %a_28_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_1_i16, i32 0
  %a_28_1_vsplat = shufflevector <vscale x 8 x i16> %a_28_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_1 = mul <vscale x 8 x i16> %a_28_1_vsplat, %w_28_i16
  %add_28_1 = add <vscale x 8 x i16> %mul_28_1, %add_27_1
  %a_28_2_ptr = getelementptr i8, ptr %a_28_ptr, i32 2
  %a_28_2_i8 = load i8, ptr %a_28_2_ptr
  %a_28_2_i16 = sext i8 %a_28_2_i8 to i16
  %a_28_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_2_i16, i32 0
  %a_28_2_vsplat = shufflevector <vscale x 8 x i16> %a_28_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_2 = mul <vscale x 8 x i16> %a_28_2_vsplat, %w_28_i16
  %add_28_2 = add <vscale x 8 x i16> %mul_28_2, %add_27_2
  %a_28_3_ptr = getelementptr i8, ptr %a_28_ptr, i32 3
  %a_28_3_i8 = load i8, ptr %a_28_3_ptr
  %a_28_3_i16 = sext i8 %a_28_3_i8 to i16
  %a_28_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_3_i16, i32 0
  %a_28_3_vsplat = shufflevector <vscale x 8 x i16> %a_28_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_3 = mul <vscale x 8 x i16> %a_28_3_vsplat, %w_28_i16
  %add_28_3 = add <vscale x 8 x i16> %mul_28_3, %add_27_3
  %a_28_4_ptr = getelementptr i8, ptr %a_28_ptr, i32 4
  %a_28_4_i8 = load i8, ptr %a_28_4_ptr
  %a_28_4_i16 = sext i8 %a_28_4_i8 to i16
  %a_28_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_4_i16, i32 0
  %a_28_4_vsplat = shufflevector <vscale x 8 x i16> %a_28_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_4 = mul <vscale x 8 x i16> %a_28_4_vsplat, %w_28_i16
  %add_28_4 = add <vscale x 8 x i16> %mul_28_4, %add_27_4
  %a_28_5_ptr = getelementptr i8, ptr %a_28_ptr, i32 5
  %a_28_5_i8 = load i8, ptr %a_28_5_ptr
  %a_28_5_i16 = sext i8 %a_28_5_i8 to i16
  %a_28_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_5_i16, i32 0
  %a_28_5_vsplat = shufflevector <vscale x 8 x i16> %a_28_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_5 = mul <vscale x 8 x i16> %a_28_5_vsplat, %w_28_i16
  %add_28_5 = add <vscale x 8 x i16> %mul_28_5, %add_27_5
  %a_28_6_ptr = getelementptr i8, ptr %a_28_ptr, i32 6
  %a_28_6_i8 = load i8, ptr %a_28_6_ptr
  %a_28_6_i16 = sext i8 %a_28_6_i8 to i16
  %a_28_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_6_i16, i32 0
  %a_28_6_vsplat = shufflevector <vscale x 8 x i16> %a_28_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_6 = mul <vscale x 8 x i16> %a_28_6_vsplat, %w_28_i16
  %add_28_6 = add <vscale x 8 x i16> %mul_28_6, %add_27_6
  %a_28_7_ptr = getelementptr i8, ptr %a_28_ptr, i32 7
  %a_28_7_i8 = load i8, ptr %a_28_7_ptr
  %a_28_7_i16 = sext i8 %a_28_7_i8 to i16
  %a_28_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_7_i16, i32 0
  %a_28_7_vsplat = shufflevector <vscale x 8 x i16> %a_28_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_7 = mul <vscale x 8 x i16> %a_28_7_vsplat, %w_28_i16
  %add_28_7 = add <vscale x 8 x i16> %mul_28_7, %add_27_7
  %a_28_8_ptr = getelementptr i8, ptr %a_28_ptr, i32 8
  %a_28_8_i8 = load i8, ptr %a_28_8_ptr
  %a_28_8_i16 = sext i8 %a_28_8_i8 to i16
  %a_28_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_8_i16, i32 0
  %a_28_8_vsplat = shufflevector <vscale x 8 x i16> %a_28_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_8 = mul <vscale x 8 x i16> %a_28_8_vsplat, %w_28_i16
  %add_28_8 = add <vscale x 8 x i16> %mul_28_8, %add_27_8
  %a_28_9_ptr = getelementptr i8, ptr %a_28_ptr, i32 9
  %a_28_9_i8 = load i8, ptr %a_28_9_ptr
  %a_28_9_i16 = sext i8 %a_28_9_i8 to i16
  %a_28_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_9_i16, i32 0
  %a_28_9_vsplat = shufflevector <vscale x 8 x i16> %a_28_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_9 = mul <vscale x 8 x i16> %a_28_9_vsplat, %w_28_i16
  %add_28_9 = add <vscale x 8 x i16> %mul_28_9, %add_27_9
  %a_28_10_ptr = getelementptr i8, ptr %a_28_ptr, i32 10
  %a_28_10_i8 = load i8, ptr %a_28_10_ptr
  %a_28_10_i16 = sext i8 %a_28_10_i8 to i16
  %a_28_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_10_i16, i32 0
  %a_28_10_vsplat = shufflevector <vscale x 8 x i16> %a_28_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_10 = mul <vscale x 8 x i16> %a_28_10_vsplat, %w_28_i16
  %add_28_10 = add <vscale x 8 x i16> %mul_28_10, %add_27_10
  %a_28_11_ptr = getelementptr i8, ptr %a_28_ptr, i32 11
  %a_28_11_i8 = load i8, ptr %a_28_11_ptr
  %a_28_11_i16 = sext i8 %a_28_11_i8 to i16
  %a_28_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_28_11_i16, i32 0
  %a_28_11_vsplat = shufflevector <vscale x 8 x i16> %a_28_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_28_11 = mul <vscale x 8 x i16> %a_28_11_vsplat, %w_28_i16
  %add_28_11 = add <vscale x 8 x i16> %mul_28_11, %add_27_11

  %w_29_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 29
  %w_29_i8 = load <vscale x 8 x i8>, ptr %w_29_ptr
  %w_29_i16 = sext <vscale x 8 x i8> %w_29_i8 to <vscale x 8 x i16>

  %a_29_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 29
  %a_29_0_ptr = getelementptr i8, ptr %a_29_ptr, i32 0
  %a_29_0_i8 = load i8, ptr %a_29_0_ptr
  %a_29_0_i16 = sext i8 %a_29_0_i8 to i16
  %a_29_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_0_i16, i32 0
  %a_29_0_vsplat = shufflevector <vscale x 8 x i16> %a_29_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_0 = mul <vscale x 8 x i16> %a_29_0_vsplat, %w_29_i16
  %add_29_0 = add <vscale x 8 x i16> %mul_29_0, %add_28_0
  %a_29_1_ptr = getelementptr i8, ptr %a_29_ptr, i32 1
  %a_29_1_i8 = load i8, ptr %a_29_1_ptr
  %a_29_1_i16 = sext i8 %a_29_1_i8 to i16
  %a_29_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_1_i16, i32 0
  %a_29_1_vsplat = shufflevector <vscale x 8 x i16> %a_29_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_1 = mul <vscale x 8 x i16> %a_29_1_vsplat, %w_29_i16
  %add_29_1 = add <vscale x 8 x i16> %mul_29_1, %add_28_1
  %a_29_2_ptr = getelementptr i8, ptr %a_29_ptr, i32 2
  %a_29_2_i8 = load i8, ptr %a_29_2_ptr
  %a_29_2_i16 = sext i8 %a_29_2_i8 to i16
  %a_29_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_2_i16, i32 0
  %a_29_2_vsplat = shufflevector <vscale x 8 x i16> %a_29_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_2 = mul <vscale x 8 x i16> %a_29_2_vsplat, %w_29_i16
  %add_29_2 = add <vscale x 8 x i16> %mul_29_2, %add_28_2
  %a_29_3_ptr = getelementptr i8, ptr %a_29_ptr, i32 3
  %a_29_3_i8 = load i8, ptr %a_29_3_ptr
  %a_29_3_i16 = sext i8 %a_29_3_i8 to i16
  %a_29_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_3_i16, i32 0
  %a_29_3_vsplat = shufflevector <vscale x 8 x i16> %a_29_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_3 = mul <vscale x 8 x i16> %a_29_3_vsplat, %w_29_i16
  %add_29_3 = add <vscale x 8 x i16> %mul_29_3, %add_28_3
  %a_29_4_ptr = getelementptr i8, ptr %a_29_ptr, i32 4
  %a_29_4_i8 = load i8, ptr %a_29_4_ptr
  %a_29_4_i16 = sext i8 %a_29_4_i8 to i16
  %a_29_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_4_i16, i32 0
  %a_29_4_vsplat = shufflevector <vscale x 8 x i16> %a_29_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_4 = mul <vscale x 8 x i16> %a_29_4_vsplat, %w_29_i16
  %add_29_4 = add <vscale x 8 x i16> %mul_29_4, %add_28_4
  %a_29_5_ptr = getelementptr i8, ptr %a_29_ptr, i32 5
  %a_29_5_i8 = load i8, ptr %a_29_5_ptr
  %a_29_5_i16 = sext i8 %a_29_5_i8 to i16
  %a_29_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_5_i16, i32 0
  %a_29_5_vsplat = shufflevector <vscale x 8 x i16> %a_29_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_5 = mul <vscale x 8 x i16> %a_29_5_vsplat, %w_29_i16
  %add_29_5 = add <vscale x 8 x i16> %mul_29_5, %add_28_5
  %a_29_6_ptr = getelementptr i8, ptr %a_29_ptr, i32 6
  %a_29_6_i8 = load i8, ptr %a_29_6_ptr
  %a_29_6_i16 = sext i8 %a_29_6_i8 to i16
  %a_29_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_6_i16, i32 0
  %a_29_6_vsplat = shufflevector <vscale x 8 x i16> %a_29_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_6 = mul <vscale x 8 x i16> %a_29_6_vsplat, %w_29_i16
  %add_29_6 = add <vscale x 8 x i16> %mul_29_6, %add_28_6
  %a_29_7_ptr = getelementptr i8, ptr %a_29_ptr, i32 7
  %a_29_7_i8 = load i8, ptr %a_29_7_ptr
  %a_29_7_i16 = sext i8 %a_29_7_i8 to i16
  %a_29_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_7_i16, i32 0
  %a_29_7_vsplat = shufflevector <vscale x 8 x i16> %a_29_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_7 = mul <vscale x 8 x i16> %a_29_7_vsplat, %w_29_i16
  %add_29_7 = add <vscale x 8 x i16> %mul_29_7, %add_28_7
  %a_29_8_ptr = getelementptr i8, ptr %a_29_ptr, i32 8
  %a_29_8_i8 = load i8, ptr %a_29_8_ptr
  %a_29_8_i16 = sext i8 %a_29_8_i8 to i16
  %a_29_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_8_i16, i32 0
  %a_29_8_vsplat = shufflevector <vscale x 8 x i16> %a_29_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_8 = mul <vscale x 8 x i16> %a_29_8_vsplat, %w_29_i16
  %add_29_8 = add <vscale x 8 x i16> %mul_29_8, %add_28_8
  %a_29_9_ptr = getelementptr i8, ptr %a_29_ptr, i32 9
  %a_29_9_i8 = load i8, ptr %a_29_9_ptr
  %a_29_9_i16 = sext i8 %a_29_9_i8 to i16
  %a_29_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_9_i16, i32 0
  %a_29_9_vsplat = shufflevector <vscale x 8 x i16> %a_29_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_9 = mul <vscale x 8 x i16> %a_29_9_vsplat, %w_29_i16
  %add_29_9 = add <vscale x 8 x i16> %mul_29_9, %add_28_9
  %a_29_10_ptr = getelementptr i8, ptr %a_29_ptr, i32 10
  %a_29_10_i8 = load i8, ptr %a_29_10_ptr
  %a_29_10_i16 = sext i8 %a_29_10_i8 to i16
  %a_29_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_10_i16, i32 0
  %a_29_10_vsplat = shufflevector <vscale x 8 x i16> %a_29_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_10 = mul <vscale x 8 x i16> %a_29_10_vsplat, %w_29_i16
  %add_29_10 = add <vscale x 8 x i16> %mul_29_10, %add_28_10
  %a_29_11_ptr = getelementptr i8, ptr %a_29_ptr, i32 11
  %a_29_11_i8 = load i8, ptr %a_29_11_ptr
  %a_29_11_i16 = sext i8 %a_29_11_i8 to i16
  %a_29_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_29_11_i16, i32 0
  %a_29_11_vsplat = shufflevector <vscale x 8 x i16> %a_29_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_29_11 = mul <vscale x 8 x i16> %a_29_11_vsplat, %w_29_i16
  %add_29_11 = add <vscale x 8 x i16> %mul_29_11, %add_28_11

  %w_30_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 30
  %w_30_i8 = load <vscale x 8 x i8>, ptr %w_30_ptr
  %w_30_i16 = sext <vscale x 8 x i8> %w_30_i8 to <vscale x 8 x i16>

  %a_30_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 30
  %a_30_0_ptr = getelementptr i8, ptr %a_30_ptr, i32 0
  %a_30_0_i8 = load i8, ptr %a_30_0_ptr
  %a_30_0_i16 = sext i8 %a_30_0_i8 to i16
  %a_30_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_0_i16, i32 0
  %a_30_0_vsplat = shufflevector <vscale x 8 x i16> %a_30_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_0 = mul <vscale x 8 x i16> %a_30_0_vsplat, %w_30_i16
  %add_30_0 = add <vscale x 8 x i16> %mul_30_0, %add_29_0
  %a_30_1_ptr = getelementptr i8, ptr %a_30_ptr, i32 1
  %a_30_1_i8 = load i8, ptr %a_30_1_ptr
  %a_30_1_i16 = sext i8 %a_30_1_i8 to i16
  %a_30_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_1_i16, i32 0
  %a_30_1_vsplat = shufflevector <vscale x 8 x i16> %a_30_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_1 = mul <vscale x 8 x i16> %a_30_1_vsplat, %w_30_i16
  %add_30_1 = add <vscale x 8 x i16> %mul_30_1, %add_29_1
  %a_30_2_ptr = getelementptr i8, ptr %a_30_ptr, i32 2
  %a_30_2_i8 = load i8, ptr %a_30_2_ptr
  %a_30_2_i16 = sext i8 %a_30_2_i8 to i16
  %a_30_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_2_i16, i32 0
  %a_30_2_vsplat = shufflevector <vscale x 8 x i16> %a_30_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_2 = mul <vscale x 8 x i16> %a_30_2_vsplat, %w_30_i16
  %add_30_2 = add <vscale x 8 x i16> %mul_30_2, %add_29_2
  %a_30_3_ptr = getelementptr i8, ptr %a_30_ptr, i32 3
  %a_30_3_i8 = load i8, ptr %a_30_3_ptr
  %a_30_3_i16 = sext i8 %a_30_3_i8 to i16
  %a_30_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_3_i16, i32 0
  %a_30_3_vsplat = shufflevector <vscale x 8 x i16> %a_30_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_3 = mul <vscale x 8 x i16> %a_30_3_vsplat, %w_30_i16
  %add_30_3 = add <vscale x 8 x i16> %mul_30_3, %add_29_3
  %a_30_4_ptr = getelementptr i8, ptr %a_30_ptr, i32 4
  %a_30_4_i8 = load i8, ptr %a_30_4_ptr
  %a_30_4_i16 = sext i8 %a_30_4_i8 to i16
  %a_30_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_4_i16, i32 0
  %a_30_4_vsplat = shufflevector <vscale x 8 x i16> %a_30_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_4 = mul <vscale x 8 x i16> %a_30_4_vsplat, %w_30_i16
  %add_30_4 = add <vscale x 8 x i16> %mul_30_4, %add_29_4
  %a_30_5_ptr = getelementptr i8, ptr %a_30_ptr, i32 5
  %a_30_5_i8 = load i8, ptr %a_30_5_ptr
  %a_30_5_i16 = sext i8 %a_30_5_i8 to i16
  %a_30_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_5_i16, i32 0
  %a_30_5_vsplat = shufflevector <vscale x 8 x i16> %a_30_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_5 = mul <vscale x 8 x i16> %a_30_5_vsplat, %w_30_i16
  %add_30_5 = add <vscale x 8 x i16> %mul_30_5, %add_29_5
  %a_30_6_ptr = getelementptr i8, ptr %a_30_ptr, i32 6
  %a_30_6_i8 = load i8, ptr %a_30_6_ptr
  %a_30_6_i16 = sext i8 %a_30_6_i8 to i16
  %a_30_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_6_i16, i32 0
  %a_30_6_vsplat = shufflevector <vscale x 8 x i16> %a_30_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_6 = mul <vscale x 8 x i16> %a_30_6_vsplat, %w_30_i16
  %add_30_6 = add <vscale x 8 x i16> %mul_30_6, %add_29_6
  %a_30_7_ptr = getelementptr i8, ptr %a_30_ptr, i32 7
  %a_30_7_i8 = load i8, ptr %a_30_7_ptr
  %a_30_7_i16 = sext i8 %a_30_7_i8 to i16
  %a_30_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_7_i16, i32 0
  %a_30_7_vsplat = shufflevector <vscale x 8 x i16> %a_30_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_7 = mul <vscale x 8 x i16> %a_30_7_vsplat, %w_30_i16
  %add_30_7 = add <vscale x 8 x i16> %mul_30_7, %add_29_7
  %a_30_8_ptr = getelementptr i8, ptr %a_30_ptr, i32 8
  %a_30_8_i8 = load i8, ptr %a_30_8_ptr
  %a_30_8_i16 = sext i8 %a_30_8_i8 to i16
  %a_30_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_8_i16, i32 0
  %a_30_8_vsplat = shufflevector <vscale x 8 x i16> %a_30_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_8 = mul <vscale x 8 x i16> %a_30_8_vsplat, %w_30_i16
  %add_30_8 = add <vscale x 8 x i16> %mul_30_8, %add_29_8
  %a_30_9_ptr = getelementptr i8, ptr %a_30_ptr, i32 9
  %a_30_9_i8 = load i8, ptr %a_30_9_ptr
  %a_30_9_i16 = sext i8 %a_30_9_i8 to i16
  %a_30_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_9_i16, i32 0
  %a_30_9_vsplat = shufflevector <vscale x 8 x i16> %a_30_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_9 = mul <vscale x 8 x i16> %a_30_9_vsplat, %w_30_i16
  %add_30_9 = add <vscale x 8 x i16> %mul_30_9, %add_29_9
  %a_30_10_ptr = getelementptr i8, ptr %a_30_ptr, i32 10
  %a_30_10_i8 = load i8, ptr %a_30_10_ptr
  %a_30_10_i16 = sext i8 %a_30_10_i8 to i16
  %a_30_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_10_i16, i32 0
  %a_30_10_vsplat = shufflevector <vscale x 8 x i16> %a_30_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_10 = mul <vscale x 8 x i16> %a_30_10_vsplat, %w_30_i16
  %add_30_10 = add <vscale x 8 x i16> %mul_30_10, %add_29_10
  %a_30_11_ptr = getelementptr i8, ptr %a_30_ptr, i32 11
  %a_30_11_i8 = load i8, ptr %a_30_11_ptr
  %a_30_11_i16 = sext i8 %a_30_11_i8 to i16
  %a_30_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_30_11_i16, i32 0
  %a_30_11_vsplat = shufflevector <vscale x 8 x i16> %a_30_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_30_11 = mul <vscale x 8 x i16> %a_30_11_vsplat, %w_30_i16
  %add_30_11 = add <vscale x 8 x i16> %mul_30_11, %add_29_11

  %w_31_ptr = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 31
  %w_31_i8 = load <vscale x 8 x i8>, ptr %w_31_ptr
  %w_31_i16 = sext <vscale x 8 x i8> %w_31_i8 to <vscale x 8 x i16>

  %a_31_ptr = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 31
  %a_31_0_ptr = getelementptr i8, ptr %a_31_ptr, i32 0
  %a_31_0_i8 = load i8, ptr %a_31_0_ptr
  %a_31_0_i16 = sext i8 %a_31_0_i8 to i16
  %a_31_0_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_0_i16, i32 0
  %a_31_0_vsplat = shufflevector <vscale x 8 x i16> %a_31_0_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_0 = mul <vscale x 8 x i16> %a_31_0_vsplat, %w_31_i16
  %add_31_0 = add <vscale x 8 x i16> %mul_31_0, %add_30_0
  %a_31_1_ptr = getelementptr i8, ptr %a_31_ptr, i32 1
  %a_31_1_i8 = load i8, ptr %a_31_1_ptr
  %a_31_1_i16 = sext i8 %a_31_1_i8 to i16
  %a_31_1_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_1_i16, i32 0
  %a_31_1_vsplat = shufflevector <vscale x 8 x i16> %a_31_1_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_1 = mul <vscale x 8 x i16> %a_31_1_vsplat, %w_31_i16
  %add_31_1 = add <vscale x 8 x i16> %mul_31_1, %add_30_1
  %a_31_2_ptr = getelementptr i8, ptr %a_31_ptr, i32 2
  %a_31_2_i8 = load i8, ptr %a_31_2_ptr
  %a_31_2_i16 = sext i8 %a_31_2_i8 to i16
  %a_31_2_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_2_i16, i32 0
  %a_31_2_vsplat = shufflevector <vscale x 8 x i16> %a_31_2_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_2 = mul <vscale x 8 x i16> %a_31_2_vsplat, %w_31_i16
  %add_31_2 = add <vscale x 8 x i16> %mul_31_2, %add_30_2
  %a_31_3_ptr = getelementptr i8, ptr %a_31_ptr, i32 3
  %a_31_3_i8 = load i8, ptr %a_31_3_ptr
  %a_31_3_i16 = sext i8 %a_31_3_i8 to i16
  %a_31_3_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_3_i16, i32 0
  %a_31_3_vsplat = shufflevector <vscale x 8 x i16> %a_31_3_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_3 = mul <vscale x 8 x i16> %a_31_3_vsplat, %w_31_i16
  %add_31_3 = add <vscale x 8 x i16> %mul_31_3, %add_30_3
  %a_31_4_ptr = getelementptr i8, ptr %a_31_ptr, i32 4
  %a_31_4_i8 = load i8, ptr %a_31_4_ptr
  %a_31_4_i16 = sext i8 %a_31_4_i8 to i16
  %a_31_4_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_4_i16, i32 0
  %a_31_4_vsplat = shufflevector <vscale x 8 x i16> %a_31_4_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_4 = mul <vscale x 8 x i16> %a_31_4_vsplat, %w_31_i16
  %add_31_4 = add <vscale x 8 x i16> %mul_31_4, %add_30_4
  %a_31_5_ptr = getelementptr i8, ptr %a_31_ptr, i32 5
  %a_31_5_i8 = load i8, ptr %a_31_5_ptr
  %a_31_5_i16 = sext i8 %a_31_5_i8 to i16
  %a_31_5_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_5_i16, i32 0
  %a_31_5_vsplat = shufflevector <vscale x 8 x i16> %a_31_5_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_5 = mul <vscale x 8 x i16> %a_31_5_vsplat, %w_31_i16
  %add_31_5 = add <vscale x 8 x i16> %mul_31_5, %add_30_5
  %a_31_6_ptr = getelementptr i8, ptr %a_31_ptr, i32 6
  %a_31_6_i8 = load i8, ptr %a_31_6_ptr
  %a_31_6_i16 = sext i8 %a_31_6_i8 to i16
  %a_31_6_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_6_i16, i32 0
  %a_31_6_vsplat = shufflevector <vscale x 8 x i16> %a_31_6_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_6 = mul <vscale x 8 x i16> %a_31_6_vsplat, %w_31_i16
  %add_31_6 = add <vscale x 8 x i16> %mul_31_6, %add_30_6
  %a_31_7_ptr = getelementptr i8, ptr %a_31_ptr, i32 7
  %a_31_7_i8 = load i8, ptr %a_31_7_ptr
  %a_31_7_i16 = sext i8 %a_31_7_i8 to i16
  %a_31_7_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_7_i16, i32 0
  %a_31_7_vsplat = shufflevector <vscale x 8 x i16> %a_31_7_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_7 = mul <vscale x 8 x i16> %a_31_7_vsplat, %w_31_i16
  %add_31_7 = add <vscale x 8 x i16> %mul_31_7, %add_30_7
  %a_31_8_ptr = getelementptr i8, ptr %a_31_ptr, i32 8
  %a_31_8_i8 = load i8, ptr %a_31_8_ptr
  %a_31_8_i16 = sext i8 %a_31_8_i8 to i16
  %a_31_8_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_8_i16, i32 0
  %a_31_8_vsplat = shufflevector <vscale x 8 x i16> %a_31_8_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_8 = mul <vscale x 8 x i16> %a_31_8_vsplat, %w_31_i16
  %add_31_8 = add <vscale x 8 x i16> %mul_31_8, %add_30_8
  %a_31_9_ptr = getelementptr i8, ptr %a_31_ptr, i32 9
  %a_31_9_i8 = load i8, ptr %a_31_9_ptr
  %a_31_9_i16 = sext i8 %a_31_9_i8 to i16
  %a_31_9_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_9_i16, i32 0
  %a_31_9_vsplat = shufflevector <vscale x 8 x i16> %a_31_9_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_9 = mul <vscale x 8 x i16> %a_31_9_vsplat, %w_31_i16
  %add_31_9 = add <vscale x 8 x i16> %mul_31_9, %add_30_9
  %a_31_10_ptr = getelementptr i8, ptr %a_31_ptr, i32 10
  %a_31_10_i8 = load i8, ptr %a_31_10_ptr
  %a_31_10_i16 = sext i8 %a_31_10_i8 to i16
  %a_31_10_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_10_i16, i32 0
  %a_31_10_vsplat = shufflevector <vscale x 8 x i16> %a_31_10_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_10 = mul <vscale x 8 x i16> %a_31_10_vsplat, %w_31_i16
  %add_31_10 = add <vscale x 8 x i16> %mul_31_10, %add_30_10
  %a_31_11_ptr = getelementptr i8, ptr %a_31_ptr, i32 11
  %a_31_11_i8 = load i8, ptr %a_31_11_ptr
  %a_31_11_i16 = sext i8 %a_31_11_i8 to i16
  %a_31_11_v0 = insertelement <vscale x 8 x i16> poison, i16 %a_31_11_i16, i32 0
  %a_31_11_vsplat = shufflevector <vscale x 8 x i16> %a_31_11_v0, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %mul_31_11 = mul <vscale x 8 x i16> %a_31_11_vsplat, %w_31_i16
  %add_31_11 = add <vscale x 8 x i16> %mul_31_11, %add_30_11

  %scale_i8 = load <vscale x 8 x i8>, ptr %scale_iter_ptr
  %scale_i32 = sext <vscale x 8 x i8> %scale_i8 to <vscale x 8 x i32>

  %add_0_i32 = sext <vscale x 8 x i16> %add_31_0 to <vscale x 8 x i32>
  %scaled_0 = mul <vscale x 8 x i32> %add_0_i32, %scale_i32
  %acc_0_new = add <vscale x 8 x i32> %acc_0, %scaled_0
  %add_1_i32 = sext <vscale x 8 x i16> %add_31_1 to <vscale x 8 x i32>
  %scaled_1 = mul <vscale x 8 x i32> %add_1_i32, %scale_i32
  %acc_1_new = add <vscale x 8 x i32> %acc_1, %scaled_1
  %add_2_i32 = sext <vscale x 8 x i16> %add_31_2 to <vscale x 8 x i32>
  %scaled_2 = mul <vscale x 8 x i32> %add_2_i32, %scale_i32
  %acc_2_new = add <vscale x 8 x i32> %acc_2, %scaled_2
  %add_3_i32 = sext <vscale x 8 x i16> %add_31_3 to <vscale x 8 x i32>
  %scaled_3 = mul <vscale x 8 x i32> %add_3_i32, %scale_i32
  %acc_3_new = add <vscale x 8 x i32> %acc_3, %scaled_3
  %add_4_i32 = sext <vscale x 8 x i16> %add_31_4 to <vscale x 8 x i32>
  %scaled_4 = mul <vscale x 8 x i32> %add_4_i32, %scale_i32
  %acc_4_new = add <vscale x 8 x i32> %acc_4, %scaled_4
  %add_5_i32 = sext <vscale x 8 x i16> %add_31_5 to <vscale x 8 x i32>
  %scaled_5 = mul <vscale x 8 x i32> %add_5_i32, %scale_i32
  %acc_5_new = add <vscale x 8 x i32> %acc_5, %scaled_5
  %add_6_i32 = sext <vscale x 8 x i16> %add_31_6 to <vscale x 8 x i32>
  %scaled_6 = mul <vscale x 8 x i32> %add_6_i32, %scale_i32
  %acc_6_new = add <vscale x 8 x i32> %acc_6, %scaled_6
  %add_7_i32 = sext <vscale x 8 x i16> %add_31_7 to <vscale x 8 x i32>
  %scaled_7 = mul <vscale x 8 x i32> %add_7_i32, %scale_i32
  %acc_7_new = add <vscale x 8 x i32> %acc_7, %scaled_7
  %add_8_i32 = sext <vscale x 8 x i16> %add_31_8 to <vscale x 8 x i32>
  %scaled_8 = mul <vscale x 8 x i32> %add_8_i32, %scale_i32
  %acc_8_new = add <vscale x 8 x i32> %acc_8, %scaled_8
  %add_9_i32 = sext <vscale x 8 x i16> %add_31_9 to <vscale x 8 x i32>
  %scaled_9 = mul <vscale x 8 x i32> %add_9_i32, %scale_i32
  %acc_9_new = add <vscale x 8 x i32> %acc_9, %scaled_9
  %add_10_i32 = sext <vscale x 8 x i16> %add_31_10 to <vscale x 8 x i32>
  %scaled_10 = mul <vscale x 8 x i32> %add_10_i32, %scale_i32
  %acc_10_new = add <vscale x 8 x i32> %acc_10, %scaled_10
  %add_11_i32 = sext <vscale x 8 x i16> %add_31_11 to <vscale x 8 x i32>
  %scaled_11 = mul <vscale x 8 x i32> %add_11_i32, %scale_i32
  %acc_11_new = add <vscale x 8 x i32> %acc_11, %scaled_11

  %a_iter_next = getelementptr <12 x i8>, ptr %a_iter_ptr, i32 32
  %w_iter_next = getelementptr <vscale x 8 x i8>, ptr %w_iter_ptr, i32 32
  %scale_iter_next = getelementptr <vscale x 8 x i8>, ptr %scale_iter_ptr, i32 1
  %loop_next = add i32 %loop_idx, 1
  %loop_cond = icmp slt i32 %loop_next, 8
  br i1 %loop_cond, label %loop, label %loop_end

loop_end:
  %res_0_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 0
  store <vscale x 8 x i32> %acc_0, ptr %res_0_ptr
  %res_1_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 1
  store <vscale x 8 x i32> %acc_1, ptr %res_1_ptr
  %res_2_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 2
  store <vscale x 8 x i32> %acc_2, ptr %res_2_ptr
  %res_3_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 3
  store <vscale x 8 x i32> %acc_3, ptr %res_3_ptr
  %res_4_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 4
  store <vscale x 8 x i32> %acc_4, ptr %res_4_ptr
  %res_5_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 5
  store <vscale x 8 x i32> %acc_5, ptr %res_5_ptr
  %res_6_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 6
  store <vscale x 8 x i32> %acc_6, ptr %res_6_ptr
  %res_7_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 7
  store <vscale x 8 x i32> %acc_7, ptr %res_7_ptr
  %res_8_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 8
  store <vscale x 8 x i32> %acc_8, ptr %res_8_ptr
  %res_9_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 9
  store <vscale x 8 x i32> %acc_9, ptr %res_9_ptr
  %res_10_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 10
  store <vscale x 8 x i32> %acc_10, ptr %res_10_ptr
  %res_11_ptr = getelementptr <vscale x 8 x i32>, ptr %res_ptr, i32 11
  store <vscale x 8 x i32> %acc_11, ptr %res_11_ptr

  ret void
}


